begin : GATE_CURRENT
	if (KG > 0.0)
	begin
		if (((psi_p > 0) && (TG < 0)) || ((psi_p < 0) && (TG > 0)))
		begin
			v1_ig		= sqrt(0.25 + (v_o + 2.0 * qs) / gamma_g2);
			v2_ig 		= 0.5 + v1_ig;
			psi_ox 		= (v_o + 2.0 * qs) / v2_ig;
			d_psi_dq 	= (2.0 / v2_ig) * (1.0 - (v_o + 2.0 * qs) / (2.0 * v1_ig * v2_ig * gamma_g2));
		end
		else
		begin
			psi_ox 		= v_o + 2.0 * qs;
			d_psi_dq 	= 2.0;
		end
		psi_x 			= abs(psi_ox) / xb;
		if (psi_x < 1.0)
		begin
			s1_px 		= sqrt(1.0 - psi_x);
			p_tun 		= exp( - ub * (1.0 / (1.0 + s1_px) + s1_px));
		end
		else 	p_tun 		= exp( - ub / psi_x);
		igo 			= qs * psi_ox * p_tun;
		if ((vs == vd) || (psi_ox == 0.0))
		begin
			nigc 		= igo * nq;
			nigs 		= nigc * 0.5;
			nigd 		= nigs;
		end
		else
		begin
			dq_dksi 	= (irp - if_) / (2.0 * qs + 1.0);
			a_gc 		= dq_dksi * (1.0 / qs + d_psi_dq / psi_ox);
			if (psi_x < 1.0)
			begin
				s1_px 	= sqrt(1.0 - psi_x);
				if (psi_ox > 0.0)	b_gc =  dq_dksi * d_psi_dq * (ub / xb) * (3.0 + psi_x) / (4.0 + 2.0 * s1_px * (2.0 + psi_x));
				else 			b_gc = -dq_dksi * d_psi_dq * (ub / xb) * (3.0 + psi_x) / (4.0 + 2.0 * s1_px * (2.0 + psi_x));
			end
			else
							b_gc =  dq_dksi * d_psi_dq * ub / (psi_x * psi_ox);
			nigc 		=       nq * igo * (2.0 + a_gc) / (2.0 - b_gc);
			nigs 		= 0.5 * nq * igo * (3.0 + a_gc) / (3.0 - b_gc);
			nigd 		= nigc - nigs;
		end
		if (vg > vfb)
		begin
			IGB 		= 0.0;
			IG 		= 2.0 * KG * WeffNF * Leff * UT2 * nigc / TOX2;
			IGD 		= 2.0 * KG * WeffNF * Leff * UT2 * nigd / TOX2;
			IGS 		= IG - IGD;
		end
		else
		begin
			IGB 		= KG * WeffNF * Leff * psi_ox * abs(psi_ox) * UT2 * p_tun / TOX2;
			IG 		= 0.0;
			IGD 		= 0.0;
			IGS 		= 0.0;
		end
// OVERLAP
		if (LOVIG != 0)
		begin
			psi_oxr_ov_s 		= (vg - vs > vfb_ov)?
						  vg - vs - pow( sqrt( vg - vs - vfb_ov + gamma_g2  * 0.25) - gamma_g * 0.5 ,2.0) :
						  vg - vs + pow( sqrt(-vg + vs + vfb_ov + gamma_ov2 * 0.25) - gamma_ov * 0.5 ,2.0);
			psi_xr_ov_s 		= abs(psi_oxr_ov_s) / xb;
			if (psi_xr_ov_s < 1.0)
			begin
				s1_px 		= sqrt(1.0 - psi_xr_ov_s);
				p_tun_sov 	= exp( - ub * (1.0 / (1.0 + s1_px) + s1_px));
			end
			else 	p_tun_sov 	= exp( - ub / psi_xr_ov_s);
			IGSOV 			= KG * WeffNF * LOVIG * psi_oxr_ov_s * abs(psi_oxr_ov_s) * UT2 * p_tun_sov / TOX2;

			psi_oxr_ov_d 		= (vg - vd > vfb_ov)?
						  vg - vd - pow( sqrt( vg - vd - vfb_ov + gamma_g2  * 0.25) - gamma_g * 0.5 ,2.0) :
						  vg - vd + pow( sqrt(-vg + vd + vfb_ov + gamma_ov2 * 0.25) - gamma_ov * 0.5 ,2.0);
			psi_xr_ov_d 		= abs(psi_oxr_ov_d) / xb;
			if (psi_xr_ov_d < 1.0)
			begin
				s1_px 		= sqrt(1.0 - psi_xr_ov_d);
				p_tun_dov 	= exp( - ub * (1.0 / (1.0 + s1_px) + s1_px));
			end
			else 	p_tun_dov 	= exp( - ub / psi_xr_ov_d);
			IGDOV 			= KG * WeffNF * LOVIG * psi_oxr_ov_d * abs(psi_oxr_ov_d) * UT2 * p_tun_dov / TOX2;
		end
		else
		begin
			IGSOV 			= 0.0;
			IGDOV 			= 0.0;
		end
	end
	else
	begin
		IG 	= 0.0;
		IGS 	= 0.0;
		IGD 	= 0.0;
		IGB 	= 0.0;
		IGSOV 	= 0.0;
		IGDOV 	= 0.0;
	end
end

`ifdef DC_S
// GATE CURRENTS
	I(b ,g ) <+ -SIGN_M * IGB;
	I(s ,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGS       + (1 - d_gt_s_flag) * IGD);
	I(d ,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGD       + (1 - d_gt_s_flag) * IGS);
// OVERLAP GATE CURRENTS
	I(s ,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGSOV     + (1 - d_gt_s_flag) * IGDOV);
	I(d ,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGDOV     + (1 - d_gt_s_flag) * IGSOV);
`endif
`ifdef DC
// GATE CURRENTS
	I(b ,g ) <+ -SIGN_M * IGB;
	I(si,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGS       + (1 - d_gt_s_flag) * IGD);
	I(di,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGD       + (1 - d_gt_s_flag) * IGS);
// OVERLAP GATE CURRENTS
	I(si,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGSOV     + (1 - d_gt_s_flag) * IGDOV);
	I(di,g ) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGDOV     + (1 - d_gt_s_flag) * IGSOV);
`endif
`ifdef RF_S
// GATE CURRENTS
	I(b ,gi) <+ -SIGN_M * IGB;
	I(si,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGS       + (1 - d_gt_s_flag) * IGD);
	I(di,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGD       + (1 - d_gt_s_flag) * IGS);
// OVERLAP GATE CURRENTS
	I(si,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGSOV     + (1 - d_gt_s_flag) * IGDOV);
	I(di,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGDOV     + (1 - d_gt_s_flag) * IGSOV);
`endif
`ifdef RF
// GATE CURRENTS
	I(b ,gi) <+ -SIGN_M * IGB;
	I(si,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGS       + (1 - d_gt_s_flag) * IGD);
	I(di,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGD       + (1 - d_gt_s_flag) * IGS);
// OVERLAP GATE CURRENTS
	I(si,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGSOV     + (1 - d_gt_s_flag) * IGDOV);
	I(di,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGDOV     + (1 - d_gt_s_flag) * IGSOV);
`endif
`ifdef NQS
// GATE CURRENTS
	I(b ,gi) <+ -SIGN_M * IGB;
	I(si,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGS       + (1 - d_gt_s_flag) * IGD);
	I(di,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGD       + (1 - d_gt_s_flag) * IGS);
// OVERLAP GATE CURRENTS
	I(si,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGSOV     + (1 - d_gt_s_flag) * IGDOV);
	I(di,gi) <+ -SIGN_M * 0.5 * ((d_gt_s_flag + 1) * IGDOV     + (1 - d_gt_s_flag) * IGSOV);
`endif
