`ifdef NQS
	`ifdef RF
		`undef RF
	`endif
	`ifdef RF_S
		`undef RF_S
	`endif
	`ifdef DC
		`undef DC
	`endif
	`ifdef DC_S
		`undef DC_S
	`endif
	`ifdef NLS
	`else
		`define NLS 5
	`endif
`else
	`ifdef RF
		`ifdef RF_S
			`undef RF_S
		`endif
		`ifdef DC
			`undef DC
		`endif
		`ifdef DC_S
			`undef DC_S
		`endif
	`else
		`ifdef RF_S
			`ifdef DC
				`undef DC
			`endif
			`ifdef DC_S
				`undef DC_S
			`endif
		`else
			`ifdef DC
				`ifdef DC_S
					`undef DC_S
				`endif
			`else
				`ifdef DC_S
				`else
					`define DC_S
				`endif
			`endif
		`endif
	`endif
`endif

