begin : IMPACT_IONIZATION_CURRENT_IDB
	v_ib 		= (vd - vs) - IBN * 2.0 * vdssat;
	if ((v_ib > 0.0) && (IBA > 0.0))
	begin
		tmp 	= IBB_t * LC / (v_ib * UT);
		if (tmp > 70.0)
			IDB 	= 0.0;
		else
			IDB 	= IDS * v_ib * UT * exp(-tmp) * IBA / IBB_t;
	end
	else
			IDB 	= 0.0;
end //  IMPACT_IONIZATION_CURRENT_IDB

`ifdef DC_S
	I(d ,b ) <+  SIGN_M * 0.5 * (d_gt_s_flag + 1) * IDB;
	I(s ,b ) <+  SIGN_M * 0.5 * (1 - d_gt_s_flag) * IDB;
`endif

`ifdef DC
	I(di,b ) <+  SIGN_M * 0.5 * (d_gt_s_flag + 1) * IDB;
	I(si,b ) <+  SIGN_M * 0.5 * (1 - d_gt_s_flag) * IDB;
`endif

`ifdef RF_S
	I(di,bi) <+  SIGN_M * 0.5 * (d_gt_s_flag + 1) * IDB;
	I(si,bi) <+  SIGN_M * 0.5 * (1 - d_gt_s_flag) * IDB;
`endif

`ifdef RF
	I(di,bi) <+  SIGN_M * 0.5 * (d_gt_s_flag + 1) * IDB;
	I(si,bi) <+  SIGN_M * 0.5 * (1 - d_gt_s_flag) * IDB;
`endif

`ifdef NQS
	I(di,bi) <+  SIGN_M * 0.5 * (d_gt_s_flag + 1) * IDB;
	I(si,bi) <+  SIGN_M * 0.5 * (1 - d_gt_s_flag) * IDB;
`endif
