// EXTERNAL: DIODES

begin : DIODES
begin :	TEMPERATURE_DIODES
// source
	jss_t 		= JSS * temp_arg_S;
	jssws_t 	= JSSWS * temp_arg_S;
	jsswgs_t 	= JSSWGS * temp_arg_S;
	pbs_t 		= PBS - (TPB * dT);
	pbsws_t 	= PBSWS - (TPBSW * dT);
	pbswgs_t 	= PBSWGS - (TPBSWG * dT);
	cjs_t 		= CJS * (1.0 + TCJ * dT);
	cjsws_t 	= CJSWS * (1.0 + TCJSW * dT);
	cjswgs_t 	= CJSWGS * (1.0 + TCJSWG * dT);
	jtss_t 		= JTSS * exp( - eg_nom / UT * XTSS * (1.0 - rT));
	jtssws_t 	= JTSSWS * exp( - eg_nom / UT * XTSSWS * (1.0 - rT));
	jtsswgs_t 	= JTSSWGS * exp( - eg_nom / UT * XTSSWGS * (1.0 - rT));
	njtss_t 	= NJTSS * (1.0 + (rT - 1.0) * TNJTSS);
	njtssws_t 	= NJTSSWS * (1.0 + (rT - 1.0) * TNJTSSWS);
	njtsswgs_t 	= NJTSSWGS * (1.0 + (rT - 1.0) * TNJTSSWGS);
// drain
	jsd_t 		= JSD * temp_arg_D;
	jsswd_t 	= JSSWD * temp_arg_D;
	jsswgd_t 	= JSSWGD * temp_arg_D;
	pbd_t 		= PBD - (TPB * dT);
	pbswd_t 	= PBSWD - (TPBSW * dT);
	pbswgd_t 	= PBSWGD - (TPBSWG * dT);
	cjd_t 		= CJD * (1.0 + TCJ * dT);
	cjswd_t 	= CJSWD * (1.0 + TCJSW * dT);
	cjswgd_t 	= CJSWGD * (1.0 + TCJSWG * dT);
	jtsd_t 		= JTSD * exp( - eg_nom / UT * XTSD * (1.0 - rT));
	jtsswd_t 	= JTSSWD * exp( - eg_nom / UT * XTSSWD * (1.0 - rT));
	jtsswgd_t 	= JTSSWGD * exp( - eg_nom / UT * XTSSWGD * (1.0 - rT));
	njtsd_t 	= NJTSD * (1.0 + (rT - 1.0) * TNJTSD);
	njtsswd_t 	= NJTSSWD * (1.0 + (rT - 1.0) * TNJTSSWD);
	njtsswgd_t 	= NJTSSWGD * (1.0 + (rT - 1.0) * TNJTSSWGD);
end // 	TEMPERATURE_DIODES

begin : SCALING_GEOMETRY_JUNCTION_DIODES
	if ((AS == 0.0) && (HDIF > 0.0))
	begin
		if (NF % 2 == 0) // EVEN NUMBER OF FINGERS
			as = hdif * Weff * (NF + 2);
		else		 // ODD NUMBER OF FINGERS
			as = hdif * Weff * (NF + 1);
	end
	else 					
		as = AS * SCALE * SCALE;
	
	if ((PS == 0.0) && (HDIF > 0.0)) 	
	begin
		if (NF % 2 == 0) // EVEN NUMBER OF FINGERS
			ps = 2.0 * (hdif * (NF + 2) + Weff);
		else		 // ODD NUMBER OF FINGERS
			ps = 2.0 * hdif * (NF + 1) + Weff;
	end
	else
		ps = PS * SCALE;

	if ((AD == 0.0) && (HDIF > 0.0))
	begin
		if (NF % 2 == 0) // EVEN NUMBER OF FINGERS
			ad = hdif * Weff * (NF    );
		else		 // ODD NUMBER OF FINGERS
			ad = hdif * Weff * (NF + 1);
	end
	else
		ad = AD * SCALE * SCALE;

	if ((PD == 0.0) && (HDIF > 0.0)) 		
	begin
		if (NF % 2 == 0) // EVEN NUMBER OF FINGERS
			pd = 2.0 * hdif * NF;
		else		 // ODD NUMBER OF FINGERS
			pd = 2.0 * hdif * (NF + 1) + Weff;
	end
	else
		pd = PD * SCALE;
end //  SCALING_GEOMETRY_JUNCTION_DIODES

`ifdef DC_S
	v_si_b = SIGN * V(s ,b  ); v_di_b = SIGN * V(d ,b  );
`endif
`ifdef DC
	v_si_b = SIGN * V(si,b  ); v_di_b = SIGN * V(di,b  );
`endif
`ifdef RF_S
	v_si_b = SIGN * V(si,bi ); v_di_b = SIGN * V(di,bi );
`endif
`ifdef RF
	v_si_b = SIGN * V(si,bsi); v_di_b = SIGN * V(di,bdi);
`endif
`ifdef NQS
	v_si_b = SIGN * V(si,bsi); v_di_b = SIGN * V(di,bdi);
`endif

// SOURCE-BULK CURRENT
	is_s 		= jss_t * as + jssws_t * ps + jsswgs_t * WeffNF;
	arg_s 		= - v_si_b * rT / (UT * NJS);
	if (arg_s < -40.0) arg_s = -40.0;
	f_breakdown_s 	= 1.0 + XJBVS * exp(-(-v_si_b + BVS) * rT / (UT * NJS));
// SOURCE:TRAP - ASSISTED TUNNELING CURRENT
	isb_tun 	= WeffNF * jtsswgs_t * (exp(v_si_b * rT / (UT * njtsswgs_t) * VTSSWGS / max(VTSSWGS + v_si_b,1.0E-3)) - 1.0);
	isb_tun 	= isb_tun + ps * jtssws_t * (exp(v_si_b * rT / (UT * njtssws_t) * VTSSWS / max(VTSSWS + v_si_b,1.0E-3)) - 1.0);
	isb_tun 	= isb_tun + as * jtss_t * (exp(v_si_b * rT / (UT * njtss_t) * VTSS / max(VTSS + v_si_b,1.0E-3)) - 1.0);
	ISBJ		= (is_s * (1.0 - exp(arg_s)) * f_breakdown_s + v_si_b * GMIN + isb_tun);
// DRAIN-BULK CURRENT
	is_d 		= jsd_t * ad + jsswd_t * pd + jsswgd_t * WeffNF;
	arg_d 		= - v_di_b * rT / (UT * NJD);
	if (arg_d < -40.0) arg_d = -40.0;
	f_breakdown_d 	= 1.0 + XJBVD * exp(-(-v_di_b + BVD) * rT / (UT * NJD));
// DRAIN: TRAP - ASSISTED TUNNELING CURRENT
	idb_tun 	= + WeffNF * jtsswgd_t * (exp(v_di_b * rT / (UT * njtsswgd_t) * VTSSWGD / max(VTSSWGD + v_di_b,1.0E-3)) - 1.0);
	idb_tun 	= idb_tun + pd * jtsswd_t * (exp(v_di_b * rT / (UT * njtsswd_t) * VTSSWD / max(VTSSWD + v_di_b,1.0E-3)) - 1.0);
	idb_tun 	= idb_tun + ad * jtsd_t * (exp(v_di_b * rT / (UT * njtsd_t) * VTSD / max(VTSD + v_di_b,1.0E-3)) - 1.0);
	IDBJ 		= (is_d * (1.0 - exp(arg_d)) * f_breakdown_d + v_di_b * GMIN + idb_tun);
// SOURCE-BULK CAPACITANCE CHARGES
	if (v_si_b > 0.0)
	begin
		csb_s 	= cjs_t    * as     * exp( - MJS    * ln(1.0 + v_si_b / pbs_t   ));
		cssw_s 	= cjsws_t  * ps     * exp( - MJSWS  * ln(1.0 + v_si_b / pbsws_t ));
		csswg_s	= cjswgs_t * WeffNF * exp( - MJSWGS * ln(1.0 + v_si_b / pbswgs_t));
		qsb_s   = cjs_t    * as     * pbs_t    * (1.0 - exp((1.0 - MJS)    * ln(1.0 + v_si_b / pbs_t   ))) / (1.0 - MJS); 
		qssw_s  = cjsws_t  * ps     * pbsws_t  * (1.0 - exp((1.0 - MJSWS)  * ln(1.0 + v_si_b / pbsws_t ))) / (1.0 - MJSWS); 
		qsswg_s = cjswgs_t * WeffNF * pbswgs_t * (1.0 - exp((1.0 - MJSWGS) * ln(1.0 + v_si_b / pbswgs_t))) / (1.0 - MJSWGS); 
	end
	else
	begin
		csb_s	= cjs_t    * as     * (1.0 - MJS    * v_si_b / pbs_t   );
		cssw_s	= cjsws_t  * ps     * (1.0 - MJSWS  * v_si_b / pbsws_t );
		csswg_s	= cjswgs_t * WeffNF * (1.0 - MJSWGS * v_si_b / pbswgs_t);
		qsb_s   = cjs_t    * as     * (- v_si_b + MJS    * 0.5 / pbs_t    * (v_si_b * v_si_b)); 
		qssw_s  = cjsws_t  * ps     * (- v_si_b + MJSWS  * 0.5 / pbsws_t  * (v_si_b * v_si_b)); 
		qsswg_s = cjswgs_t * WeffNF * (- v_si_b + MJSWGS * 0.5 / pbswgs_t * (v_si_b * v_si_b)); 
	end
	CSBJ 		= csb_s + cssw_s + csswg_s;
	QSBJ 		= - (qsb_s + qssw_s + qsswg_s);
// DRAIN-BULK CAPACITANCE CHARGES
	if (v_di_b > 0.0)
	begin
		csb_d 	= cjd_t    * ad     * exp( - MJD    * ln(1.0 + v_di_b / pbd_t   ));
		cssw_d 	= cjswd_t  * pd     * exp( - MJSWD  * ln(1.0 + v_di_b / pbswd_t ));
		csswg_d	= cjswgd_t * WeffNF * exp( - MJSWGD * ln(1.0 + v_di_b / pbswgd_t));
		qsb_d   = cjd_t    * ad     * pbd_t    * (1.0 - exp((1.0 - MJD)    * ln(1.0 + v_di_b / pbd_t   ))) / (1.0 - MJD); 
		qssw_d  = cjswd_t  * pd     * pbswd_t  * (1.0 - exp((1.0 - MJSWD)  * ln(1.0 + v_di_b / pbswd_t ))) / (1.0 - MJSWD); 
		qsswg_d = cjswgd_t * WeffNF * pbswgd_t * (1.0 - exp((1.0 - MJSWGD) * ln(1.0 + v_di_b / pbswgd_t))) / (1.0 - MJSWGD); 
	end
	else
	begin
		csb_d	= cjd_t    * ad     * (1.0 - MJD    * v_di_b / pbd_t   );
		cssw_d	= cjswd_t  * pd     * (1.0 - MJSWD  * v_di_b / pbswd_t );
		csswg_d	= cjswgd_t * WeffNF * (1.0 - MJSWGD * v_di_b / pbswgd_t);
		qsb_d   = cjd_t    * ad     * (- v_di_b + MJD    * 0.5 / pbd_t    * (v_di_b * v_di_b)); 
		qssw_d  = cjswd_t  * pd     * (- v_di_b + MJSWD  * 0.5 / pbswd_t  * (v_di_b * v_di_b)); 
		qsswg_d = cjswgd_t * WeffNF * (- v_di_b + MJSWGD * 0.5 / pbswgd_t * (v_di_b * v_di_b)); 
	end
	CDBJ 		= csb_d + cssw_d + csswg_d;
	QDBJ 		= - (qsb_d + qssw_d + qsswg_d);
end //  DIODES


`ifdef DC_S
// DIODES IV
	I(d ,b ) <+  SIGN_M * IDBJ;
	I(s ,b ) <+  SIGN_M * ISBJ;
// DIODES CV
	I(d ,b ) <+  SIGN_M * ddt(QDBJ);
	I(s ,b ) <+  SIGN_M * ddt(QSBJ);
`endif

`ifdef DC
   $strobe("IDB = ", SIGN_M * IDBJ);
   $strobe("IDBDvd = ", ddx(SIGN_M * IDBJ, V(di)));
   $strobe("IDBDvs = ", ddx(SIGN_M * IDBJ, V(si)));
   $strobe("IDBDvg = ", ddx(SIGN_M * IDBJ, V(g)));
   $strobe("ISB = ", SIGN_M * ISBJ);
   $strobe("ISBDvd = ", ddx(SIGN_M * ISBJ, V(di)));
   $strobe("ISBDvs = ", ddx(SIGN_M * ISBJ, V(si)));
   $strobe("ISBDvg = ", ddx(SIGN_M * ISBJ, V(g)));
// DIODES IV
	I(di,b ) <+  SIGN_M * IDBJ;
	I(si,b ) <+  SIGN_M * ISBJ;
// DIODES CV
	I(di,b ) <+  SIGN_M * ddt(QDBJ);
	I(si,b ) <+  SIGN_M * ddt(QSBJ);
`endif

`ifdef RF_S
// DIODES IV
	I(di,bi) <+  SIGN_M * IDBJ;
	I(si,bi) <+  SIGN_M * ISBJ;
// DIODES CV
	I(di,bi) <+  SIGN_M * ddt(QDBJ);
	I(si,bi) <+  SIGN_M * ddt(QSBJ);
`endif

`ifdef RF
// DIODES IV
	I(di,bdi) <+  SIGN_M * IDBJ;
	I(si,bsi) <+  SIGN_M * ISBJ;
// DIODES CV
	I(di,bdi) <+  SIGN_M * ddt(QDBJ);
	I(si,bsi) <+  SIGN_M * ddt(QSBJ);
`endif

`ifdef NQS
// DIODES IV
	I(di,bdi) <+  SIGN_M * IDBJ;
	I(si,bsi) <+  SIGN_M * ISBJ;
// DIODES CV
	I(di,bdi) <+  SIGN_M * ddt(QDBJ);
	I(si,bsi) <+  SIGN_M * ddt(QSBJ);
`endif
