`ifdef DEFINITIONS_INCLUDE
`else

// CONSTANTS
`define C_EPSSIL		(1.03594314E-10)
`define C_EPSOX			(34.53144E-12)
`define C_QE			(1.602E-19)
`define C_K			(1.3807E-23)
`define POS_MIN			(1.0E-6)
`define MINIMUM_RESISTANCE	(1.0E-3)
`define SQRT2			(1.4142135623730950488016887242097)
`define ONE3RD			(0.33333333333333333333333333333333)
`define TWO3RDS			(0.66666666666666666666666666666667)
`define ONESQRT2		(0.70710678118654752440084436210485)
`define PI 			(3.1415926535897932384626433832795)
`define UT(T) 			((`C_K * (T)) / `C_QE)
// END: CONSTANTS

// USEFUL FUNCTIONS
`define MAX(x,y) 		((x)>(y)?(x):(y))
`define MIN(x,y) 		((x)<(y)?(x):(y))
`define MIN_MAX(val,min,max) 	(`MIN(`MAX(val,min),max))
`define MINA(x,y,a) 		(0.5*((x)+(y)-sqrt(((x)-(y))*((x)-(y))+(a))))
`define MAXA(x,y,a) 		(0.5*((x)+(y)+sqrt(((x)-(y))*((x)-(y))+(a))))
`define MINA_MAXA(val,min,max,a) (`MINA(`MAXA(val,min,a),max,a))
// END: USEFUL FUNCTIONS

//ADMS
`ifdef insideADMS
	`define MODEL @(initial_model)
	`define INSTANCE @(initial_instance)
	`define ATTR(txt) (*txt*)
`else
	`define MODEL
	`define INSTANCE
	`define ATTR(txt)
`endif

`define DEFINITIONS_INCLUDE
`endif