begin : OVERLAP_CAPACITANCES_CHARGES
	if (LOV > 0.0) 	
	begin
		// SOURCE
		if (TG < 0)
		begin
			vgsov_p 		= vg - VOV * vs - vfb_ov;
			if (vgsov_p > 0.0)
			begin
				gamma_dep_sov 	= gamma_g_ov;
				gamma_acc_sov 	= gamma_ov;
				v0_sov 		= vgsov_p;
			end
			else
			begin
				gamma_dep_sov 	= gamma_ov;
				gamma_acc_sov 	= gamma_g_ov;
				v0_sov 		= - vgsov_p;
			end
			a0_sov 			= 1.0 + gamma_acc_sov * `ONESQRT2;
			a1_sov 			= gamma_dep_sov / gamma_acc_sov;
			a2_sov 			= a0_sov / (a0_sov + a1_sov);
			a3_sov 			= 1.0 + gamma_dep_sov * `ONESQRT2 + a1_sov;
			v1_sov 			= v0_sov * 0.5 - 3.0 * a2_sov * a3_sov;
			dpsigs0 		= v1_sov + sqrt(v1_sov * v1_sov + 6.0 * a2_sov * v0_sov);
			gamma_dep2_sov 		= gamma_dep_sov * (0.5 + 3.0 / (3.0 * `SQRT2 * gamma_acc_sov + v0_sov - dpsigs0));
			a4_sov 			= 1.0 - exp(-dpsigs0);
			v2_sov 			= v0_sov - a4_sov;
			tmp 			= v2_sov / (gamma_dep2_sov + sqrt(gamma_dep2_sov * gamma_dep2_sov + v2_sov));
			dpsigs 			= tmp * tmp + a4_sov;
			v2b_sov 		= v0_sov - dpsigs;
			v3_sov 			= v2b_sov * 0.5;
			tmp 			= v3_sov + 3.0 * a0_sov;
			if (vgsov_p > 0.0) 	dpsiox_s = v3_sov - 3.0 * a0_sov + sqrt(tmp * tmp - 6.0 * v2b_sov);
			else 			dpsiox_s = - (v3_sov - 3.0 * a0_sov + sqrt(tmp * tmp - 6.0 * v2b_sov));
		end
		else
		begin
			vgsov_p 		= vg - VOV * vs - vfb_ov;
			if (vgsov_p > 0.0)
			begin
				gamma_acc_sov 	= gamma_ov;
				v0_sov 		= vgsov_p;
				a0_sov 		= 1.0 + gamma_acc_sov * `ONESQRT2;
				v1_sov 		= v0_sov * 0.5 - 3.0 * a0_sov * a0_sov;
				dpsigs0 	= v1_sov + sqrt(v1_sov * v1_sov);
				dpsigs 		= 1.0 - exp(-dpsigs0);
				v2b_sov 	= v0_sov - dpsigs;
				v3_sov 		= v2b_sov * 0.5;
				tmp 		= v3_sov + 3.0 * a0_sov;
				dpsiox_s 	= v3_sov - 3.0 * a0_sov + sqrt(tmp * tmp - 6.0 * v2b_sov);
			end
			else
			begin
				gamma_dep_sov 	= gamma_ov;
				v0_sov 		= - vgsov_p;
				a3_sov 		= 1.0 + gamma_dep_sov * `ONESQRT2;
				v1_sov 		= v0_sov * 0.5 - 3.0 * a3_sov;
				dpsigs0 	= v1_sov + sqrt(v1_sov * v1_sov + 6.0 * v0_sov);
				gamma_dep2_sov 	= gamma_dep_sov * 0.5;
				a4_sov 		= 1.0 - exp(-dpsigs0);
				v2_sov 		= v0_sov - a4_sov;
				tmp 		= v2_sov / (gamma_dep2_sov + sqrt(gamma_dep2_sov * gamma_dep2_sov + v2_sov));
				dpsigs 		= tmp * tmp + a4_sov;
				v2b_sov 	= v0_sov - dpsigs;
				dpsiox_s 	= - v2b_sov;
			end
		end

		// DRAIN
		if (TG < 0)
		begin
			vgdov_p 		= vg - VOV * vd - vfb_ov;
			if (vgdov_p > 0.0)
			begin
				gamma_dep_dov 	= gamma_g_ov;
				gamma_acc_dov 	= gamma_ov;
				v0_dov 		= vgdov_p;
			end
			else
			begin
				gamma_dep_dov 	= gamma_ov;
				gamma_acc_dov 	= gamma_g_ov;
				v0_dov 		= - vgdov_p;
			end
			a0_dov 			= 1.0 + gamma_acc_dov * `ONESQRT2;
			a1_dov 			= gamma_dep_dov / gamma_acc_dov;
			a2_dov 			= a0_dov / (a0_dov + a1_dov);
			a3_dov 			= 1.0 + gamma_dep_dov * `ONESQRT2 + a1_dov;
			v1_dov 			= v0_dov * 0.5 - 3.0 * a2_dov * a3_dov;
			dpsigd0 		= v1_dov + sqrt(v1_dov * v1_dov + 6.0 * a2_dov * v0_dov);
			gamma_dep2_dov 		= gamma_dep_dov * (0.5 + 3.0 / (3.0 * `SQRT2 * gamma_acc_dov + v0_dov - dpsigd0));
			a4_dov 			= 1.0 - exp(-dpsigd0);
			v2_dov 			= v0_dov - a4_dov;
			tmp 			= v2_dov / (gamma_dep2_dov + sqrt(gamma_dep2_dov * gamma_dep2_dov + v2_dov));
			dpsigd 			= tmp * tmp + a4_dov;
			v2b_dov 		= v0_dov - dpsigd;
			v3_dov 			= v2b_dov * 0.5;
			tmp 			= v3_dov + 3.0 * a0_dov;
			if (vgdov_p > 0.0) 	dpsiox_d = v3_dov - 3.0 * a0_dov + sqrt(tmp * tmp - 6.0 * v2b_dov);
			else 			dpsiox_d = - (v3_dov - 3.0 * a0_dov + sqrt(tmp * tmp - 6.0 * v2b_dov));
		end
		else
		begin
			vgdov_p 		= vg - VOV * vd - vfb_ov;
			if (vgdov_p > 0.0)
			begin
				gamma_acc_dov 	= gamma_ov;
				v0_dov 		= vgdov_p;
				a0_dov 		= 1.0 + gamma_acc_dov * `ONESQRT2;
				v1_dov 		= v0_dov * 0.5 - 3.0 * a0_dov * a0_dov;
				dpsigd0 	= v1_dov + sqrt(v1_dov * v1_dov);
				dpsigd 		= 1.0 - exp(-dpsigd0);
				v2b_dov 	= v0_dov - dpsigd;
				v3_dov 		= v2b_dov * 0.5;
				tmp 		= v3_dov + 3.0 * a0_dov;
				dpsiox_d 	= v3_dov - 3.0 * a0_dov + sqrt(tmp * tmp - 6.0 * v2b_dov);
			end
			else
			begin
				gamma_dep_dov 	= gamma_ov;
				v0_dov 		= - vgdov_p;
				a3_dov 		= 1.0 + gamma_dep_dov * `ONESQRT2;
				v1_dov 		= v0_dov * 0.5 - 3.0 * a3_dov;
				dpsigd0 	= v1_dov + sqrt(v1_dov * v1_dov + 6.0 * v0_dov);
				gamma_dep2_dov 	= gamma_dep_dov * 0.5;
				a4_dov 		= 1.0 - exp(-dpsigd0);
				v2_dov 		= v0_dov - a4_dov;
				tmp 		= v2_dov / (gamma_dep2_dov + sqrt(gamma_dep2_dov * gamma_dep2_dov + v2_dov));
				dpsigd 		= tmp * tmp + a4_dov;
				v2b_dov 	= v0_dov - dpsigd;
				dpsiox_d 	= - v2b_dov;
			end
		end	
		QSOV 		= - Q0OV * dpsiox_s;
		QDOV 		= - Q0OV * dpsiox_d; 
	end
	else 	
	begin 	
		dpsiox_s	= 0.0;
		QSOV  		= 0.0;
		dpsiox_d	= 0.0;
		QDOV 		= 0.0;
	end
end 

`ifdef DC_S
	I(d ,g ) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QDOV) + (1 - d_gt_s_flag) * ddt(QSOV));
	I(s ,g ) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QSOV) + (1 - d_gt_s_flag) * ddt(QDOV));
`endif
`ifdef DC
	I(di,g ) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QDOV) + (1 - d_gt_s_flag) * ddt(QSOV));
	I(si,g ) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QSOV) + (1 - d_gt_s_flag) * ddt(QDOV));
`endif
`ifdef RF_S
	I(di,gi) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QDOV) + (1 - d_gt_s_flag) * ddt(QSOV));
	I(si,gi) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QSOV) + (1 - d_gt_s_flag) * ddt(QDOV));
`endif
`ifdef RF
	I(di,gi) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QDOV) + (1 - d_gt_s_flag) * ddt(QSOV));
	I(si,gi) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QSOV) + (1 - d_gt_s_flag) * ddt(QDOV));
`endif
`ifdef NQS 
	I(di,gi) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QDOV) + (1 - d_gt_s_flag) * ddt(QSOV));
	I(si,gi) <+  SIGN_M * 0.5 * ((d_gt_s_flag + 1) * ddt(QSOV) + (1 - d_gt_s_flag) * ddt(QDOV));
`endif
