`ifdef FUNCTIONS_INCLUDE
`else

`define QV(q,v) \
begin												\
	vv = v / NUV;										\
	if (vv > -0.6)										\
	begin											\
		z1 	= 0.25 * (vv - 1.4 + sqrt(vv * (vv - 0.394036) + 9.662671));		\
		z2 	= (vv - (2.0 * z1 + ln(z1))) / (2.0 * z1 + 1.0);			\
		q 	= z1 * (1.0 + z2 * (1.0 + 0.070 * z2)) * NUV;				\
	end											\
	else											\
	begin											\
		ln_z1_ 	= 0.5 * (vv - 0.201491 - sqrt(vv * (vv - 0.402982) + 2.446562));	\
		z1 	= exp(ln_z1_);								\
		z2 	= (vv - (2.0 * z1 + ln_z1_)) / (2.0 * z1 + 1.0);			\
		q 	= z1 * (1.0 + z2 * (1.0 + 0.483 * z2)) * NUV;				\
	end											\
end

`define NQ(nq,psi_p,sqrt_psi_p,qs,qd,dpd,gamma_b,gamma_g2) \
begin															\
	psi_sa_tmp 	= psi_p - qs - qd;										\
	sqrt_psi_sa 	= sqrt(`MAXA(psi_sa_tmp,1.0e-4,1.0E-2));							\
	if (TG < 0)													\
	begin														\
		z0 		= 1.0 + dpd + gamma_b / (sqrt_psi_p + sqrt_psi_sa);					\
		zk 		= 0.5 + dpd * sqrt_psi_sa / gamma_b;							\
		nq		= z0 / (zk + sqrt(zk * zk + z0 * (qs + qd) / gamma_g2));				\
	end														\
	else														\
		nq	 	= 1.0 + gamma_b / (sqrt_psi_p + sqrt_psi_sa);						\
end

`define QX(qx,psi_p,nq,qs,qd,powqs_qd2,powqsqd1_2) \
begin 																			\
	if (psi_p > 2.0)	qx = inv_dqmip1 * nq * `ONE3RD * (qs + qd + qs + 0.5 * (1.0 + 0.8 * qs + 1.2 * qd) * powqs_qd2 * powqsqd1_2);		\
	else 			qx = 0.0;														\
end

`define QG(qG,psi_p,qs,qd,powqs_qd2,powqsqd1_2,qsqd1,v_o,gamma_g2) \
begin 																							\
	if (psi_p > 2.0) 																				\
     	begin 																						\
		if (TG < 0) 																				\
		begin 																					\
      			v1_qg 	= v_o + 2.0 * qs * inv_dqmip1; 																\
      			v2_qg	= v_o + 2.0 * qd * inv_dqmip1; 																\
			k1 	= sqrt(0.25 + v1_qg / gamma_g2); 																\
			k2 	= sqrt(0.25 + v2_qg / gamma_g2); 																\
			k12 	= k1 + k2; 																		\
			k12_2 	= k12 * k12; 																		\
			k12_3 	= k12_2 * k12; 																		\
			qG	= (v1_qg / (1.0 + 2.0 * k1) + v2_qg / (1.0 + 2.0 * k2) + inv_dqmip1 * `ONE3RD * (powqs_qd2 / k12_3) * (0.8 * (k12_2 + k1 * k2) / qsqd1 + 2.0 / gamma_g2)); 	\
		end 																					\
		else 																					\
	        	qG 	= v_o + qs + qd + inv_dqmip1 * `ONE3RD * powqs_qd2 / qsqd1; 												\
    	end 																						\
     	else if (psi_p > 0.0) 																				\
			qG 	= (TG<0) ? v_o / (0.5 + sqrt(0.25 + v_o / gamma_g2)) : v_o; 												\
	else 																						\
			qG 	= (TG>0) ? v_o / (0.5 + sqrt(0.25 - v_o / gamma_g2)) : v_o; 												\
end 

`define FUNCTIONS_INCLUDE
`endif
