######################################################################
# Automatically generated by qmake (1.07a) Sat Jan 9 06:07:37 2010
######################################################################

TEMPLATE = lib
#CONFIG += debug
CONFIG -= qt
CONFIG += staticlib
CONFIG += release
DEFINES += NDEBUG
# TIME_NDEBUG
DEPENDPATH += superlu
INCLUDEPATH += . umfpack
TARGET = ../examples/hmor

#INCLUDEPATH += . umfpack /apps/MATLAB/R2014a/extern/include/

INCLUDEPATH += . umfpack

#unix:LIBS += -Wl,-rpath -Wl,/apps/MATLAB/R2014a/bin/glnxa64 -L/apps/MATLAB/R2014a/bin/glnxa64 -lmat -lmx -lumfpack -lamd -lblas -larpack  

unix:LIBS += -lumfpack -lamd -lblas -larpack


#unix:LIBS += ../lib/libumfpack.a ../lib/libamd.a /usr/lib/libarpack.a /usr/lib/libblas.a  /usr/lib/liblapack.a -lgfortran

#unix:LIBS += ../lib/libumfpack.a ../lib/libamd.a ../lib/arpack.a ../lib/libf2c.a ../lib/lapack.a ../lib/blas.a 

# Input
HEADERS += arch.h \
           arpackf.h \
           cap.h \
           ckt.h \
           comm.h \
           compressed_matrix.h \
           eigs.h \
           element.h \
           f2c.h \
           graph.h \
           linear_solver.h \
           node_list.h \
           orth_list.h \
           res.h \
           typeint.h \
           unit.h \
	   matrix_util.h \
	   dump_dot.h \
           subckt.h \
           subckt_ins.h \
           timer.h \
	   amor.h
SOURCES += cap.cpp \
	   linear_solver.cpp \
           ckt.cpp \
           eigs.cpp \
           element.cpp \
           node_list.cpp \
           res.cpp \
           unit.cpp \
 	   matrix_util.cpp \
	   dump_dot.cpp \
           subckt.cpp \
           timer.cpp \
           amor.cpp
