"""Imported legacy DSL kernel, namespaced under rtlgen_x."""

from rtlgen_x.dsl.legacy.codegen import EmitProfile, VerilogEmitter
from rtlgen_x.dsl.legacy.core import (
    Array,
    BehavioralModule,
    BehavioralRTLPair,
    BlackBoxModule,
    CacheInterface,
    HandshakeInterface,
    Input,
    Interface,
    LocalParam,
    Memory,
    Module,
    Output,
    Parameter,
    Reg,
    Signal,
    Vector,
    Wire,
    connect_interfaces,
)
from rtlgen_x.dsl.legacy.dsl_sim import DSLSimReport, DSLSimValidator, ModuleSimResult
from rtlgen_x.dsl.legacy.lib import (
    AsyncFIFO,
    BarrelShifter,
    CRC,
    Decoder,
    Divider,
    FSM,
    LFSR,
    PriorityEncoder,
    RoundRobinArbiter,
    SyncFIFO,
)
from rtlgen_x.dsl.legacy.lint import LintResult, VerilogLinter
from rtlgen_x.dsl.legacy.logic import (
    Cat,
    Const,
    Else,
    Elif,
    ForGen,
    Foreach,
    GenElse,
    GenIf,
    If,
    Mux,
    Otherwise,
    PadLeft,
    Rep,
    Split,
    StateTransition,
    Switch,
    When,
    comment,
)
from rtlgen_x.dsl.legacy.pipeline import Handshake, Pipeline, StageContext
from rtlgen_x.dsl.legacy.protocols import AHBLite, APB, AXI4, AXI4Lite, AXI4Stream, Bundle, Wishbone
from rtlgen_x.dsl.legacy.ram import SimpleDualPortRAM, SinglePortRAM
from rtlgen_x.dsl.legacy.sim import Simulator

__all__ = [
    "AHBLite",
    "APB",
    "AXI4",
    "AXI4Lite",
    "AXI4Stream",
    "Array",
    "AsyncFIFO",
    "BarrelShifter",
    "BehavioralModule",
    "BehavioralRTLPair",
    "BlackBoxModule",
    "Bundle",
    "CRC",
    "CacheInterface",
    "Cat",
    "Const",
    "DSLSimReport",
    "DSLSimValidator",
    "Decoder",
    "Divider",
    "Elif",
    "Else",
    "EmitProfile",
    "FSM",
    "ForGen",
    "Foreach",
    "GenElse",
    "GenIf",
    "Handshake",
    "HandshakeInterface",
    "If",
    "Input",
    "Interface",
    "LFSR",
    "LintResult",
    "LocalParam",
    "Memory",
    "Module",
    "ModuleSimResult",
    "Mux",
    "Otherwise",
    "Output",
    "PadLeft",
    "Parameter",
    "Pipeline",
    "PriorityEncoder",
    "Reg",
    "Rep",
    "RoundRobinArbiter",
    "Signal",
    "SimpleDualPortRAM",
    "Simulator",
    "SinglePortRAM",
    "Split",
    "StageContext",
    "StateTransition",
    "Switch",
    "SyncFIFO",
    "Vector",
    "VerilogEmitter",
    "VerilogLinter",
    "When",
    "Wire",
    "Wishbone",
    "comment",
    "connect_interfaces",
]
