"""L5 DSL module for the ThorTensorCore.

RTL-ready rtlgen description of the 8x8x8 INT8->INT32 MMA. Each output element
is generated by a per-element expression tree that sums the eight INT8*INT8
products and optionally adds the accumulator input.
"""

from __future__ import annotations
import os
import sys

_PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from rtlgen.core import Module, Input, Output, Wire, Const
from rtlgen import Cat, Mux
from rtlgen.logic import If
from rtlgen.codegen import ModuleDocTemplate, fill_doc_template


class ThorTensorCore(Module):
    """8x8x8 INT8->INT32 matrix-multiply-accumulate unit.

    result[i][j] = (acc_en ? C[i][j] : 0) + sum_k A[i][k]*B[k][j].
    1-cycle registered output (done asserted with valid result).
    """

    A_W = 512    # 8x8 INT8
    B_W = 512
    C_W = 2048   # 8x8 INT32

    def __init__(self):
        super().__init__("thor_tensor_core")

        self.clk = Input(1, "clk")
        self.rst_n = Input(1, "rst_n")

        self.a = Input(self.A_W, "a")
        self.b = Input(self.B_W, "b")
        self.c = Input(self.C_W, "c")
        self.acc_en = Input(1, "acc_en")
        self.start = Input(1, "start")

        self.result = Output(self.C_W, "result")
        self.done = Output(1, "done")

        # Build per-element expression trees.
        result_bits = []
        for i in range(8):
            for j in range(8):
                # Accumulator: C[i][j] (32-bit) gated by acc_en.
                c_base = i * 8 + j
                c_slice = self.c[c_base * 32 + 31:c_base * 32]
                acc = Mux(self.acc_en, c_slice, Const(0, 32))

                # Sum over k of A[i][k]*B[k][j], INT8 signed.
                # Each 16-bit product is sign-extended to 32 bits and added with
                # the framework's unsigned ``+``; the low 32 bits match signed sum.
                total = acc
                for k in range(8):
                    a_elem = self._int8_elem(self.a, i, k)
                    b_elem = self._int8_elem(self.b, k, j)
                    prod = self._int8_mul(a_elem, b_elem)
                    prod32 = _sign_extend_16to32(prod)
                    total = (total + prod32)[31:0]
                result_bits.append(total)

        # Cat() places the first operand in the most-significant position, so
        # reverse the list so element (i,j) lands at bits [(i*8+j)*32 +: 32]
        # (matching the L1 pack layout).
        comb_result = Cat(*reversed(result_bits))

        # Gate start through a Wire (framework seq() If() requirement).
        start_w = Wire(1, "start_w")
        with self.comb:
            start_w <<= self.start
            self.done <<= self.start

        with self.seq(self.clk, ~self.rst_n):
            with If(start_w):
                self.result <<= comb_result

        tpl = ModuleDocTemplate(
            source="thor_gpu/modules/tensor_core/layer_L5_dsl/src/dsl.py",
            description="8x8x8 INT8->INT32 MMA with optional accumulator input; 1-cycle registered.",
            author="RTLCraft Agent", version="0.1",
            timing="1 cycle latency; done coincident with start.",
        )
        fill_doc_template(tpl, self)

    # -- helpers ---------------------------------------------------------

    @staticmethod
    def _int8_elem(vec, row, col):
        """Extract the signed INT8 element [row][col] from a packed 512-bit matrix."""
        idx = row * 8 + col
        lo = idx * 8
        return vec[lo + 7:lo]

    @staticmethod
    def _int8_mul(a8, b8):
        """Signed 8x8->16 multiply, returned as a 16-bit unsigned pattern.

        Sign-extend each operand to 16 bits (two's complement), then multiply
        with the framework's unsigned ``*``: the low 16 bits of the product are
        identical to a signed multiply result.
        """
        a16 = _sign_extend_8to16(a8)
        b16 = _sign_extend_8to16(b8)
        return (a16 * b16)[15:0]


def _sign_extend_8to16(s):
    """Replicate the sign bit (bit 7) of an 8-bit signal to extend to 16 bits.

    rtlgen ``Cat`` places the first operand in the most-significant position,
    so the replicated sign bits come first (high), then the original 8 bits.
    """
    sign = s[7]
    return Cat(sign, sign, sign, sign, sign, sign, sign, sign, s)


def _sign_extend_16to32(s):
    """Replicate the sign bit (bit 15) of a 16-bit signal to extend to 32 bits."""
    sign = s[15]
    return Cat(sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, s)


def describe():
    from typing import Any, Dict
    return {
        "name": "ThorTensorCore",
        "layer": "L5_dsl",
        "status": "implemented",
        "description": "RTL-ready 8x8x8 INT8->INT32 MMA (1-cycle registered).",
        "dsl_class": "ThorTensorCore",
        "ports": "a[512], b[512], c[2048], acc_en, start -> result[2048], done",
    }


__all__ = ["ThorTensorCore", "describe"]
