"""Compiled simulator capability primitives."""

from rtlgen_x.sim.benchmark import (
    SimulatorBenchmarkReport,
    StreamingBenchmarkReport,
    benchmark_compiled_speedup,
    benchmark_streaming_capacity,
    build_stress_module,
    generate_stress_input_buffer,
    generate_stress_inputs,
    iter_stress_input_rows,
)
from rtlgen_x.sim.cosim import CosimMismatch, LegacyRtlCosimReport, run_legacy_rtl_cosim
from rtlgen_x.sim.cpp_backend import (
    Assignment,
    BinaryExpr,
    ConstExpr,
    CompiledSimulator,
    CppBuildError,
    CppBackendScaffold,
    MaskExpr,
    Memory,
    MemoryReadExpr,
    MemoryWrite,
    MuxExpr,
    Signal,
    SignalRef,
    SimModule,
    UnaryExpr,
    pack_u64_numpy_rows,
    pack_u64_numpy,
    pack_u64_words,
)
from rtlgen_x.sim.python_runtime import PythonSimulator

__all__ = [
    "Assignment",
    "BinaryExpr",
    "CompiledSimulator",
    "ConstExpr",
    "CppBuildError",
    "CppBackendScaffold",
    "MaskExpr",
    "Memory",
    "MemoryReadExpr",
    "MemoryWrite",
    "MuxExpr",
    "PythonSimulator",
    "Signal",
    "SignalRef",
    "SimulatorBenchmarkReport",
    "StreamingBenchmarkReport",
    "SimModule",
    "UnaryExpr",
    "pack_u64_numpy_rows",
    "pack_u64_numpy",
    "benchmark_compiled_speedup",
    "benchmark_streaming_capacity",
    "build_stress_module",
    "CosimMismatch",
    "generate_stress_input_buffer",
    "generate_stress_inputs",
    "iter_stress_input_rows",
    "LegacyRtlCosimReport",
    "pack_u64_words",
    "run_legacy_rtl_cosim",
]
