"""Compiled simulator capability primitives."""

from rtlgen_x.sim.benchmark import (
    SimulatorBenchmarkReport,
    StressSweepPoint,
    StressSweepReport,
    StreamingBenchmarkReport,
    benchmark_compiled_speedup,
    benchmark_streaming_capacity,
    build_stress_module,
    generate_stress_input_buffer,
    generate_stress_inputs,
    iter_stress_input_rows,
    run_stress_sweep,
    write_stress_sweep_report,
)
from rtlgen_x.sim.cosim import CosimMismatch, LegacyRtlCosimReport, run_legacy_rtl_cosim
from rtlgen_x.sim.cpp_backend import (
    Assignment,
    BinaryExpr,
    ConstExpr,
    CompiledSimulator,
    CppBuildError,
    CppBackendScaffold,
    MaskExpr,
    Memory,
    MemoryReadExpr,
    MemoryWrite,
    MuxExpr,
    Signal,
    SignalRef,
    SimModule,
    UnaryExpr,
    pack_u64_numpy_rows,
    pack_u64_numpy,
    pack_signal_values_u64_words,
    pack_u64_words,
    unpack_signal_values_u64_words,
)
from rtlgen_x.sim.python_runtime import PythonSimulator
from rtlgen_x.sim.compat import reset_simulator
from rtlgen_x.sim.fuzz import FuzzSuiteReport, FuzzTemplate, build_fuzz_templates, run_fuzz_suite
from rtlgen_x.sim.trace import (
    ExecutionTrace,
    RandomParityConfig,
    RandomParityHarnessReport,
    SimulatorParityReport,
    TraceMismatch,
    TraceStep,
    capture_execution_trace,
    compare_python_and_compiled,
    replay_execution_trace,
    run_random_parity_fuzz,
)

__all__ = [
    "Assignment",
    "BinaryExpr",
    "CompiledSimulator",
    "ConstExpr",
    "CppBuildError",
    "CppBackendScaffold",
    "ExecutionTrace",
    "FuzzSuiteReport",
    "FuzzTemplate",
    "MaskExpr",
    "Memory",
    "MemoryReadExpr",
    "MemoryWrite",
    "MuxExpr",
    "PythonSimulator",
    "RandomParityConfig",
    "RandomParityHarnessReport",
    "Signal",
    "SignalRef",
    "SimulatorParityReport",
    "SimulatorBenchmarkReport",
    "StressSweepPoint",
    "StressSweepReport",
    "StreamingBenchmarkReport",
    "SimModule",
    "TraceMismatch",
    "TraceStep",
    "UnaryExpr",
    "pack_u64_numpy_rows",
    "pack_u64_numpy",
    "pack_signal_values_u64_words",
    "benchmark_compiled_speedup",
    "benchmark_streaming_capacity",
    "build_stress_module",
    "build_fuzz_templates",
    "CosimMismatch",
    "generate_stress_input_buffer",
    "generate_stress_inputs",
    "iter_stress_input_rows",
    "run_stress_sweep",
    "write_stress_sweep_report",
    "LegacyRtlCosimReport",
    "pack_u64_words",
    "unpack_signal_values_u64_words",
    "capture_execution_trace",
    "compare_python_and_compiled",
    "replay_execution_trace",
    "run_fuzz_suite",
    "run_random_parity_fuzz",
    "run_legacy_rtl_cosim",
    "reset_simulator",
]
