"""
rtlgen.uvm_scoreboard — Golden trace bridge: sim.py → UVM scoreboard.

Produces SystemVerilog UVM scoreboard code that compares DUT outputs
against golden reference traces generated by rtlgen Simulator.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

from rtlgen.core import Module
from rtlgen.sim import Simulator


def generate_golden_trace(
    module: Module,
    stimuli: List[Dict[str, int]],
    output_signals: List[str],
    trace_name: str = "golden_trace",
) -> Tuple[str, List[str]]:
    """Run sim.py with given stimuli and return golden trace data + UVM code.

    Args:
        module: The DUT module
        stimuli: List of {signal_name: value} per cycle
        output_signals: List of signal names to capture per cycle
        trace_name: Name for the golden trace file

    Returns:
        (sv_code, golden_data_lines)
        sv_code: SystemVerilog code for UVM scoreboard
        golden_data_lines: List of "time value" strings per output signal per cycle
    """
    sim = Simulator(module)
    sim.reset("rst", cycles=2)

    golden_data: List[str] = []
    sv_lines: List[str] = []
    sv_lines.append(f"// Golden trace scoreboard: {trace_name}")
    sv_lines.append(f"// Generated by rtlgen.uvm_scoreboard")
    sv_lines.append("")
    sv_lines.append(f'`define GOLDEN_FILE "{trace_name}.dat"')
    sv_lines.append("")

    # Header
    headers = ["cycle"] + output_signals
    sv_lines.append(f"// Columns: {', '.join(headers)}")
    golden_data.append("# " + " ".join(headers))

    for cycle, stim in enumerate(stimuli):
        # Apply stimulus
        for sig, val in stim.items():
            sim.set(sig, val)
        sim.step()

        # Capture outputs
        values = [str(cycle)]
        for sig in output_signals:
            v = sim.get_int(sig)
            values.append(str(v))
        golden_data.append(" ".join(values))

    # Generate UVM scoreboard
    sv_lines.extend([
        f'import "uvm_pkg.sv"',
        "",
        f"class {trace_name}_scoreboard extends uvm_scoreboard;",
        f"    `uvm_component_utils({trace_name}_scoreboard)",
        "",
        f"    int golden[$];",
        f"    int cycle;",
        "",
        f"    function new(string name, uvm_component parent);",
        f"        super.new(name, parent);",
        f"    endfunction",
        "",
        f"    function void build_phase(uvm_phase phase);",
        f"        super.build_phase(phase);",
        f'        $readmemh(`GOLDEN_FILE, golden);',
        f"    endfunction",
        "",
        f"    function void check_outputs(",
        f"        input logic [31:0] cycle_num, ",
        "        " + ", ".join(f"input logic [31:0] {sig}" for sig in output_signals),
        f"    );",
        f"        int expected;",
        f"        int offset = cycle_num * ({len(output_signals)} + 1) + 1;",
        f"",
    ])
    for i, sig in enumerate(output_signals):
        sv_lines.append(
            f"        expected = golden[offset + {i}];"
        )
        sv_lines.append(
            f"        if ({sig} !== expected) begin"
        )
        sv_lines.append(
            f'            `uvm_error("{trace_name}", '
            f'$sformatf("Cycle %0d: {sig}=%0d, expected %0d", '
            f"cycle_num, {sig}, expected));"
        )
        sv_lines.append(f"        end")
    sv_lines.append(f"    endfunction")
    sv_lines.append(f"endclass")

    return "\n".join(sv_lines), golden_data


def generate_scoreboard_comparator(
    module: Module,
    outputs: List[str],
    class_name: str = "scoreboard",
) -> str:
    """Generate standalone UVM scoreboard comparing DUT vs reference model.

    Uses sim.py to compute expected outputs, emits SystemVerilog checker.
    """
    from rtlgen.codegen import VerilogEmitter

    # Emit DUT Verilog so UVM knows the port names
    dut_ports = []
    for name, sig in list(module._inputs.items()) + list(module._outputs.items()):
        dut_ports.append((name, sig.width, "input" if name in module._inputs else "output"))

    sv = []
    sv.append(f"// UVM Scoreboard for {module.name}")
    sv.append(f"// Auto-generated by rtlgen.uvm_scoreboard")
    sv.append("")
    sv.append(f"class {class_name} extends uvm_scoreboard;")
    sv.append(f"    `uvm_component_utils({class_name})")
    sv.append("")
    sv.append(f"    // Expected values (from rtlgen golden model)")
    sv.append(f"    int expected_q[$];")
    sv.append("")
    sv.append(f"    function new(string name, uvm_component parent);")
    sv.append(f"        super.new(name, parent);")
    sv.append(f"    endfunction")
    sv.append("")
    sv.append(f"    function void check_response(")
    sv.append(f"        int cycle, ")
    for name, w, _ in dut_ports:
        sv.append(f"        input logic [{w-1}:0] {name},")
    sv.append(f"    );")
    sv.append(f"        automatic int exp;")
    for name, w, _ in dut_ports:
        if name in outputs:
            sv.append(f"        exp = expected_q.pop_front();")
            sv.append(f"        if ({name} !== exp) begin")
            sv.append(f'            `uvm_error("{class_name}", $sformatf(')
            sv.append(f'                "Cycle %0d: {name}=%0d, expected %0d",')
            sv.append(f"                cycle, {name}, exp));")
            sv.append(f"        end")
    sv.append(f"    endfunction")
    sv.append(f"endclass")
    return "\n".join(sv)
