"""Supported DSL authoring surface for rtlgen_x.

The authored design object is a DSL ``Module``. ``LoweredDslModule`` is the
inspection wrapper around lowering output. Raw ``SimModule`` is intentionally a
lower-level executable object rather than the primary authoring surface.
"""

from rtlgen_x.dsl.adapter import (
    DslLoweringError,
    DslLoweringReport,
    LoweredDslModule,
    build_compiled_simulator_from_dsl,
    lower_dsl_module_to_sim,
)
from rtlgen_x.dsl.codegen import EmitProfile, VerilogEmitter
from rtlgen_x.dsl.core import (
    Array,
    BehavioralModule,
    BehavioralRTLPair,
    BlackBoxModule,
    CacheInterface,
    ClockDomainSpec,
    ConnectivitySite,
    HandshakeInterface,
    Input,
    Interface,
    LocalParam,
    MemoryAccess,
    Memory,
    Module,
    ModuleConnectivityReport,
    ModuleInstancePath,
    Output,
    Parameter,
    PortConnection,
    Reg,
    ResetDomainSpec,
    Signal,
    SignalDriver,
    StateWriter,
    Vector,
    Wire,
    connect_interfaces,
)
from rtlgen_x.dsl.lib import (
    APBRegisterBank,
    AXI4LiteRegisterBank,
    AsyncFIFO,
    BarrelShifter,
    CRC,
    Decoder,
    Divider,
    FSM,
    LFSR,
    PriorityEncoder,
    ReadyValidFIFO,
    ReadyValidRegister,
    ReqRspQueue,
    RoundRobinArbiter,
    SkidBuffer,
    SyncFIFO,
    WishboneRegisterBank,
)
from rtlgen_x.dsl.lint import LintResult, VerilogLinter
from rtlgen_x.dsl.logic import (
    Cat,
    Const,
    Else,
    Elif,
    ForGen,
    Foreach,
    GenElse,
    GenIf,
    If,
    Mux,
    Otherwise,
    PadLeft,
    Rep,
    SRA,
    Split,
    StateTransition,
    Switch,
    When,
    comment,
)
from rtlgen_x.dsl.pipeline import Handshake, Pipeline, StageContext
from rtlgen_x.dsl.protocols import AHBLite, APB, AXI4, AXI4Lite, AXI4Stream, Bundle, ReadyValid, ReqRsp, Wishbone
from rtlgen_x.dsl.ram import SimpleDualPortRAM, SinglePortRAM

__all__ = [
    "AHBLite",
    "APB",
    "APBRegisterBank",
    "AXI4",
    "AXI4Lite",
    "AXI4LiteRegisterBank",
    "AXI4Stream",
    "Array",
    "AsyncFIFO",
    "BarrelShifter",
    "BehavioralModule",
    "BehavioralRTLPair",
    "BlackBoxModule",
    "Bundle",
    "CRC",
    "CacheInterface",
    "Cat",
    "ClockDomainSpec",
    "ConnectivitySite",
    "Const",
    "Decoder",
    "Divider",
    "DslLoweringError",
    "DslLoweringReport",
    "Elif",
    "Else",
    "EmitProfile",
    "FSM",
    "ForGen",
    "Foreach",
    "GenElse",
    "GenIf",
    "Handshake",
    "HandshakeInterface",
    "If",
    "Input",
    "Interface",
    "LFSR",
    "LintResult",
    "LocalParam",
    "LoweredDslModule",
    "MemoryAccess",
    "Memory",
    "Module",
    "ModuleConnectivityReport",
    "ModuleInstancePath",
    "Mux",
    "Otherwise",
    "Output",
    "PadLeft",
    "Parameter",
    "Pipeline",
    "PortConnection",
    "PriorityEncoder",
    "ReadyValidFIFO",
    "ReadyValidRegister",
    "ReadyValid",
    "ReqRsp",
    "ReqRspQueue",
    "Reg",
    "ResetDomainSpec",
    "Rep",
    "SRA",
    "RoundRobinArbiter",
    "SkidBuffer",
    "Signal",
    "SignalDriver",
    "SimpleDualPortRAM",
    "SinglePortRAM",
    "Split",
    "StageContext",
    "StateWriter",
    "StateTransition",
    "Switch",
    "SyncFIFO",
    "Vector",
    "VerilogEmitter",
    "VerilogLinter",
    "When",
    "Wire",
    "Wishbone",
    "WishboneRegisterBank",
    "build_compiled_simulator_from_dsl",
    "comment",
    "connect_interfaces",
    "lower_dsl_module_to_sim",
]
