"""Generic lightweight architecture simulation primitives."""

from rtlgen_x.archsim.behavior import BehaviorReport, BehaviorSimulator
from rtlgen_x.archsim.cycle import CycleReport, CycleSimulator
from rtlgen_x.archsim.explore import (
    StageSweepReport,
    SweepPoint,
    UpgradeCandidate,
    rank_bandwidth_upgrades,
    rank_capacity_upgrades,
    rank_initiation_interval_upgrades,
    rank_latency_upgrades,
    rank_queue_depth_upgrades,
    run_stage_bandwidth_sweep,
    run_stage_capacity_sweep,
    run_stage_initiation_interval_sweep,
    run_stage_latency_sweep,
    run_stage_queue_depth_sweep,
)
from rtlgen_x.archsim.model import ArchitectureModel, FlowSpec, StageSpec, Workload
from rtlgen_x.archsim.presets import (
    ArchitectureScenario,
    build_all_advanced_scenarios,
    build_all_reference_scenarios,
    build_cache_hierarchy_scenario,
    build_dma_copy_scenario,
    build_controller_scenario,
    build_cpu_in_order_scenario,
    build_gpu_throughput_scenario,
    build_gpu_warp_cluster_scenario,
    build_npu_dataflow_scenario,
    build_npu_systolic_scenario,
    build_streaming_datapath_scenario,
)
from rtlgen_x.archsim.primitives import (
    cache_hierarchy,
    compose_stage_groups,
    compute_stage,
    controller_stage,
    dataflow_array,
    datapath_stage,
    dma_engine,
    interconnect_stage,
    linear_model,
    memory_stage,
    queue_stage,
    warp_cluster,
)

__all__ = [
    "ArchitectureModel",
    "ArchitectureScenario",
    "BehaviorReport",
    "BehaviorSimulator",
    "CycleReport",
    "CycleSimulator",
    "FlowSpec",
    "StageSweepReport",
    "StageSpec",
    "SweepPoint",
    "UpgradeCandidate",
    "Workload",
    "build_all_advanced_scenarios",
    "build_all_reference_scenarios",
    "build_cache_hierarchy_scenario",
    "build_dma_copy_scenario",
    "build_controller_scenario",
    "build_cpu_in_order_scenario",
    "build_gpu_throughput_scenario",
    "build_gpu_warp_cluster_scenario",
    "build_npu_dataflow_scenario",
    "build_npu_systolic_scenario",
    "build_streaming_datapath_scenario",
    "cache_hierarchy",
    "compose_stage_groups",
    "compute_stage",
    "controller_stage",
    "dataflow_array",
    "datapath_stage",
    "dma_engine",
    "interconnect_stage",
    "linear_model",
    "memory_stage",
    "queue_stage",
    "rank_bandwidth_upgrades",
    "rank_capacity_upgrades",
    "rank_initiation_interval_upgrades",
    "rank_latency_upgrades",
    "rank_queue_depth_upgrades",
    "run_stage_bandwidth_sweep",
    "run_stage_capacity_sweep",
    "run_stage_initiation_interval_sweep",
    "run_stage_latency_sweep",
    "run_stage_queue_depth_sweep",
    "warp_cluster",
]
