// Calibre DRC Rule Deck
// Design: FullSystem
// Auto-generated by IC Backend MVP

PRECISION 1000
LAYOUT PATH "out/FullSystem.gds"
LAYOUT PRIMARY FullSystem
DRC RESULTS DATABASE drc_results.db
DRC MAXIMUM RESULTS ALL
DRC MAXIMUM VERTEX 4096
DRC CELL NAME YES
DRC SUMMARY REPORT drc_summary.rpt

// Include PDK DRC rules
INCLUDE "/share/home/yangfan/backend_scripts/backend/tf/tsmcn28_10lm7X2ZUTRDL_HVH.tf"
