"""High-level unstructured-mesh simulator (FVM backend)."""

from __future__ import annotations
from typing import Dict, Optional
import numpy as np

from tcad.mesh.base import Mesh
from tcad.solver.unstructured_fvm import UnstructuredFVM


class UnstructuredSimulator:
    """
    Device simulator on unstructured tetrahedral meshes using the
    finite-volume-method backend.

    This class provides a similar API to :class:`tcad.simulator.Simulator`
    but works with body-fitted unstructured meshes generated by Gmsh or
    other external meshers.

    Parameters
    ----------
    mesh : Mesh
        Unstructured mesh with tetrahedral elements and node-centered
        material fields (``epsilon``, ``doping``, ``mu_n``, ``mu_p``).
    """

    def __init__(self, mesh: Mesh):
        if not isinstance(mesh, Mesh):
            raise TypeError("UnstructuredSimulator requires a Mesh instance")
        self.mesh = mesh
        self._fvm = UnstructuredFVM(mesh)
        self.results: Optional[Dict[str, np.ndarray]] = None

    def set_material_from_mesh(self):
        """Pull material properties from mesh fields into the solver."""
        n = self.mesh.num_nodes()
        fields = self.mesh.fields

        if "epsilon" in fields:
            self._fvm.set_permittivity(fields["epsilon"])
        if "doping" in fields:
            self._fvm.set_doping(fields["doping"])
        if "mu_n" in fields and "mu_p" in fields:
            self._fvm.set_mobility(fields["mu_n"], fields["mu_p"])

    def set_contact(self, name: str, voltage: float, workfunction: float = 4.0):
        """
        Set a contact to Dirichlet potential.

        The mesh must contain a field named ``contact_<name>`` with
        non-zero values indicating contact nodes.
        """
        field_name = f"contact_{name}"
        if field_name not in self.mesh.fields:
            available = [k for k in self.mesh.fields.keys() if k.startswith("contact_")]
            raise KeyError(f"Contact '{name}' not found. Available: {available}")

        mask = self.mesh.fields[field_name] > 0.5
        indices = np.where(mask)[0]

        # Build-in potential offset for semiconductor contacts
        # For simplicity, use flat-band approximation: phi_eq = VT * asinh(Nd/2ni)
        # Here we just apply the contact voltage directly.
        for idx in indices:
            self._fvm.dirichlet[int(idx)] = float(voltage)

    def run(self) -> Dict[str, np.ndarray]:
        """
        Execute a Poisson solve on the unstructured mesh.

        Returns
        -------
        dict with keys ``phi``, ``Ex``, ``Ey``, ``Ez``, ``converged``.
        """
        phi = self._fvm.solve_poisson()
        Ex, Ey, Ez = self._fvm.compute_electric_field(phi)

        self.results = {
            "phi": phi,
            "Ex": Ex,
            "Ey": Ey,
            "Ez": Ez,
            "converged": True,
            "iterations": 1,
        }
        return self.results

    def to_mesh_fields(self) -> Dict[str, np.ndarray]:
        """Copy latest simulation results into mesh fields."""
        if self.results is None:
            raise RuntimeError("No results. Call run() first.")
        return {
            k: self.results[k]
            for k in ["phi", "Ex", "Ey", "Ez"]
            if k in self.results
        }

    def save(self, filename: str):
        """Export mesh with results to file via meshio."""
        fields = self.to_mesh_fields()
        for name, data in fields.items():
            self.mesh.add_field(name, data)
        self.mesh.save(filename)
