#include "CCodeGeneration.h"
#include "vaParser.h"
#include <stdio.h>
#include <string>
#include <list>
#include <set>
#include <vector>
#include <fstream>
#include <iostream>
#include <algorithm>
using namespace std;
extern module* gModule;

void ModelCardGeneratorH(module* mod, const string &filename)
{
  char fn[1000];
  sprintf(fn, "%s.h", filename.c_str());
  ofstream ofs(fn);
  if(!ofs){
    cerr<<"File: "<<filename<<" cannot open for read.\n";
    exit(-1);
  }
  string className = mod->_name + "Model";
  int count;

  ofs<<"#ifndef verilog_ams_src_"<<filename<<"_H_\n";
  ofs<<"#define verilog_ams_src_"<<filename<<"_H_\n";
  ofs<<"/////////////////////////////////////////////////////////////////////////////////////////////////////\n";
  ofs<<"/// Generated by VA-C-Generator. DO NOT EDIT!\n";
  ofs<<"/// @author vaParser\n";
  ofs<<"/////////////////////////////////////////////////////////////////////////////////////////////////////\n\n";
  ofs<<"#include \"ahdl/AhdlModel.h\"\n"<<endl;

  ofs<<"class "<<className<<" : public AhdlModel\n";
  ofs<<"{\npublic:\n";

  /// output Net
  ofs<<"    struct Net\n    {\n";
  ofs<<"        enum Name\n        {\n";
  ofs<<"            ";
  vector<net>::iterator netiter = mod->_net.begin();
  count = 0;
  while(netiter != mod->_net.end()){
    if(count != 0)ofs<<", ";
    ofs<<netiter->_name<<" = "<<count;
    ++count;
    ++netiter;
  }
  ofs<<endl;
  ofs<<"        };\n    };\n\n"; ///Endof output Net;

  /// output parameter
  ofs<<"    struct Elem\n    {\n";
  ofs<<"        enum Name\n        {\n";
  ofs<<"            ";
  list<parameter>::iterator pariter = mod->_param.begin();
  count = 0;
  while(pariter != mod->_param.end()){
    if(count != 0) ofs<<", ";
    ofs<<pariter->_name<<" = "<<count;
    ++count;
    ++pariter;
  }
  ofs<<endl;
  ofs<<"        };\n    };\n"; ///End of output parameter

  ofs<<"\n\n";
  ofs<<"    "<<className<<"();\n";
  ofs<<"\n";
  ofs<<"};\n\n";
  ofs<<"#endif\n";

  ofs.close();
  ofs.clear();
}


void ModelCardGeneratorC(module* mod, const string &filename)
{
  char fn[1000];
  sprintf(fn, "%s.cc", filename.c_str());
  ofstream ofs(fn);
  if(!ofs){
    cerr<<"File: "<<filename<<" cannot open for read.\n";
    exit(-1);
  }

  /// Nothing to output

  ofs.close();
  ofs.clear();

}

void OutputSyntax(module* mod)
{
  char oputfname[1024];
  map<string, bitset<BIT_> >::iterator it;
  map<string, int>::iterator pit;
  list<statement>::iterator iter = mod->_main._steps.end();
  while(iter != mod->_main._steps.end()){
    cout<<iter->_describ<<endl;
    cout<<"    //";
    it = iter->_var.begin();
    while(it != iter->_var.end()){
      cout<<it->first<<"  "<<it->second<<"\t";
      ++it;
    }
    pit = iter->_param.begin();
    while(pit != iter->_param.end()){
      cout<<pit->first<<"\t";
      ++pit;
    }
    cout<<endl;
    ++iter;
  }

  ofstream ofs("model.syntax");

  /// parameter output.
  list<parameter>::iterator paramit;
  paramit = mod->_param.begin();
  string eleparam;
  string modparam;
  string port;
  string net;
  string ddtval, ddtexp, ddtans;
  while(paramit != mod->_param.end()){
    if(paramit->_type == 1) eleparam += " " + paramit->_name + "=" + double2string(paramit->_defvalue);
    else modparam += " " + paramit->_name + "=" + double2string(paramit->_defvalue);
    ++paramit;
  }
  /// port output
  for(int i=0; i<mod->_port.size(); ++i){
    port += " " + mod->_port[i]._name;
  }
  /// net output
  for(int i=0; i<mod->_net.size(); ++i){
    net += " " + mod->_net[i]._name;
  }
  for(int i=0; i<mod->_ddtnum; ++i){
    ddtval += " DdtVal" + int2string(i);
  }
  ofs<<mod->_name<<endl<<"begin\n";
  transform(eleparam.begin(), eleparam.end(), eleparam.begin(), ::tolower);
  transform(modparam.begin(), modparam.end(), modparam.begin(), ::tolower);
  ofs<<"@element@"<<eleparam<<";\n";
  ofs<<"@port@"<<port<<";\n";
  ofs<<"@net@"<<net<<";\n";
  ofs<<"@model@"<<modparam<<";\n";
  ofs<<"@state@"<<ddtval<<";\n";
  ofs<<"end\n";
  ofs.close();
  ofs.clear();
}


void OutputH(module* mod, const char *ofname)
{
  char oputfname[1024];
  sprintf(oputfname, "%sEquation.h", ofname);
  ofstream ofs(oputfname);
  map<string, int>::iterator dervit;
  ofs<<"#ifndef src_devices_"<<ofname<<"_Equation_h\n";
  ofs<<"#define src_devices_"<<ofname<<"_Equation_h\n";
  ofs<<endl;
  ofs<<"#include \"AhdlDeviceEvaluator.h\"\n";

  string className = "Ahdl" + mod->_name + "DeviceEvaluator";

  ofs<<"class "<<className<<" : public AhdlDeviceEvaluator\n";
  ofs<<"{\npublic\n";
  ofs<<"    virtual void ProvideSparseStructure();\n";
  ofs<<"    virtual void InitializeSubMatrixPointer();\n";
  ofs<<"\n";
  ofs<<"    virtual void ProvideTimeDomainRhs();\n";
  ofs<<"    virtual void ProvideTimeDomainJacobi();\n\n";

  ofs<<"private:\n";

  int size = mod->_net.size();
  ofs<<"    int matPosition_["<<size<<"]["<<size<<"];\n"<<endl;

  ofs<<"};\n\n";
  ofs<<"#endif\n";
  ofs.close();
  ofs.clear();
}


void OutputC(module* mod, const char *ofname)
{
  char oputfname[1024];
  sprintf(oputfname, "%sEquation.cc", ofname);
  ofstream ofs(oputfname);
  string className = "Ahdl" + mod->_name + "DeviceEvaluator";

  ofs<<"#include \"AhdlResDeviceEvaluator.h\""<<endl;
  ofs<<"#include \"ahdl/ResModel.h\""<<endl<<endl;

  ofs<<"typedef ResModel::Net Net;\n";
  ofs<<"typedef ResModel::Elem Elem;\n\n";

  //// output ProvideSparseStructure
  ofs<<"void "<<
     className<<"::ProvideSparseStructure()\n";
  ofs<<"{\n";
  ofs<<"    int netnum["<<mod->_net.size()<<"];\n";
  for(int i=0; i<mod->_net.size(); ++i){
    ofs<<"    netnum["<<i<<"] = variableIndex_[Net::"
      <<mod->_net[i]._name<<"];"<<endl;
  }
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"    equation_->AllocateMatrixElement(netnum["
          <<i<<"], netnum["<<j<<"]);\n";
    }
  }
  ofs<<"    for(int i = 0; i < "<<mod->_net.size()<<"; ++i) {\n";
  ofs<<"        equation_->AllocateRhs(variableIndex_[i]);\n";
  ofs<<"    }\n";
  ofs<<"}\n\n"; //end of ProvideSparseStructure

  /// output InitializeSubMatrixPointer
  ofs<<"void "<<
    className<<"::InitializeSubMatrixPointer()\n";
  ofs<<"{\n";
  ofs<<"    int netnum["<<mod->_net.size()<<"];\n";
  for(int i=0; i<mod->_net.size(); ++i){
    ofs<<"    netnum["<<i<<"] = variableIndex_[Net::"
      <<mod->_net[i]._name<<"];"<<endl;
  }
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"    matPosition_["<<i<<"]["<<j<<"] = "
          <<"equation->GetMatrixElementPosition"
          <<"(netnum["<<i<<"], netnum["<<j<<"]);\n";
    }
  }
  ofs<<endl;
  ofs<<"    for(int i = 0; i < "<<mod->_net.size()<<"; ++i) {\n";
  ofs<<"        rhsPosition_[i] = equation_->GetRhsPosition(variableIndex_[i]);\n";
  ofs<<"    }\n";
  ofs<<"}\n\n";  /// end of InitializeSubMatrixPointer

  /// output TimeDomainEquation
  ofs<<"void "<<
    className<<"::ProvideTimeDomainEquation()\n";
  ofs<<"{\n";
  ofs<<EquationGenerator(mod);
  ofs<<"}\n\n";/// end of Equation

  /// output TimeDomainJacobi
  ofs<<"void "<<
    className<<"::ProvideTimeDomainJacobi()\n";
  ofs<<"{\n";
  ofs<<JacobiGenerator(mod);
  ofs<<"}\n\n";/// end of Jacobi

  ofs.close();
  ofs.clear();
}

string EquationGenerator(module *mod)
{
  string equStr;
  string ddtexp, ddtans;
  string stri;

  /// Begin Variable define
  for(int i=0; i<mod->_ddtnum; ++i){
    ddtexp += ", DdtExp" + int2string(i);
    ddtans += ", DdtAns" + int2string(i);
  }
  equStr += "    double" + ddtexp.substr(1) + ";\n";
  equStr += "    double" + ddtans.substr(1) + ";\n";
  equStr += "    int netnum[" + int2string(mod->_net.size()) + "];\n";
  for(int i=0; i<mod->_net.size(); ++i){
    stri = int2string(i);
    equStr += "    netnum["+ stri +
      "] = variableIndex_[Net::" + mod->_net[i]._name + "];\n";
  }
  for(int i=0; i<mod->_net.size(); ++i){
    stri = int2string(i);
    equStr += "    double _rhsN" + stri + " = 0;\n";
  }
  map<string, int>::iterator dervit = mod->_dervar.begin();
  while(dervit != mod->_dervar.end()){
    equStr += "    double "
      + dervit->first.substr(1, (dervit->first).find("Dv")-1)
      + " = equation->GetAnalogValue(netnum["
      + int2string(dervit->second) + "]);\n";
    ++dervit;
  } // End of variable define

  /// begin calculate
  string destmp;
  int flownode;
  source *mysource;
  list<statement>::iterator iter = mod->_main._steps.begin();
  list<source*>::iterator sourceiter;
  sourceiter = mod->_contribute.begin();
  while(iter != mod->_main._steps.end()){
    if(iter->_mode == 4 || iter->_mode == 5) {
      ++iter; continue;
    } else if(iter->_mode == 2){
      destmp = ReplaceModelParam(*iter);
      mysource = *sourceiter;
      ++sourceiter;
      if(mysource->_type == 1){
        if(mysource->_nodenum == 1){
          equStr += "    _rhsN" + int2string(mysource->_pos) + " += -(" + destmp + ");\n";
        } else if(mysource->_nodenum == 2){
          equStr += "    _rhsN" + int2string(mysource->_pos) + " += -(" + destmp + ");\n";
          equStr += "    _rhsN" + int2string(mysource->_neg) + " += (" + destmp + ");\n";
        } else {
          cerr<<"Too many nodes in source."<<endl;
          exit(-1);
        }
      } else if (mysource->_type == 2){
        if(mysource->_nodenum == 1){
          cerr<<"V(node) not impl yet.\n";
          exit(-1);
        } else if (mysource->_nodenum == 2){
          flownode = GetFlowNode(mysource->_pos, mysource->_neg);
          equStr += "    _rhsN" + int2string(flownode) + " += " + destmp +";\n";
        } else {
          cerr<<"Too many nodes in source."<<endl;
          exit(-1);
        }
      }
    } else {
      equStr += "    " + ReplaceModelParam(*iter) + "\n";
    }
    ++iter;
  }
  /// stamp RHS
  for(int i=0; i<mod->_net.size(); ++i){
    equStr += "    equation->AddtoCachedRhs(netnum[" + int2string(i)
      + "], rhsPosition_[Net::" + mod->_net[i]._name
      + "], _rhsN" + int2string(i) + ", 1);\n";
  }
  return equStr;
}

string JacobiGenerator(module *mod)
{
  string jacStr;
  string ddtexp, ddtans;
  string stri;

  /// begin variables declaration
  jacStr += "    double _der0 = equation_->DdtConduct();\n";
    for(int i=0; i<mod->_ddtnum; ++i){
    ddtexp += ", DdtExp" + int2string(i);
    ddtans += ", DdtAns" + int2string(i);
  }
  jacStr += "    double" + ddtexp.substr(1) + ";\n";
  jacStr += "    double" + ddtans.substr(1) + ";\n";
  jacStr += "    int netnum[" + int2string(mod->_net.size()) + "];\n";

  map<string, int>::iterator dervit = mod->_dervar.begin();
  while(dervit != mod->_dervar.end()){
    jacStr += "    double "
      + dervit->first.substr(1, (dervit->first).find("Dv")-1)
      + " = equation->GetAnalogValue(netnum["
      + int2string(dervit->second) + "]);\n";
    jacStr += "    double " + dervit->first + " = 1;\n";
    ++dervit;
  }
  for(int i=0; i<mod->_net.size(); ++i){
    stri = int2string(i);
    jacStr += "    netnum["+ stri +
      "] = variableIndex_[Net::" + mod->_net[i]._name + "];\n";
  }

  map<string, int>::iterator tmpvariter = mod->_tmpdervar.begin();
  int count = 0;
  while(tmpvariter != mod->_tmpdervar.end()){
    if(count%5 == 0){
      if(count > 1) jacStr += ";\n";
      jacStr += "    double " + tmpvariter->first;
    }
    else jacStr += ", " + tmpvariter->first;
    ++tmpvariter;
    ++count;
  }
  if(count) jacStr += ";\n";
  jacStr += "    double contributetmp";
  for(int i=0; i<gModule->_net.size(); ++i){
    if(i%4 == 0) jacStr += ";\n    double dcontributetmpDv" + int2string(i);
    else jacStr += ", dcontributetmpDv" + int2string(i);
  }
  jacStr += ";\n\n";

  // begin current calculate and derivation calculate
  string mainstr;
  statement mystat;
  set<string> dertmpvar;
  bitset<BIT_> tmpbit;
  map<string, bitset<BIT_> >::iterator viter;
  string destmp;
  source *mysource;
  list<statement>::iterator iter = mod->_main._steps.begin();
  list<source*>::iterator sourceiter;
  sourceiter = mod->_contribute.begin();
  while(iter != mod->_main._steps.end()){
    if(iter->_mode == 4) {
      mainstr += "            " + iter->_describ + "\n";
    } else if(iter->_mode == 2){
      mysource = *sourceiter;
      ++sourceiter;
      tmpbit = 0;
      viter = iter->_var.begin();
      while(viter != iter->_var.end()){
        tmpbit |= viter->second;
        ++viter;
      }
      destmp = "            contributetmp = " + iter->_describ + ";\n";
      destmp += "//Derivate " + int2string(tmpbit.to_ulong());
      mystat = *iter;
      mystat._describ = "            contributetmp = " + iter->_describ + ";";
      if(tmpbit != 0){
        destmp = calculate_deriv(mystat, dertmpvar);
        destmp = ReplaceModelParam(destmp, mystat._param);
      } else {
        destmp = ReplaceModelParam(destmp, mystat._param);
      }
      // Derivate of contributetmp`
      mainstr += destmp + "\n";
      if(mysource->_type == 1){
        if(mysource->_nodenum == 2){
          for(int i=0; i<mod->_net.size(); ++i){
            if(tmpbit[i] != 0){
              mainstr += "            _matValueN" + int2string(mysource->_pos) + "N" + 
                int2string(i) + " += dcontributetmpDv" + int2string(i) + ";\n";
              mainstr += "            _matValueN" + int2string(mysource->_neg) + "N" + 
                int2string(i) + " += -dcontributetmpDv" + int2string(i) + ";\n";
            }
          }
        } else if(mysource->_nodenum == 1){
          for(int i=0; i<mod->_net.size(); ++i){
            if(tmpbit[i] != 0){
              mainstr += "            _matValueN" + int2string(mysource->_pos) + "N"
                + int2string(i) + " += dcontributetmpDv" + int2string(i) + ";\n";
            }
          }
        }
      } else if (mysource->_type == 2){
        if(mysource->_nodenum == 1){
          cerr<<"V(node) not impl yet.\n";
          exit(-1);
        } else if (mysource->_nodenum == 2){

        } else {
          cerr<<"Too many nodes in source."<<endl;
          exit(-1);
        }
      }
    } else if(iter->_mode == 0){
      if(iter->_type == true)
      {
        destmp = calculate_deriv(*iter, dertmpvar);
        destmp = ReplaceModelParam(destmp, iter->_param);
        mainstr += destmp + "\n";
      } else {
        mainstr += ReplaceModelParam(*iter) + "\n";
      }
    }
    ++iter;
  }

  /// stamp matrix
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1){
        jacStr += "    double _matValueN" + int2string(i) + "N" + int2string(j) + " = 0;\n";
      }
    }
  }
  jacStr += mainstr;
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1){
        jacStr += "    equation->SetCachedMatrix(matEleN" + int2string(i) + "N" +
          int2string(j) + " , _matValueN" + int2string(i) + "N" + int2string(j) + ");\n";
      }
    }
  }

  return jacStr;
}
