#ifndef INC_DERIVATION_H_
#define INC_DERIVATION_H_

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#define BIT_ 32

#include <string>
#include <bitset>
#include <map>
#include <set>
#include <vector>
using std::map;
using std::string;
using std::bitset;
using std::set;
using std::vector;

struct statement{
    string _describ;
    map<string, bitset<BIT_> > _var;
    map<string, int> _param;
    bool _type;  ///  false neednot to derivate.
                 ///  true  need to derivate.
    int  _level; ///  0     main loop
                 ///  1     sublevel loop. EX. if(){sublevel}else{sublevel}
                 ///  2     ...
    int _mode;   ///  1:    system function 2:contribution 0:mornal
};

extern map<string, bitset<BIT_> > __varmap;

/// This Function will check The Variable var is depend on Voltage index with ind.
/// The 3th parameter takes the full variable dependence infomation.
bool VarCheckDependence(const char* var, int ind);

/// This Function willing to do the mathmatic funcions such as: sin cos tan log10 log ...
/// derivation automaticly.
/// The math function derivation format descriped in source file.
/// The memory used in string returned by this function is malloced by function
/// Users should free it when needn't to use it.
char* GetDerivFunction(const char *funname, const char* self, const char* deriv, int expnum);


/// This Function will calculate the derivation of operater +|-
char* DerivationOfOperatorAM();

/// This Function will calculate the derivation of operater *|/
char* DerivationOfOperatorMD();

// This function willing to return the answer of 'first' and 'second' with operator operatorType.
char* GetExprAns(const char operatorType, const char* first, const char* second);

/// This function for report errors like printf format.
void derivError(const char* fmt, ...);

/// If the expression is atomic, return true, else false.
bool CheckAtomic(const char* expr);

// Check the Vaule of the string. use symbolic way
int GetType(const char* str);

vector<string>  ReplaceDdtDeriv(string&);

// Main Function for calculate the difference of a expression.
string calculate_deriv_replace(const statement& inputState, set<string>& optTmpVariable, vector<vector<string> >& dddts);
string calculate_deriv(const statement& inputState, set<string>& optTmpVariable);

/// auto generated by Bison/Yacc. in derYacc.cpp
extern int derivparse();
#endif
