#include "vaParser.h"
#include "xyce_vcomp.h"
#include <stdio.h>
#include <string>
#include <list>
#include <set>
#include <vector>
#include <fstream>
#include <iostream>
#include <algorithm>
#include<iomanip>

using namespace std;
extern module* gModule;

void GenerateHeader(module* mod, const string &filename)
{
  char fn[1000];
  sprintf(fn, "%s.h", filename.c_str());
  ofstream ofs(fn);
  if(!ofs){
    cerr<<"File: "<<filename<<" cannot open for read.\n";
    exit(-1);
  }

  ofs << "#ifndef verilog_ams_src_"<<filename<<"_H_\n";
  ofs << "#define verilog_ams_src_"<<filename<<"_H_\n";
  ofs << "/////////////////////////////////////////////////////////////////////////////////////////////////////\n";
  ofs << "/// Generated by VA-C-Generator. DO NOT EDIT!\n";
  ofs << "/// @author vaParser\n";
  ofs << "/////////////////////////////////////////////////////////////////////////////////////////////////////\n\n";

  ofs << "// ----------   Standard Includes   ----------" << endl;
  ofs << "#include <N_DEV_Configuration.h>\n";
  ofs << "#include <map>\n";
  ofs << "#include <N_DEV_DeviceMaster.h>\n";
  ofs << "#include <N_DEV_DeviceInstance.h>\n";
  ofs << "#include <N_DEV_DeviceModel.h>\n";
  ofs << "#include <N_DEV_DeviceBlock.h>\n";
  ofs << "namespace Xyce {\n";
  ofs << "namespace Device {\n";
  ofs << "namespace ADMS_Device {\n";
  ofs << "class Model;\n";
  ofs << "class Instance;\n\n";
  ofs << "struct Traits : public DeviceTraits<Model, Instance>\n";
  ofs << "{\n";
  ofs << "static const char *name() {return  \"AHDL Model\";}\n";
  ofs << "static const char *deviceTypeName() {return \"AHDL level 1\";}\n";
  ofs << "static int numNodes() {return " << mod->_port.size() << ";}\n";
  ofs << "static bool modelRequired() {return false;}\n";
  ofs << "static bool isLinearDevice() {return false;}\n";
  ofs << "\n";
  ofs << "static Device *factory(const Configuration &configuration, const FactoryBlock &factory_block);\n";
  ofs << "static void loadModelParameters(ParametricData<Model> &model_parameters);\n";
  ofs << "static void loadInstanceParameters(ParametricData<Instance> &instance_parameters);\n";
  ofs << "};\n\n";

  ofs << "class Instance : public DeviceInstance\n";
  ofs << "{\n";
  ofs << "friend class SizeDependParam;\n";
  ofs << "friend class ParametricData<Instance>;\n";
  ofs << "friend class Model;\n";
  ofs << "friend class Traits;friend class Master;\n";
  ofs << "\n";
  ofs << "// functions\n";
  ofs << "public:\n\n";
  ofs << "Instance(\n";
  ofs << "const Configuration &       configuration,\n";
  ofs << "const InstanceBlock &     IB,\n";
  ofs << "Model &                   Miter,\n";
  ofs << "const FactoryBlock &      factory_block);\n";
  ofs << "\n";
  ofs << "~Instance();\n";
  ofs << "\n";
  ofs << "private:\n";
  ofs << "Instance(const Instance &);\n";
  ofs << "Instance &operator=(const Instance &);\n";
  ofs << "\n";
  ofs << "public:\n";
  ofs << "void registerLIDs( const std::vector<int> & intLIDVecRef,\n";
  ofs << "const std::vector<int> & extLIDVecRef );\n";
  ofs << "void registerStateLIDs( const std::vector<int> & staLIDVecRef);\n";
  ofs << "void registerStoreLIDs( const std::vector<int> & stoLIDVecRef);\n";
  ofs << "virtual void registerBranchDataLIDs(const std::vector<int> & branchLIDVecRef);\n";
  ofs << "void loadNodeSymbols(Util::SymbolTable &symbol_table) const; // override\n";
  ofs << "const std::vector< std::vector<int> > & jacobianStamp() const;\n";
  ofs << "void registerJacLIDs( const std::vector< std::vector<int> > & jacLIDVec );\n";
  ofs << "bool processParams ();\n";

  ofs << "bool updateTemperature(const double & temp_tmp);\n";
  ofs << "bool updateIntermediateVars_RHS();\n";
  ofs << "bool updateIntermediateVars_Jac();\n";
  ofs << "bool updateIntermediateVars ();\n";
  ofs << "bool updatePrimaryState ();\n";
  ofs << "bool loadDAEQVector ();\n";
  ofs << "bool loadDAEFVector ();\n";
  ofs << "bool auxChargeCalculations ();\n";
  ofs << "bool setupCapacitors_newDAE ();\n";

  ofs << "bool setupCapacitors_oldDAE ();\n";

  ofs << "bool loadDAEdQdx ();\n";
  ofs << "bool loadDAEdFdx ();\n";
  ofs << "void setupPointers ();\n";
  ofs << "public:\n";
  ofs << "// Getters and setters\n";
  ofs << "Model &getModel() \n";
  ofs << "{\n";
  ofs << "return model_;\n";
  ofs << "}\n";
  ofs << "\n";
  ofs << "private:\n";
  ofs << "\n";
  ofs << "  Model &       model_;         ///< Owning model\n";
  ofs << "  double temp;\n";
  
  // nodes
  vector<net>::iterator netiter = mod->_net.begin();
  while(netiter != mod->_net.end()){
    ofs << "  int "<< netiter->_name<<";\n" ;
    ++netiter;
  }

  // element parameters
  list<parameter>::iterator pariter = mod->_param.begin();
  while(pariter != mod->_param.end()){
    if(pariter->_type == 1)
      ofs <<"  double " << pariter->_name<<";\n";
    ++pariter;
  }

  // states
  for(int i=0; i<mod->_ddtnum; ++i){
    ofs << "  int li_state_" <<  int2string(i) << ";\n";
  }

  // offsets
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"  int  AMatOffset_r"<<i<<"c"<<j<<";\n";
    }
  }

  // pointers
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"  double * f_matPosition_r"<<i<<"c"<<j<<";\n";
    }
  }

  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"  double * q_matPosition_r"<<i<<"c"<<j<<";\n";
    }
  }

  // intermediate rhs & jacs
  ofs << "  double fRHS[" << mod->_net.size() << "];\n";
  ofs << "  double qRHS[" << mod->_net.size() << "];\n";

  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"  double fMat_r"<<i<<"c"<<j<<";\n";
    }
  }

  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"  double qMat_r"<<i<<"c"<<j<<";\n";
    }
  }

  // jacobian structure
  ofs << "  static std::vector< std::vector<int> > jacStamp;\n";
  //  ofs << "  static std::vector<int> jacMap;\n";
  //  ofs << "  static std::vector< std::vector<int> > jacMap2;\n";
  
  ofs << "};\n";

  ofs << "\n\n";

  // model
  ofs << "class Model : public DeviceModel\n";
  ofs << "{\n";
  ofs << "typedef std::vector<Instance *> InstanceVector;\n";

  ofs << "friend class ParametricData<Model>;\n";
  ofs << "friend class Instance;\n";
  ofs << "friend class Traits;friend class Master;\n";

  ofs << "public:\n";
  ofs << "  Model(\n";
  ofs << "     const Configuration &       configuration,\n";
  ofs << "     const ModelBlock &        MB,\n";
  ofs << "     const FactoryBlock &      factory_block);\n";
  ofs << "  ~Model();\n";
  
  ofs << "private:\n";
  ofs << "  Model();\n";
  ofs << "  Model(const Model &);\n";
  ofs << "  Model &operator=(const Model &);\n";
  
  ofs << "public:\n";
  ofs << "  virtual void forEachInstance(DeviceInstanceOp &op) const /* override */;\n";
  
  ofs << "  virtual std::ostream &printOutInstances(std::ostream &os) const;\n";
  
  ofs << "  bool processParams ();\n";
  ofs << "  bool processInstanceParams ();\n";
  
  ofs << "  bool clearTemperatureData ();\n";
  
  ofs << "public:\n";
  ofs << "  void addInstance(Instance *instance) \n";
  ofs << "  {\n";
  ofs << "    instanceContainer.push_back(instance);\n";
  ofs << "  }\n";
  ofs << "\n";
  ofs << "private:\n";
  ofs << "  std::vector<Instance*> instanceContainer;\n";
  ofs << "\n";
  ofs << "private:\n";
  // parameters
  list<parameter>::iterator paramit;
  paramit = mod->_param.begin();

  while(paramit != mod->_param.end()){
    if(paramit->_type != 1)
      ofs << "  double " << paramit->_name << ";\n";
    ++paramit;
  }

  ofs << "  bool my_dummy;\n";
  
  ofs << "};\n";

  ofs << "\n\n";

  // master
  ofs << "class Master : public DeviceMaster<Traits>\n";
  ofs << "{\n";
  ofs << "  friend class SizeDependParam;\n";
  ofs << "public:\n";
  ofs << "  Master(\n";
  ofs << "     const Configuration &       configuration,\n";
  ofs << "     const FactoryBlock &      factory_block,\n";
  ofs << "     const SolverState & ss1,\n";
  ofs << "     const DeviceOptions & do1)\n";
  ofs << "    : DeviceMaster<Traits>(configuration, factory_block, ss1, do1)\n";
  ofs << "  {}\n";
  
  ofs << "  virtual bool updateState (double * solVec, double * staVec, double * stoVec);\n";
  
  ofs << "  virtual bool loadDAEVectors (double * solVec, double * fVec, double * qVec, double * bVec, double * leadF, double * leadQ, double * junctionV);\n";
  
  ofs << "  virtual bool loadDAEMatrices (Linear::Matrix & dFdx, Linear::Matrix & dQdx);\n";
  ofs << "\n";
  ofs << "};\n";

  ofs << "void registerDevice();\n";

  ofs << "\n";
  ofs << "}\n";
  ofs << "}\n";
  ofs << "}\n\n";

  ofs << "extern \"C\"{\n";
  ofs << "void registerDevice();\n";
  ofs << "}\n\n";
  
  ofs << "#endif\n";

  ofs.close();
}
  
void GenearteCCode(module* mod, const string &filename)
{
  char fn[1000];
  char fi[1000];
  sprintf(fn, "%s.C", filename.c_str());
  ofstream ofs(fn);
  if(!ofs){
    cerr<<"File: "<<filename<<" cannot open for read.\n";
    exit(-1);
  }

  ofs << "#include <Xyce_config.h>\n";

  
  ofs << "#include <N_DEV_DeviceOptions.h>\n";
  ofs << "#include <N_DEV_ExternData.h>\n";
  ofs << "#include <N_DEV_MatrixLoadData.h>\n";
  ofs << "#include <N_DEV_SolverState.h>\n";
  ofs << "#include <N_DEV_Message.h>\n";
  ofs << "#include <N_ERH_ErrorMgr.h>\n";
   
  ofs << "#include <N_LAS_Matrix.h>\n";
  ofs << "#include <N_LAS_Vector.h>\n";
  ofs << "#include <N_UTL_FeatureTest.h>\n";
  ofs << "#include <N_UTL_Math.h>\n";
  ofs << "#include <N_ANP_NoiseData.h>\n";
  ofs << "#include \"" << filename.c_str() << ".h\"\n\n";
  ofs << "using std::max;\n";
  

  ofs << "namespace Xyce {\n";
  ofs << "namespace Device {\n";
  
  ofs << "namespace ADMS_Device {\n";

  ofs << std::setiosflags(ios::scientific);
  ofs << std::setprecision(8);
  
  ofs << "void Traits::loadInstanceParameters(ParametricData<ADMS_Device::Instance> &p)\n";
  ofs << "{\n";
  //  ofs << setiosflags(ios::fixed);

  list<parameter>::iterator paramit;
  paramit = mod->_param.begin();
  while(paramit != mod->_param.end()){
    if(paramit->_type == 1)
      {    
	ofs << "p.addPar(\"" << paramit->_name << "\", " << paramit->_defvalue << ", &ADMS_Device::Instance::" << paramit->_name << ")\n";
	ofs << ".setUnit(U_NONE)\n";
	ofs << ".setCategory(CAT_PROCESS)\n";
	ofs << ".setDescription(\"Desciption not available\");\n";
      }
    ++paramit;
  }
  ofs << "}\n";

  ofs << "void Traits::loadModelParameters(ParametricData<ADMS_Device::Model> &p)\n";
  ofs << "{\n\n";

  paramit = mod->_param.begin();
  while(paramit != mod->_param.end()){
    if(paramit->_type != 1)
      {
    
	ofs << "p.addPar(\"" << paramit->_name << "\", " << paramit->_defvalue  <<", &ADMS_Device::Model::" << paramit->_name << ")\n";
	ofs << ".setUnit(U_NONE)\n";
	ofs << ".setCategory(CAT_PROCESS)\n";
	ofs << ".setDescription(\"Desciption not available\");\n";
      }
    ++paramit;
  }
  ofs << "}\n\n";

  ofs << "std::vector< std::vector<int> > Instance::jacStamp;\n";

  ofs << "bool Instance::processParams ()\n";
  ofs << "{\n";
  ofs << "temp = getDeviceOptions().temp.getImmutableValue<double>();\n";
  ofs << "updateTemperature(temp);\n";
  ofs << "return true;\n";
  ofs << "}\n\n";

  ofs << "Instance::Instance(\n";
  ofs << "const Configuration & configuration,\n";
  ofs << "const InstanceBlock & IB,\n";
  ofs << "Model &model,\n";
  ofs << "const FactoryBlock &  factory_block)\n";
  ofs << ": DeviceInstance(IB, configuration.getInstanceParameters(), factory_block),\n";
  ofs << " model_(model),\n";

  // nodes
  vector<net>::iterator netiter = mod->_net.begin();
  while(netiter != mod->_net.end()){
    ofs << netiter->_name<<"(0),\n" ;
    ++netiter;
  }

  // element parameters
  list<parameter>::iterator pariter = mod->_param.begin();
  while(pariter != mod->_param.end()){
    if(pariter->_type == 1)
      ofs << pariter->_name<<"(0.0),\n";
    ++pariter;
  }

  // offsets
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"AMatOffset_r"<<i<<"c"<<j<<"(0),\n";
    }
  }
  
  // states
  for(int i=0; i<mod->_ddtnum; ++i){
    ofs << "li_state_" <<  int2string(i) << "(0),\n";
  }

  // pointers
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"f_matPosition_r"<<i<<"c"<<j<<"(0),\n";
    }
  }

  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
	{
	  if(i == mod->_net.size()-1 && j == mod->_net.size()-1)
	    ofs<<"q_matPosition_r"<<i<<"c"<<j<<"(0)\n";
	  else
	    ofs << "q_matPosition_r"<<i<<"c"<<j<<"(0),\n";
	}
    }
  }
  

  ofs << "{\n";
  ofs << "numIntVars = " << mod->_net.size() - mod->_port.size() << ";\n";
  ofs << "numExtVars = " << mod->_port.size() << ";\n";
  ofs << "numStateVars = " << mod->_ddtnum << ";\n";
  ofs << "setNumStoreVars(0);\n";
  ofs << "setNumBranchDataVars(0);\n";
  ofs << "numBranchDataVarsIfAllocated = 0;\n";

  // now Jacobian stamp structure
  std::vector<int> vsize(mod->_net.size());
  ofs << "if(jacStamp.empty()) {\n";
  ofs << "jacStamp.resize(" << mod->_net.size() << ");\n";
  for(int i=0; i<mod->_net.size(); ++i){
    vsize[i] = 0;
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
	vsize[i]++;
    }
  }

  int nzcnt;
  for(int i=0; i<mod->_net.size(); ++i){
    ofs << "jacStamp[" << i << "].resize(" << vsize[i] << ");\n";
    nzcnt = 0;
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
	ofs << "jacStamp[" << i << "][" << nzcnt++ << "] = "  << j << ";\n";
    }
  }

  ofs << "} // end of if(jacStamp.empty()) \n";

  ofs << "setDefaultParams();\n";

  ofs << "setParams(IB.params);\n";

  //  ofs << "updateDependentParams();\n";

  ofs << "processParams();\n";
  

  ofs << "}\n\n";


  ofs << "Instance::~Instance()\n";
  ofs << "{\n";
  ofs << "}\n\n";


  ofs << "void Instance::registerLIDs( const std::vector<int> & intLIDVecRef,\n";
  ofs << " const std::vector<int> & extLIDVecRef )\n";
  ofs << "{\n";

  ofs << "intLIDVec = intLIDVecRef;\n";
  ofs << "extLIDVec = extLIDVecRef;\n";

  for(int i = 0; i < mod->_port.size(); ++i)
    {
      ofs << mod->_net[i]._name << " =  extLIDVec[" << i << "];\n";
    }

  for(int i = mod->_port.size(); i < mod->_net.size(); ++i)
    {
      ofs << mod->_net[i]._name << " =  intLIDVec[" << i - mod->_port.size() << "];\n";
    }
  
  
  ofs << "}\n\n";


  ofs << "void Instance::loadNodeSymbols(Util::SymbolTable &symbol_table) const\n";
  ofs << "{\n";
  if(mod->_net.size() > mod->_port.size())
    {
      for(int i = mod->_port.size(); i < mod->_net.size(); ++i)
	ofs << "        addInternalNode(symbol_table, " << mod->_net[i]._name << ", getName(), \"" <<  mod->_net[i]._name << "\");\n";
    }
  
  ofs << "}\n\n";


  ofs << "void Instance::registerStoreLIDs( const std::vector<int> & stoLIDVecRef )\n";
  ofs << "{\n";
  ofs << "}\n\n";

  ofs << "void Instance::registerStateLIDs( const std::vector<int> & staLIDVecRef )\n";
  ofs << "{\n";
  ofs << "}\n\n";
  
  ofs << "void Instance::registerBranchDataLIDs(const std::vector<int> & branchLIDVecRef)\n";
  ofs << "{\n";
  ofs << "}\n\n";


  ofs << "const std::vector< std::vector<int> > & Instance::jacobianStamp() const\n";
  ofs << "{\n";
  ofs << "return jacStamp;\n";
  ofs << "}\n\n";

  ofs << "void Instance::registerJacLIDs( const std::vector< std::vector<int> > & jacLIDVec )\n";
  ofs << "{\n";
  ofs << "DeviceInstance::registerJacLIDs( jacLIDVec );\n";

  // offsets
  int cnt = 0;
  for(int i=0; i<mod->_net.size(); ++i){
    cnt = 0;
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"AMatOffset_r"<<i<<"c"<<j<<" = jacLIDVec[" << i << "][" << cnt++ << "];\n";
    }
  }
  
  ofs << "}\n\n";


  ofs << "void Instance::setupPointers () \n";
  ofs << "{\n";
  ofs << "#ifndef Xyce_NONPOINTER_MATRIX_LOAD\n";

  ofs << "Linear::Matrix & dFdx = *(extData.dFdxMatrixPtr);\n";
  ofs << "Linear::Matrix & dQdx = *(extData.dQdxMatrixPtr);\n";

  // pointers
  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"f_matPosition_r"<<i<<"c"<<j<<" = &(dFdx[" << mod->_net[i]._name  << "][AMatOffset_r" << i << "c" << j << "]);\n";
    }
  }

  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs<<"q_matPosition_r"<<i<<"c"<<j<<" = &(dQdx[" << mod->_net[i]._name  << "][AMatOffset_r" << i << "c" << j << "]);\n";
    }
  }

  ofs << "#endif\n";
  ofs << "}\n\n";



  ofs << "bool Instance::updateTemperature (const double & temp_tmp)\n";
  ofs << "{\n";

  ofs << "}\n\n";


  ofs << "bool Instance::updateIntermediateVars ()\n";
  ofs << "{\n";

  ofs << "updateIntermediateVars_RHS();\n";
  ofs << "updateIntermediateVars_Jac();\n";
  ofs << "return true;\n";
  
  ofs << "}\n\n";

  ofs << "bool Instance::updateIntermediateVars_RHS()\n";
  ofs << "{\n";
  EquationGenerator(mod, ofs);
  ofs << "}\n\n";


  ofs << "bool Instance::updateIntermediateVars_Jac()\n";
  ofs << "{\n";
  JacobiGenerator(mod, ofs);
  ofs << "}\n\n";

  ofs << "bool Instance::updatePrimaryState ()\n";
  ofs << "{\n";
  ofs << "    bool bsuccess = true;\n";
  ofs << "    bsuccess = updateIntermediateVars ();\n";
  ofs << "    return bsuccess;\n";
  ofs << "}\n\n";

  ofs << "bool Instance::loadDAEQVector ()\n";
  ofs << "{\n";
  ofs << "    double * qVec = extData.daeQVectorRawPtr;\n";

  for(int i = 0; i < mod->_net.size(); ++i)
    ofs << "    qVec[" << mod->_net[i]._name << "] += qRHS[" << i << "];\n";

  ofs << "    return true;\n";
  
  ofs << "}\n\n";

  ofs << "bool Instance::loadDAEFVector ()\n";
  ofs << "{\n";
  ofs << "    double * fVec = extData.daeFVectorRawPtr;\n";
  
  for(int i = 0; i < mod->_net.size(); ++i)
    ofs << "    fVec[" << mod->_net[i]._name << "] += fRHS[" << i << "];\n";

  ofs << "    return true;\n";
  ofs << "}\n\n";


  ofs << "bool Instance::loadDAEdQdx ()\n";
  ofs << "{\n";
  ofs << "    Linear::Matrix & dQdx = *(extData.dQdxMatrixPtr);\n";

  for(int i = 0; i < mod->_net.size(); ++i)
    for(int j = 0; j < mod->_net.size(); ++j)
      if(mod->_matstructrue[i][j] == 1)
	{
	  ofs << "    dQdx[" << mod->_net[i]._name <<  "][AMatOffset_r" << i << "c" << j << "] += qMat_r" << i << "c" << j << ";\n"; 
	}

  ofs << "    return true;\n";
  ofs << "}\n\n";

  ofs << "bool Instance::loadDAEdFdx ()\n";
  ofs << "{\n";
  ofs << "    Linear::Matrix & dFdx = *(extData.dFdxMatrixPtr);\n";

  for(int i = 0; i < mod->_net.size(); ++i)
    for(int j = 0; j < mod->_net.size(); ++j)
      if(mod->_matstructrue[i][j] == 1)
	{
	  ofs << "    dFdx[" << mod->_net[i]._name <<  "][AMatOffset_r" << i << "c" << j << "] += fMat_r" << i << "c" << j << ";\n"; 
	}

  ofs << "    return true;\n";
  ofs << "}\n\n";

  ofs << "bool Model::processParams ()\n";
  ofs << "{\n";
  ofs << "}\n\n";

  ofs << "bool Model::processInstanceParams()\n";
  ofs << "{\n";
  ofs << "    std::vector<Instance*>::iterator iter;\n";
  ofs << "    std::vector<Instance*>::iterator first = instanceContainer.begin();\n";
  ofs << "    std::vector<Instance*>::iterator last  = instanceContainer.end();\n";
  ofs << "\n";
  ofs << "    for (iter=first; iter!=last; ++iter)\n";
  ofs << "    {\n";
  ofs << "        (*iter)->processParams();\n";
  ofs << "    }\n";
  ofs << "\n";
  ofs << "    return true;\n";
  ofs << "}\n\n";

  ofs << "Model::Model(\n";
  ofs << "const Configuration & configuration,\n";
  ofs << "  const ModelBlock &    MB,\n";
  ofs << "  const FactoryBlock &  factory_block)\n";
  ofs << "  : DeviceModel(MB, configuration.getModelParameters(), factory_block),\n";

  paramit = mod->_param.begin();
  while(paramit != mod->_param.end()){
    if(paramit->_type != 1)
      {
	ofs << "  " <<  paramit->_name << "(0.), \n";
      }
    ++paramit;
  }

  ofs << "  my_dummy(false)\n";
  ofs << "{\n";
  ofs << "    setDefaultParams();\n";
  ofs << "    setModParams(MB.params);\n";
  ofs << "    updateDependentParameters();\n";
  ofs << "    processParams();\n";
  
  ofs << "}\n\n";


  ofs << "Model::~Model ()\n";
  ofs << "{\n";
  ofs << "    std::vector<Instance*>::iterator iter;\n";
  ofs << "    std::vector<Instance*>::iterator first = instanceContainer.begin();\n";
  ofs << "    std::vector<Instance*>::iterator last  = instanceContainer.end();\n";
  ofs << "    \n";
  ofs << "    for (iter=first; iter!=last; ++iter)\n";
  ofs << "    {\n";
  ofs << "      delete (*iter);\n";
  ofs << "    }\n";
  ofs << "}\n\n";

  ofs << "std::ostream &Model::printOutInstances (std::ostream &os) const\n";
  ofs << "{\n";
  ofs << "  std::vector<Instance*>::const_iterator iter;\n"; 
  ofs << "  std::vector<Instance*>::const_iterator first = instanceContainer.begin();\n";
  ofs << "  std::vector<Instance*>::const_iterator last  = instanceContainer.end();\n";
  ofs << "\n";
  ofs << "  int i;\n";
  ofs << "  os << std::endl;\n";
  ofs << "  os << \"    name     modelName  Parameters\" << std::endl;\n";
  ofs << "\n";
  ofs << "  for (i=0, iter=first; iter!=last; ++iter,++i)\n";
  ofs <<  " {\n";
  ofs << "    os << \"  \" << i << \": \" << (*iter)->getName() << \"\t\";\n";
  ofs << "    os << getName();\n";
  ofs << "    os << std::endl;\n";
  ofs << "  }\n";
  ofs << "\n";
  ofs << "  os << std::endl;\n";
  ofs << "\n";
  ofs << "  return os;\n";
  ofs << "}\n\n";

  ofs << "void Model::forEachInstance(DeviceInstanceOp &op) const /* override */ \n";
  ofs << "{\n";
  ofs << "  for (std::vector<Instance *>::const_iterator it = instanceContainer.begin(); it != instanceContainer.end(); ++it)\n";
  ofs << "    op(*it);\n";
  ofs << "}\n\n";

  ofs << "bool Model::clearTemperatureData ()\n";
  ofs << "{\n";
  ofs << "}\n";


  ofs << "bool Master::updateState (double * solVec, double * staVec, double * stoVec)\n";
  ofs << "{\n";
  ofs << "    bool bsuccess = true;\n";
  ofs << "    for (InstanceVector::const_iterator it = getInstanceBegin(); it != getInstanceEnd(); ++it)\n";
  ofs << "    {\n";
  ofs << "      Instance & mi = *(*it);\n";
  ofs << "    \n";
  ofs << "      bool btmp = mi.updateIntermediateVars ();\n";
  ofs << "      bsuccess = bsuccess && btmp;\n";
  ofs << "    }\n";
  ofs << "\n";
  ofs << "    return bsuccess;\n";
  ofs << "}\n\n";

  ofs << "bool Master::loadDAEVectors (double * solVec, double * fVec, double *qVec,  double * bVec, double * leadF, double * leadQ, double * junctionV)\n";
  ofs << "{\n";
  ofs << "    for (InstanceVector::const_iterator it = getInstanceBegin(); it != getInstanceEnd(); ++it)\n";
  ofs << "    {\n";
  ofs << "      Instance & mi = *(*it);\n";
  ofs << "  \n";

  for(int i = 0; i < mod->_net.size(); ++i)
    ofs << "      fVec[mi." << mod->_net[i]._name << "] += mi.fRHS[" << i << "];\n";

  for(int i = 0; i < mod->_net.size(); ++i)
    ofs << "      qVec[mi." << mod->_net[i]._name << "] += mi.qRHS[" << i << "];\n";

  ofs << "    }\n";
  ofs << "    return true;\n";
  ofs << "}\n\n";

  ofs << "#ifndef Xyce_NONPOINTER_MATRIX_LOAD\n";
  ofs << "bool Master::loadDAEMatrices (Linear::Matrix & dFdx, Linear::Matrix & dQdx)\n";
  ofs << "{\n";
  ofs << "    for (InstanceVector::const_iterator it = getInstanceBegin(); it != getInstanceEnd(); ++it)\n";
  ofs << "    {\n";
  ofs << "      Instance & mi = *(*it);\n";

  for(int i = 0; i < mod->_net.size(); ++i)
    for(int j = 0; j < mod->_net.size(); ++j)
      if(mod->_matstructrue[i][j] == 1)
	{
	  ofs << "      *mi.f_matPosition_r" << i << "c" << j << " += mi.fMat_r" << i << "c" << j << ";\n"; 
	}

    for(int i = 0; i < mod->_net.size(); ++i)
    for(int j = 0; j < mod->_net.size(); ++j)
      if(mod->_matstructrue[i][j] == 1)
	{
	  ofs << "      *mi.q_matPosition_r" << i << "c" << j << " += mi.qMat_r" << i << "c" << j << ";\n"; 
	}

  ofs << "    }\n";

  ofs << "    return true;\n";
  ofs << "}\n\n";

  ofs << "#else\n";
  ofs << "bool Master::loadDAEMatrices (Linear::Matrix & dFdx, Linear::Matrix & dQdx)\n";
  ofs << "{\n";
  ofs << "    int sizeInstances = instanceContainer_.size();\n";
  ofs << "    for (int i=0; i<sizeInstances; ++i)\n";
  ofs << "    {\n";
  ofs << "      Instance & mi = *(instanceContainer_.at(i));\n";
  ofs << "\n";

  for(int i = 0; i < mod->_net.size(); ++i)
    for(int j = 0; j < mod->_net.size(); ++j)
      if(mod->_matstructrue[i][j] == 1)
	{
	  ofs << "      dFdx[mi." << mod->_net[i]._name << "][AMatOffset_r"  << i <<  "c" << j << "] += mi.fMat_r" << i << "c" << j << ";\n"; 
	}

  for(int i = 0; i < mod->_net.size(); ++i)
    for(int j = 0; j < mod->_net.size(); ++j)
      if(mod->_matstructrue[i][j] == 1)
	{
	  ofs << "      dQdx[mi." << mod->_net[i]._name << "][AMatOffset_r"  << i <<  "c" << j << "] += mi.qMat_r" << i << "c" << j << ";\n"; 
	}

  ofs << "    }\n";
  ofs << "    return true;\n";
  ofs << "}\n\n";
  ofs << "#endif\n\n";

  ofs << "Device *Traits::factory(const Configuration &configuration, const FactoryBlock &factory_block)\n";
  ofs << "{\n";
  ofs << "    return new Master(configuration, factory_block, factory_block.solverState_, factory_block.deviceOptions_);\n";
  ofs << "}\n\n";


  ofs << "void registerDevice()\n";
  ofs << "{\n";
  ofs << "    Config<Traits>::addConfiguration()\n";
  ofs << "      .registerDevice(\""<< filename << "\", 1)\n";
  ofs << "      .registerModelType(\"" << filename << "\", 1);\n";
  ofs << "}\n\n";

  
  
  ofs << "}\n";
  ofs << "}\n";
  ofs << "}\n\n";

  ofs << "extern \"C\"{\n";
  ofs << "void registerDevice()\n";
  ofs << "{\n";
  ofs << "    Xyce::Device::ADMS_Device::registerDevice();\n";
  ofs << "}\n";
  ofs << "}\n\n";

  ofs.close();
}



void EquationGenerator(module *mod, std::ofstream& ofs)
{
  string ddtexp, ddtans;
  string stri;

  /// Begin Variable define
  for(int i=0; i<mod->_ddtnum; ++i){
    ddtexp += ", DdtExp" + int2string(i);
    ddtans += ", DdtAns" + int2string(i);
  }

  if(mod->_ddtnum != 0)
    {
      ofs << "    double" + ddtexp.substr(1) + ";\n";
      ofs << "    double" + ddtans.substr(1) + ";\n";
    }

  ofs << "    double myadms_t1, myadms_t2;\n";
  
  list<variable>::iterator varit;
  varit = mod->_variable.begin();
  while(varit != mod->_variable.end()){
    ofs <<  "    double " +  varit->_name + ";\n";
    ++varit;
  }

  map<string, int>::iterator dervit = mod->_dervar.begin();
  while(dervit != mod->_dervar.end()){
    ofs <<  "    double "
	<< dervit->first.substr(1, (dervit->first).find("Dv")-1)
	<< " = (extData.nextSolVectorRawPtr)[" << mod->_net[dervit->second]._name  <<  "];\n";
    ++dervit;
  } // End of variable define

  for(int i = 0; i < mod->_net.size(); ++i)
    {
      ofs << "    fRHS[" + int2string(i) + "] = 0.;\n";
    }

  for(int i = 0; i < mod->_net.size(); ++i)
    {
      ofs << "    qRHS[" + int2string(i) + "] = 0.;\n";
    }
  

  /// begin calculate
  string destmp;
  string org_destmp;
  int flownode;
  source *mysource;
  list<statement>::iterator iter = mod->_main._steps.begin();
  list<source*>::iterator sourceiter;
  vector<string> ddts;
  sourceiter = mod->_contribute.begin();
  while(iter != mod->_main._steps.end()){
    if(iter->_mode == 4 || iter->_mode == 5) {
      ++iter; continue;
    } else if(iter->_mode == 2){
      destmp = ReplaceModelParam(*iter);
      org_destmp = destmp;
      ddts = ReplaceDdt(destmp);
      mysource = *sourceiter;
      ++sourceiter;
      if(mysource->_type == 1 || mysource->_type == 2){
        if(mysource->_nodenum == 1){
	  ofs <<  "    myadms_t1 = " << destmp << ";\n";
          ofs << "    fRHS[" + int2string(mysource->_pos) << "] += myadms_t1;\n";
	  if(ddts.size() > 0)
	    {
	      ofs << "   myadms_t2 = " + org_destmp << ";\n";
	      ofs << "   qRHS[" << int2string(mysource->_pos) << "] += myadms_t2 - myadms_t1;\n";
	    }
					     
        } else if(mysource->_nodenum == 2){
	  ofs << "    myadms_t1 = " << destmp << ";\n";
          ofs << "    fRHS[" << int2string(mysource->_pos) << "] += myadms_t1;\n";
          ofs << "    fRHS[" << int2string(mysource->_neg) << "] -= myadms_t1;\n";

	  if(ddts.size() > 0)
	    {
	      ofs << "    myadms_t2 = " << org_destmp << ";\n";
	      ofs << "    qRHS[" << int2string(mysource->_pos) << "] += myadms_t2 - myadms_t1;\n";
	      ofs << "    qRHS[" << int2string(mysource->_neg) << "] -= (myadms_t2 - myadms_t1);\n";
	    }
	  
        } else {
          cerr<<"Too many nodes in source."<<endl;
          exit(-1);
        }
      } else if (mysource->_type == 0 || mysource->_type == 3){
        if(mysource->_nodenum == 1){
	  //          cerr<<"V(node) not impl yet.\n";
	  //          exit(-1);
        } else if (mysource->_nodenum == 2){
          flownode = GetFlowNode(mysource->_pos, mysource->_neg);
	  ofs << "    myadms_t1 = " << destmp << ";\n";
          ofs << "    fRHS[" << int2string(flownode) << "] += myadms_t1;\n";

	  if(ddts.size() > 0)
	    {
	      ofs << "    myadms_t2 = " << org_destmp << ";\n";
	      ofs << "    qRHS[" << int2string(flownode) << "] += (myadms_t2 - myadms_t1);\n";
	    }
	  
        } else {
          cerr<<"Too many nodes in source."<<endl;
          exit(-1);
        }
      }
    } else {
      ofs << "    " << ReplaceModelParam(*iter) << "\n";
    }
    ++iter;
  }
  /// stamp RHS
  //  for(int i=0; i<mod->_net.size(); ++i){
  //   equStr += "    equation->AddtoCachedRhs(netnum[" + int2string(i)
  //    + "], rhsPosition_[Net::" + mod->_net[i]._name
  //    + "], _rhsN" + int2string(i) + ", 1);\n";
  // }
  
}

void JacobiGenerator(module *mod, std::ofstream& ofs)
{
  string ddtexp, ddtans;
  string stri;

  /// begin variables declaration
  ofs <<  "    double _der0 = 1.0;\n";
  for(int i=0; i<mod->_ddtnum; ++i){
    ddtexp += ", DdtExp" + int2string(i);
    ddtans += ", DdtAns" + int2string(i);
  }

  if(mod->_ddtnum != 0)
    {
      ofs << "    double" << ddtexp.substr(1) << ";\n";
      ofs << "    double" << ddtans.substr(1) << ";\n";
    }
      
  map<string, int>::iterator dervit = mod->_dervar.begin();
  while(dervit != mod->_dervar.end()){
    ofs << "    double "
	<< dervit->first.substr(1, (dervit->first).find("Dv")-1)
	<< " =  (extData.nextSolVectorRawPtr)["
	<< mod->_net[dervit->second]._name << "];\n";
    ofs <<  "    double " << dervit->first << " = 1.;\n";
    ++dervit;
  }

  list<variable>::iterator varit;
  varit = mod->_variable.begin();
  while(varit != mod->_variable.end()){
    ofs << "    double " <<  varit->_name  << ";\n";
    ++varit;
  }


  map<string, int>::iterator tmpvariter = mod->_tmpdervar.begin();
  int count = 0;
  while(tmpvariter != mod->_tmpdervar.end()){
    if(count%5 == 0){
      if(count > 1)  ofs << ";\n";
      ofs << "    double " << tmpvariter->first;
    }
    else ofs << ", " << tmpvariter->first;
    ++tmpvariter;
    ++count;
  }
  if(count) ofs << ";\n";
  ofs <<  "    double contributetmp";
  for(int i=0; i<gModule->_net.size(); ++i){
    if(i%4 == 0) ofs <<  ";\n    double dcontributetmpDv" << int2string(i);
    else ofs << ", dcontributetmpDv" << int2string(i);
  }
  ofs << ";\n\n";

  ofs <<  "    double contributetmporg";
  for(int i=0; i<gModule->_net.size(); ++i){
    if(i%4 == 0) ofs << ";\n    double dcontributetmporgDv" << int2string(i);
    else ofs << ", dcontributetmporgDv" + int2string(i);
  }
  ofs <<  ";\n\n";

  // begin current calculate and derivation calculate
  statement mystat;
  set<string> dertmpvar;
  vector<vector<string> > dddts;
  bitset<BIT_> tmpbit;
  map<string, bitset<BIT_> >::iterator viter;
  string destmp;
  source *mysource;


  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs << "    fMat_r" << int2string(i) << "c" << int2string(j) << " = 0.;\n";
    }
  }

  for(int i=0; i<mod->_net.size(); ++i){
    for(int j=0; j<mod->_net.size(); ++j){
      if(mod->_matstructrue[i][j] == 1)
        ofs << "    qMat_r" << int2string(i) << "c" << int2string(j) << " = 0.;\n";
    }
  }

  ofs << "\n";


  string org_destmp;
  list<statement>::iterator iter = mod->_main._steps.begin();
  list<source*>::iterator sourceiter;
  sourceiter = mod->_contribute.begin();
  dddts.resize(mod->_net.size());
  while(iter != mod->_main._steps.end()){
    if(iter->_mode == 4) {
      ofs << "    " << iter->_describ << "\n";
    } else if(iter->_mode == 2){
      mysource = *sourceiter;
      ++sourceiter;
      tmpbit = 0;
      viter = iter->_var.begin();
      while(viter != iter->_var.end()){
        tmpbit |= viter->second;
        ++viter;
      }
      destmp = "    contributetmp = " + iter->_describ + ";\n";
      destmp += "    //Derivate " + int2string(tmpbit.to_ulong());
      mystat = *iter;
      mystat._describ = "    contributetmp = " + iter->_describ + ";";
      if(tmpbit != 0){
	org_destmp = calculate_deriv(mystat, dertmpvar);
        destmp = calculate_deriv_replace(mystat, dertmpvar, dddts);
        destmp = ReplaceModelParam(destmp, mystat._param);
      } else {
        destmp = ReplaceModelParam(destmp, mystat._param);
      }
      // Derivate of contributetmp`
      ofs << "    " << destmp << "\n";

      destmp = "    contributetmporg = " + iter->_describ + ";\n";
      destmp += "    //Derivate " + int2string(tmpbit.to_ulong());
      mystat = *iter;
      mystat._describ = "    contributetmporg = " + iter->_describ + ";";
      if(tmpbit != 0){
        destmp = calculate_deriv(mystat, dertmpvar);
        destmp = ReplaceModelParam(destmp, mystat._param);
      } else {
        destmp = ReplaceModelParam(destmp, mystat._param);
      }
      // Derivate of contributetmp`
      ofs <<  "    " << destmp << "\n";

      // power or current, do contribution, else do nothing
      if(mysource->_type == 1 || mysource->_type == 2) {
        if(mysource->_nodenum == 2){
          for(int i=0; i<mod->_net.size(); ++i){
            if(tmpbit[i] != 0){
              ofs << "    fMat_r" << int2string(mysource->_pos) << "c" << 
                int2string(i) << " += dcontributetmpDv" << int2string(i) << ";\n";
              ofs << "    fMat_r" << int2string(mysource->_neg) << "c" << 
                int2string(i) << " += -dcontributetmpDv" << int2string(i) << ";\n";

	      if(dddts[i].size() != 0)
		{
		  ofs << "    qMat_r" << int2string(mysource->_pos) << "c" << int2string(i) << " += (dcontributetmporgDv" << int2string(i) << " -  dcontributetmpDv" << int2string(i) << ");\n";
		  ofs << "    qMat_r" << int2string(mysource->_neg) << "c" + int2string(i) << " -= (dcontributetmporgDv" << int2string(i) << " -  dcontributetmpDv" << int2string(i) << ");\n";
		}
            }
          }
        } else if(mysource->_nodenum == 1){
          for(int i=0; i<mod->_net.size(); ++i){
            if(tmpbit[i] != 0){
              ofs << "    fMat_r" << int2string(mysource->_pos) << "c"
		  << int2string(i) << " += dcontributetmpDv" << int2string(i) << ";\n";

	      if(dddts[i].size() != 0)
		{
		  ofs << "    qMat_r" << int2string(mysource->_pos) << "c" << int2string(i) << " += (dcontributetmporgDv" << int2string(i) << " -  dcontributetmpDv" << int2string(i) << ");\n";
		}

            }
          }
        }
      } else if (mysource->_type == 0 || mysource->_type == 3){
        if(mysource->_nodenum == 1){
	  // do nothing
	  //          cerr<<"V(node) not impl yet.\n";
	  //          exit(-1);
        } else if (mysource->_nodenum == 2){

        } else {
          cerr<<"Too many nodes in source."<<endl;
          exit(-1);
        }
      }
    } else if(iter->_mode == 0){
      if(iter->_type == true)
      {
        destmp = calculate_deriv(*iter, dertmpvar);
        destmp = ReplaceModelParam(destmp, iter->_param);
        ofs << "    " << destmp << "\n";
      } else {
        ofs << "    " << ReplaceModelParam(*iter) << "\n";
      }
    }
    ++iter;
  }

  /// stamp matrix
  // for(int i=0; i<mod->_net.size(); ++i){
  //   for(int j=0; j<mod->_net.size(); ++j){
  //     if(mod->_matstructrue[i][j] == 1){
  //       jacStr += "    double _matValueN" + int2string(i) + "N" + int2string(j) + " = 0;\n";
  //     }
  //   }
  // }
  
  // for(int i=0; i<mod->_net.size(); ++i){
  //   for(int j=0; j<mod->_net.size(); ++j){
  //     if(mod->_matstructrue[i][j] == 1){
  //       jacStr += "    equation->SetCachedMatrix(matEleN" + int2string(i) + "N" +
  //         int2string(j) + " , _matValueN" + int2string(i) + "N" + int2string(j) + ");\n";
  //     }
  //   }
  // }

}
