"""isp Layer 2: Template registry."""
from rtlgen.registry import TemplateRegistry
from skills.image.isp.functional import *

TemplateRegistry.register('isp_axi_in', isp_axi_in_template)
TemplateRegistry.register('isp_crop', isp_crop_template)
TemplateRegistry.register('isp_dpc', isp_dpc_template)
TemplateRegistry.register('isp_blc', isp_blc_template)
TemplateRegistry.register('isp_oecf', isp_oecf_template)
TemplateRegistry.register('isp_dg', isp_dg_template)
TemplateRegistry.register('isp_lsc', isp_lsc_template)
TemplateRegistry.register('isp_bnr', isp_bnr_template)
TemplateRegistry.register('isp_wb', isp_wb_template)
TemplateRegistry.register('isp_awb_stats', isp_awb_stats_template)
TemplateRegistry.register('isp_demosaic', isp_demosaic_template)
TemplateRegistry.register('isp_ccm', isp_ccm_template)
TemplateRegistry.register('isp_gamma', isp_gamma_template)
TemplateRegistry.register('isp_ae_stats', isp_ae_stats_template)
TemplateRegistry.register('isp_csc', isp_csc_template)
TemplateRegistry.register('isp_ldci', isp_ldci_template)
TemplateRegistry.register('isp_sharpen', isp_sharpen_template)
TemplateRegistry.register('isp_nr2d', isp_nr2d_template)
TemplateRegistry.register('isp_scale', isp_scale_template)
TemplateRegistry.register('isp_yuv', isp_yuv_template)
TemplateRegistry.register('isp_axi_out', isp_axi_out_template)
TemplateRegistry.register('isp_apb_regs', isp_apb_regs_template)
