#ifndef verilog_ams_src_ekv3_H_
#define verilog_ams_src_ekv3_H_
/////////////////////////////////////////////////////////////////////////////////////////////////////
/// Generated by VA-C-Generator. DO NOT EDIT!
/// @author vaParser
/////////////////////////////////////////////////////////////////////////////////////////////////////

// ----------   Standard Includes   ----------
#include <N_DEV_Configuration.h>
#include <map>
#include <N_DEV_DeviceMaster.h>
#include <N_DEV_DeviceInstance.h>
#include <N_DEV_DeviceModel.h>
#include <N_DEV_DeviceBlock.h>
namespace Xyce {
namespace Device {
namespace ADMS_Device {
class Model;
class Instance;

struct Traits : public DeviceTraits<Model, Instance>
{
static const char *name() {return  "AHDL Model";}
static const char *deviceTypeName() {return "AHDL level 1";}
static int numNodes() {return 4;}
static bool modelRequired() {return false;}
static bool isLinearDevice() {return false;}

static Device *factory(const Configuration &configuration, const FactoryBlock &factory_block);
static void loadModelParameters(ParametricData<Model> &model_parameters);
static void loadInstanceParameters(ParametricData<Instance> &instance_parameters);
};

class Instance : public DeviceInstance
{
friend class SizeDependParam;
friend class ParametricData<Instance>;
friend class Model;
friend class Traits;friend class Master;

// functions
public:

Instance(
const Configuration &       configuration,
const InstanceBlock &     IB,
Model &                   Miter,
const FactoryBlock &      factory_block);

~Instance();

private:
Instance(const Instance &);
Instance &operator=(const Instance &);

public:
void registerLIDs( const std::vector<int> & intLIDVecRef,
const std::vector<int> & extLIDVecRef );
void registerStateLIDs( const std::vector<int> & staLIDVecRef);
void registerStoreLIDs( const std::vector<int> & stoLIDVecRef);
virtual void registerBranchDataLIDs(const std::vector<int> & branchLIDVecRef);
void loadNodeSymbols(Util::SymbolTable &symbol_table) const; // override
const std::vector< std::vector<int> > & jacobianStamp() const;
void registerJacLIDs( const std::vector< std::vector<int> > & jacLIDVec );
bool processParams ();
bool updateTemperature(const double & temp_tmp);
bool updateIntermediateVars_RHS();
bool updateIntermediateVars_Jac();
bool updateIntermediateVars ();
bool updatePrimaryState ();
bool loadDAEQVector ();
bool loadDAEFVector ();
bool auxChargeCalculations ();
bool setupCapacitors_newDAE ();
bool setupCapacitors_oldDAE ();
bool loadDAEdQdx ();
bool loadDAEdFdx ();
void setupPointers ();
public:
// Getters and setters
Model &getModel() 
{
return model_;
}

private:

  Model &       model_;         ///< Owning model
  double temp;
  int d;
  int g;
  int s;
  int b;
  int di;
  int si;
  int noi;
  double L;
  double W;
  double NF;
  double M;
  double AD;
  double AS;
  double PD;
  double PS;
  double SA;
  double SB;
  double SD;
  int li_state_0;
  int li_state_1;
  int li_state_2;
  int li_state_3;
  int li_state_4;
  int li_state_5;
  int li_state_6;
  int li_state_7;
  int li_state_8;
  int li_state_9;
  int li_state_10;
  int li_state_11;
  int li_state_12;
  int li_state_13;
  int li_state_14;
  int li_state_15;
  int li_state_16;
  int li_state_17;
  int li_state_18;
  int li_state_19;
  int li_state_20;
  int li_state_21;
  int li_state_22;
  int li_state_23;
  int  AMatOffset_r0c0;
  int  AMatOffset_r0c4;
  int  AMatOffset_r1c1;
  int  AMatOffset_r1c3;
  int  AMatOffset_r1c4;
  int  AMatOffset_r1c5;
  int  AMatOffset_r1c6;
  int  AMatOffset_r2c2;
  int  AMatOffset_r2c5;
  int  AMatOffset_r3c1;
  int  AMatOffset_r3c3;
  int  AMatOffset_r3c4;
  int  AMatOffset_r3c5;
  int  AMatOffset_r4c0;
  int  AMatOffset_r4c1;
  int  AMatOffset_r4c3;
  int  AMatOffset_r4c4;
  int  AMatOffset_r4c5;
  int  AMatOffset_r4c6;
  int  AMatOffset_r5c1;
  int  AMatOffset_r5c2;
  int  AMatOffset_r5c3;
  int  AMatOffset_r5c4;
  int  AMatOffset_r5c5;
  int  AMatOffset_r5c6;
  int  AMatOffset_r6c6;
  double * f_matPosition_r0c0;
  double * f_matPosition_r0c4;
  double * f_matPosition_r1c1;
  double * f_matPosition_r1c3;
  double * f_matPosition_r1c4;
  double * f_matPosition_r1c5;
  double * f_matPosition_r1c6;
  double * f_matPosition_r2c2;
  double * f_matPosition_r2c5;
  double * f_matPosition_r3c1;
  double * f_matPosition_r3c3;
  double * f_matPosition_r3c4;
  double * f_matPosition_r3c5;
  double * f_matPosition_r4c0;
  double * f_matPosition_r4c1;
  double * f_matPosition_r4c3;
  double * f_matPosition_r4c4;
  double * f_matPosition_r4c5;
  double * f_matPosition_r4c6;
  double * f_matPosition_r5c1;
  double * f_matPosition_r5c2;
  double * f_matPosition_r5c3;
  double * f_matPosition_r5c4;
  double * f_matPosition_r5c5;
  double * f_matPosition_r5c6;
  double * f_matPosition_r6c6;
  double * q_matPosition_r0c0;
  double * q_matPosition_r0c4;
  double * q_matPosition_r1c1;
  double * q_matPosition_r1c3;
  double * q_matPosition_r1c4;
  double * q_matPosition_r1c5;
  double * q_matPosition_r1c6;
  double * q_matPosition_r2c2;
  double * q_matPosition_r2c5;
  double * q_matPosition_r3c1;
  double * q_matPosition_r3c3;
  double * q_matPosition_r3c4;
  double * q_matPosition_r3c5;
  double * q_matPosition_r4c0;
  double * q_matPosition_r4c1;
  double * q_matPosition_r4c3;
  double * q_matPosition_r4c4;
  double * q_matPosition_r4c5;
  double * q_matPosition_r4c6;
  double * q_matPosition_r5c1;
  double * q_matPosition_r5c2;
  double * q_matPosition_r5c3;
  double * q_matPosition_r5c4;
  double * q_matPosition_r5c5;
  double * q_matPosition_r5c6;
  double * q_matPosition_r6c6;
  double fRHS[7];
  double qRHS[7];
  double fMat_r0c0;
  double fMat_r0c4;
  double fMat_r1c1;
  double fMat_r1c3;
  double fMat_r1c4;
  double fMat_r1c5;
  double fMat_r1c6;
  double fMat_r2c2;
  double fMat_r2c5;
  double fMat_r3c1;
  double fMat_r3c3;
  double fMat_r3c4;
  double fMat_r3c5;
  double fMat_r4c0;
  double fMat_r4c1;
  double fMat_r4c3;
  double fMat_r4c4;
  double fMat_r4c5;
  double fMat_r4c6;
  double fMat_r5c1;
  double fMat_r5c2;
  double fMat_r5c3;
  double fMat_r5c4;
  double fMat_r5c5;
  double fMat_r5c6;
  double fMat_r6c6;
  double qMat_r0c0;
  double qMat_r0c4;
  double qMat_r1c1;
  double qMat_r1c3;
  double qMat_r1c4;
  double qMat_r1c5;
  double qMat_r1c6;
  double qMat_r2c2;
  double qMat_r2c5;
  double qMat_r3c1;
  double qMat_r3c3;
  double qMat_r3c4;
  double qMat_r3c5;
  double qMat_r4c0;
  double qMat_r4c1;
  double qMat_r4c3;
  double qMat_r4c4;
  double qMat_r4c5;
  double qMat_r4c6;
  double qMat_r5c1;
  double qMat_r5c2;
  double qMat_r5c3;
  double qMat_r5c4;
  double qMat_r5c5;
  double qMat_r5c6;
  double qMat_r6c6;
  static std::vector< std::vector<int> > jacStamp;
};


class Model : public DeviceModel
{
typedef std::vector<Instance *> InstanceVector;
friend class ParametricData<Model>;
friend class Instance;
friend class Traits;friend class Master;
public:
  Model(
     const Configuration &       configuration,
     const ModelBlock &        MB,
     const FactoryBlock &      factory_block);
  ~Model();
private:
  Model();
  Model(const Model &);
  Model &operator=(const Model &);
public:
  virtual void forEachInstance(DeviceInstanceOp &op) const /* override */;
  virtual std::ostream &printOutInstances(std::ostream &os) const;
  bool processParams ();
  bool processInstanceParams ();
  bool clearTemperatureData ();
public:
  void addInstance(Instance *instance) 
  {
    instanceContainer.push_back(instance);
  }

private:
  std::vector<Instance*> instanceContainer;

private:
  double SIGN;
  double TG;
  double TNOM;
  double SCALE;
  double QOFF;
  double XL;
  double XW;
  double NQS_NOI;
  double TH_NOI;
  double INFO_LEVEL;
  double AVTO;
  double AGAMMA;
  double AKP;
  double COX;
  double XJ;
  double VTO;
  double PHIF;
  double GAMMA;
  double GAMMAG;
  double N0;
  double VBI;
  double AQMA;
  double AQMI;
  double ETAQM;
  double KP;
  double E0;
  double E1;
  double ETA;
  double ZC;
  double THC;
  double LA;
  double LB;
  double KA;
  double KB;
  double WKP1;
  double WKP2;
  double WKP3;
  double DL;
  double DLC;
  double DW;
  double DWC;
  double LDW;
  double WDL;
  double LL;
  double LLN;
  double AVT;
  double LVT;
  double WVT;
  double AGAM;
  double LGAM;
  double WGAM;
  double NFVTA;
  double NFVTB;
  double UCRIT;
  double LAMBDA;
  double DELTA;
  double ACLM;
  double LR;
  double QLR;
  double NLR;
  double FLR;
  double LETA0;
  double LETA;
  double LETA2;
  double WETA;
  double NCS;
  double ETAD;
  double SIGMAD;
  double WR;
  double QWR;
  double NWR;
  double FPROUT;
  double PDITS;
  double PDITSL;
  double PDITSD;
  double DDITS;
  double IBA;
  double IBB;
  double IBN;
  double XB;
  double EB;
  double KG;
  double LOVIG;
  double AGIDL;
  double BGIDL;
  double CGIDL;
  double EGIDL;
  double KF;
  double AF;
  double EF;
  double KGFN;
  double LQWR;
  double LNWR;
  double LWR;
  double LDPHIEDGE;
  double WQLR;
  double WNLR;
  double WLR;
  double WUCRIT;
  double WLAMBDA;
  double WETAD;
  double WE0;
  double WE1;
  double WRLX;
  double WUCEX;
  double WDPHIEDGE;
  double WLDPHIEDGE;
  double WLDGAMMAEDGE;
  double WEDGE;
  double DGAMMAEDGE;
  double DPHIEDGE;
  double SAREF;
  double SBREF;
  double WLOD;
  double KKP;
  double LKKP;
  double WKKP;
  double PKKP;
  double TKKP;
  double LLODKKP;
  double WLODKKP;
  double KVTO;
  double LKVTO;
  double WKVTO;
  double PKVTO;
  double LLODKVTO;
  double WLODKVTO;
  double KGAMMA;
  double LODKGAMMA;
  double KETAD;
  double LODKETAD;
  double KUCRIT;
  double TETA;
  double TLAMBDA;
  double TCV;
  double BEX;
  double UCEX;
  double TE0EX;
  double TE1EX;
  double IBBT;
  double TCVL;
  double TCVW;
  double TCVWL;
  double GAMMAOV;
  double GAMMAGOV;
  double VFBOV;
  double LOV;
  double VOV;
  double CGSO;
  double CGDO;
  double CGBO;
  double KJF;
  double CJF;
  double VFR;
  double DFR;
  double HDIF;
  double RSH;
  double LDIF;
  double RS;
  double RD;
  double RLX;
  double RSX;
  double RDX;
  double TR;
  double TR2;
  double GMIN;
  double NJS;
  double XJBVS;
  double BVS;
  double JSS;
  double JSSWS;
  double JSSWGS;
  double JTSS;
  double JTSSWS;
  double JTSSWGS;
  double NJTSS;
  double NJTSSWS;
  double NJTSSWGS;
  double VTSS;
  double VTSSWS;
  double VTSSWGS;
  double CJS;
  double CJSWS;
  double CJSWGS;
  double PBS;
  double PBSWS;
  double PBSWGS;
  double MJS;
  double MJSWS;
  double MJSWGS;
  double XTIS;
  double XTSS;
  double XTSSWS;
  double XTSSWGS;
  double TNJTSS;
  double TNJTSSWS;
  double TNJTSSWGS;
  double TCJ;
  double TCJSW;
  double TCJSWG;
  double TPB;
  double TPBSW;
  double TPBSWG;
  double NJD;
  double XJBVD;
  double BVD;
  double JSD;
  double JSSWD;
  double JSSWGD;
  double JTSD;
  double JTSSWD;
  double JTSSWGD;
  double NJTSD;
  double NJTSSWD;
  double NJTSSWGD;
  double VTSD;
  double VTSSWD;
  double VTSSWGD;
  double CJD;
  double CJSWD;
  double CJSWGD;
  double PBD;
  double PBSWD;
  double PBSWGD;
  double MJD;
  double MJSWD;
  double MJSWGD;
  double XTID;
  double XTSD;
  double XTSSWD;
  double XTSSWGD;
  double TNJTSD;
  double TNJTSSWD;
  double TNJTSSWGD;
  double RGSH;
  double GC;
  double KRGL1;
  double RDSBSH;
  double RBWSH;
  double RBN;
  double RSBWSH;
  double RSBN;
  double RDBWSH;
  double RDBN;
  double RINGTYPE;
  bool my_dummy;
};


class Master : public DeviceMaster<Traits>
{
  friend class SizeDependParam;
public:
  Master(
     const Configuration &       configuration,
     const FactoryBlock &      factory_block,
     const SolverState & ss1,
     const DeviceOptions & do1)
    : DeviceMaster<Traits>(configuration, factory_block, ss1, do1)
  {}
  virtual bool updateState (double * solVec, double * staVec, double * stoVec);
  virtual bool loadDAEVectors (double * solVec, double * fVec, double * qVec, double * bVec, double * leadF, double * leadQ, double * junctionV);
  virtual bool loadDAEMatrices (Linear::Matrix & dFdx, Linear::Matrix & dQdx);

};
void registerDevice();

}
}
}

extern "C"{
void registerDevice();
}

#endif
