#ifndef verilog_ams_src_test3_H_
#define verilog_ams_src_test3_H_
/////////////////////////////////////////////////////////////////////////////////////////////////////
/// Generated by VA-C-Generator. DO NOT EDIT!
/// @author vaParser
/////////////////////////////////////////////////////////////////////////////////////////////////////

// ----------   Standard Includes   ----------
#include <N_DEV_Configuration.h>
#include <map>
#include <N_DEV_DeviceMaster.h>
#include <N_DEV_DeviceInstance.h>
#include <N_DEV_DeviceModel.h>
#include <N_DEV_DeviceBlock.h>
namespace Xyce {
namespace Device {
namespace ADMS_Device {
class Model;
class Instance;

struct Traits : public DeviceTraits<Model, Instance>
{
static const char *name() {return  "AHDL Model";}
static const char *deviceTypeName() {return "AHDL level 1";}
static int numNodes() {return 2;}
static bool modelRequired() {return false;}
static bool isLinearDevice() {return false;}

static Device *factory(const Configuration &configuration, const FactoryBlock &factory_block);
static void loadModelParameters(ParametricData<Model> &model_parameters);
static void loadInstanceParameters(ParametricData<Instance> &instance_parameters);
};

class Instance : public DeviceInstance
{
friend class SizeDependParam;
friend class ParametricData<Instance>;
friend class Model;
friend class Traits;friend class Master;

// functions
public:

Instance(
const Configuration &       configuration,
const InstanceBlock &     IB,
Model &                   Miter,
const FactoryBlock &      factory_block);

~Instance();

private:
Instance(const Instance &);
Instance &operator=(const Instance &);

public:
void registerLIDs( const std::vector<int> & intLIDVecRef,
const std::vector<int> & extLIDVecRef );
void registerStateLIDs( const std::vector<int> & staLIDVecRef);
void registerStoreLIDs( const std::vector<int> & stoLIDVecRef);
virtual void registerBranchDataLIDs(const std::vector<int> & branchLIDVecRef);
void loadNodeSymbols(Util::SymbolTable &symbol_table) const; // override
const std::vector< std::vector<int> > & jacobianStamp() const;
void registerJacLIDs( const std::vector< std::vector<int> > & jacLIDVec );
bool processParams ();
bool updateTemperature(const double & temp_tmp);
bool updateIntermediateVars_RHS();
bool updateIntermediateVars_Jac();
bool updateIntermediateVars ();
bool updatePrimaryState ();
bool loadDAEQVector ();
bool loadDAEFVector ();
bool auxChargeCalculations ();
bool setupCapacitors_newDAE ();
bool setupCapacitors_oldDAE ();
bool loadDAEdQdx ();
bool loadDAEdFdx ();
void setupPointers ();
public:
// Getters and setters
Model &getModel() 
{
return model_;
}

private:

  Model &       model_;         ///< Owning model
  double temp;
  int p;
  int n;
  double fRHS[2];
  double qRHS[2];
  static std::vector< std::vector<int> > jacStamp;
};


class Model : public DeviceModel
{
typedef std::vector<Instance *> InstanceVector;
friend class ParametricData<Model>;
friend class Instance;
friend class Traits;friend class Master;
public:
  Model(
     const Configuration &       configuration,
     const ModelBlock &        MB,
     const FactoryBlock &      factory_block);
  ~Model();
private:
  Model();
  Model(const Model &);
  Model &operator=(const Model &);
public:
  virtual void forEachInstance(DeviceInstanceOp &op) const /* override */;
  virtual std::ostream &printOutInstances(std::ostream &os) const;
  bool processParams ();
  bool processInstanceParams ();
  bool clearTemperatureData ();
public:
  void addInstance(Instance *instance) 
  {
    instanceContainer.push_back(instance);
  }

private:
  std::vector<Instance*> instanceContainer;

private:
  double INFO_LEVEL;
  double TT;
  bool my_dummy;
};


class Master : public DeviceMaster<Traits>
{
  friend class SizeDependParam;
public:
  Master(
     const Configuration &       configuration,
     const FactoryBlock &      factory_block,
     const SolverState & ss1,
     const DeviceOptions & do1)
    : DeviceMaster<Traits>(configuration, factory_block, ss1, do1)
  {}
  virtual bool updateState (double * solVec, double * staVec, double * stoVec);
  virtual bool loadDAEVectors (double * solVec, double * fVec, double * qVec, double * bVec, double * leadF, double * leadQ, double * junctionV);
  virtual bool loadDAEMatrices (Linear::Matrix & dFdx, Linear::Matrix & dQdx);

};
void registerDevice();

}
}
}

extern "C"{
void registerDevice();
}

#endif
