"""
Design Compiler Adapter — logic synthesis stage.

Modular architecture: each feature section is a separate generator function,
controlled by config flags in SynthesisConfig. The YAML config file drives
which sections are included in the generated TCL script.

Industrial features:
- DC-T physical awareness (TLU+, floorplan, DEF)
- Multi-Corner Multi-Mode (MCMM)
- Multi-VT library with VT percentage constraints
- Power optimization (leakage, dynamic, clock gating)
- Timing derate (OCV)
- Path groups (C-O, D-L, D-O, reg2reg, reg2icg)
- Congestion optimization
- DFT / Scan insertion
- SVF / ECO support
- Hierarchy management
- Non-Default Routing Rules (NDR)
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from ..db.design_state import (
    DesignState, FlowStage, StageResult, StageStatus,
    SynthesisConfig, LibraryConfig, TimingDerateConfig,
)
from .base import ToolAdapter

logger = logging.getLogger("ic_backend")


class DCAdapter(ToolAdapter):
    tool_name = "DesignCompiler"
    stage = FlowStage.SYNTHESIS
    env_script = "/share/apps/EDAs/syn22.bash"
    tool_family = "dc"

    def _get_shell_cmd(self) -> str:
        return "dc_shell -no_gui -no_log"

    def setup_work_dir(self, stage_name: str = "synthesis") -> Path:
        root = super().setup_work_dir(stage_name)
        (root / "DC" / "out").mkdir(parents=True, exist_ok=True)
        (root / "DC" / "report").mkdir(parents=True, exist_ok=True)
        return root

    # =========================================================================
    # Script generation — orchestrates all modular sections
    # =========================================================================
    def generate_script(self) -> str:
        cfg = self.state.config
        syn = cfg.synthesis
        sections: list[list[str]] = []

        sections.append(self._gen_header())
        sections.append(self._gen_host_options())
        sections.append(self._gen_variables())
        sections.append(self._gen_svf())
        sections.append(self._gen_libraries())
        sections.append(self._gen_timing_settings())
        sections.append(self._gen_read_rtl())
        sections.append(self._gen_sdc_constraints())
        sections.append(self._gen_timing_derate())
        sections.append(self._gen_physical_constraints())
        sections.append(self._gen_mcmm())
        sections.append(self._gen_power_optimization())
        sections.append(self._gen_clock_gating())
        sections.append(self._gen_hierarchy_management())
        sections.append(self._gen_vt_control())
        sections.append(self._gen_congestion())
        sections.append(self._gen_dft_scan())
        sections.append(self._gen_design_rules())
        sections.append(self._gen_compile_command())
        sections.append(self._gen_post_compile())
        sections.append(self._gen_reports())
        sections.append(self._gen_write_outputs())
        sections.append(["exit"])

        # Filter empty sections and join
        all_lines: list[str] = []
        for sec in sections:
            if sec:
                all_lines.extend(sec)
                all_lines.append("")

        return "\n".join(all_lines)

    # =========================================================================
    # Modular generator functions — each produces one TCL section
    # =========================================================================

    def _gen_header(self) -> list[str]:
        """Script header with design info."""
        cfg = self.state.config
        return [
            f"# Auto-generated DC synthesis script",
            f"# Design: {cfg.design_name}",
            f"# Top module: {cfg.top_module}",
            f"# Generated by IC Backend Framework",
            "",
        ]

    def _gen_host_options(self) -> list[str]:
        """Host options (parallel cores)."""
        return [
            "# ---- Host Options ----",
            f"set_host_options -max_cores {self.state.config.synthesis.num_cores}",
        ]

    def _gen_variables(self) -> list[str]:
        """Design variables."""
        cfg = self.state.config
        return [
            "# ---- Design Variables ----",
            f'set DESIGN_NAME "{cfg.design_name}"',
            f'set TOP_MODULE "{cfg.top_module}"',
            f'set CLOCK_PERIOD {cfg.clock_period_ns}',
            f'set CLOCK_NAME "{cfg.clock_name}"',
        ]

    def _gen_svf(self) -> list[str]:
        """SVF file for ECO support."""
        if not self.state.config.synthesis.svf_enabled:
            return []
        cfg = self.state.config
        return [
            "# ---- SVF (for ECO support) ----",
            'set_svf ${DESIGN_NAME}.svf',
        ]

    def _gen_libraries(self) -> list[str]:
        """Library setup with multi-VT support."""
        cfg = self.state.config
        libs = cfg.libraries
        lines = ["# ---- Libraries ----"]

        # Search path
        search_dirs = set()
        for p in libs.std_cell_libs + libs.io_libs + libs.macro_libs:
            search_dirs.add(str(Path(p).parent))
        if search_dirs:
            lines.append(f'set search_path [concat $search_path [list {" ".join(sorted(search_dirs))}]]')

        # Target library
        lib_names = " ".join(Path(p).name for p in libs.std_cell_libs)
        lines.append(f'set target_library [list {lib_names}]')

        # IO and macro libraries
        if libs.io_libs:
            io_names = " ".join(Path(p).name for p in libs.io_libs)
            lines.append(f'set io_library [list {io_names}]')
        if libs.macro_libs:
            macro_names = " ".join(Path(p).name for p in libs.macro_libs)
            lines.append(f'set macro_library [list {macro_names}]')

        # Link library
        link_parts = ["*"] + [Path(p).name for p in libs.std_cell_libs]
        if libs.io_libs:
            link_parts.append("$io_library")
        if libs.macro_libs:
            link_parts.append("$macro_library")
        lines.append(f'set link_library   [concat {" ".join(link_parts)}]')
        lines.append(f'set symbol_library [list]')

        # Multi-VT
        if libs.vt_libs:
            lines.append("")
            lines.append("# ---- Multi-VT Libraries ----")
            for vt_name, vt_libs in libs.vt_libs.items():
                vt_names = " ".join(Path(p).name for p in vt_libs)
                lines.append(f'set {vt_name}_libs [list {vt_names}]')
                lines.append(f'set link_library [concat $link_library ${vt_name}_libs]')

        # Dont-use cells
        if libs.dont_use_cells:
            lines.append("")
            lines.append("# ---- Dont-Use Cells ----")
            lines.append("set dont_use_list [list]")
            for pattern in libs.dont_use_cells:
                lines.append(f'append_to_collection dont_use_list [get_lib_cells "*/{pattern}"]')
            lines.append("set_dont_use $dont_use_list")

        return lines

    def _gen_timing_settings(self) -> list[str]:
        """Timing-related app_var settings."""
        return [
            "# ---- Timing Settings ----",
            "set_app_var timing_enable_multiple_clocks_per_reg true",
            "set_app_var timing_separate_clock_gating_group true",
            "set_app_var timing_use_enhanced_capacitance_modeling true",
            "set_app_var timing_remove_clock_reconvergence_pessimism true",
            "set_app_var case_analysis_with_logic_constants true",
        ]

    def _gen_read_rtl(self) -> list[str]:
        """Read RTL sources (filelist, directory, or explicit files)."""
        cfg = self.state.config
        lines = ["# ---- Read RTL ----"]

        if cfg.rtl_filelist:
            lines.extend([
                f'# Using filelist: {cfg.rtl_filelist}',
                f'set RTL_FILELIST "{cfg.rtl_filelist}"',
                'set fh [open $RTL_FILELIST r]',
                'while {[gets $fh line] >= 0} {',
                '    set line [string trim $line]',
                '    if {$line == "" || [string index $line 0] == "#"} { continue }',
                '    if {[string match "*.v" $line] || [string match "*.sv" $line]} {',
                '        read_verilog $line',
                '    } elseif {[string match "*.vhd" $line] || [string match "*.vhdl" $line]} {',
                '        read_vhdl $line',
                '    }',
                '}',
                'close $fh',
            ])
        elif cfg.rtl_dir:
            lines.extend([
                f'# Using RTL directory: {cfg.rtl_dir}',
                f'set RTL_DIR "{cfg.rtl_dir}"',
                'foreach f [glob -nocomplain $RTL_DIR/*.v $RTL_DIR/*.sv] {',
                '    read_verilog $f',
                '}',
                'foreach f [glob -nocomplain $RTL_DIR/*.vhd $RTL_DIR/*.vhdl] {',
                '    read_vhdl $f',
                '}',
            ])
        else:
            for rtl in cfg.rtl_files:
                if rtl.endswith(".v") or rtl.endswith(".sv"):
                    lines.append(f'read_verilog "{rtl}"')
                elif rtl.endswith(".vhd") or rtl.endswith(".vhdl"):
                    lines.append(f'read_vhdl "{rtl}"')

        lines.extend([
            "current_design $TOP_MODULE",
            "link",
            "uniquify",
        ])
        return lines

    def _gen_sdc_constraints(self) -> list[str]:
        """SDC timing constraints."""
        cfg = self.state.config
        lines = ["# ---- Timing Constraints ----"]

        if cfg.sdc_file and Path(cfg.sdc_file).exists():
            lines.append(f'source "{cfg.sdc_file}"')
        elif cfg.sdc_file:
            lines.append(f'source "{cfg.sdc_file}"')
        else:
            # Generate from clock definitions
            for clk in cfg.clocks:
                lines.append(f"# Clock: {clk.name}")
                port = clk.pin_or_port or cfg.clock_name
                lines.append(f"create_clock -name {clk.name} -period {clk.period_ns} [get_ports {port}]")
                lines.append(f"set_clock_uncertainty -setup {clk.setup_uncertainty_ns} [get_clocks {clk.name}]")
                lines.append(f"set_clock_uncertainty -hold {clk.hold_uncertainty_ns} [get_clocks {clk.name}]")
                lines.append(f"set_clock_transition {clk.transition_ns} [get_clocks {clk.name}]")
                lines.append("")

            # I/O delays
            lines.extend([
                "# ---- I/O Delays ----",
                f"set_input_delay -clock $CLOCK_NAME -max 3.0 [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]",
                f"set_input_delay -clock $CLOCK_NAME -min 1.0 [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]",
                f"set_output_delay -clock $CLOCK_NAME -max 3.0 [all_outputs]",
                f"set_output_delay -clock $CLOCK_NAME -min 1.0 [all_outputs]",
            ])

            # Driving cell
            if cfg.libraries.driver_cell:
                lines.append(
                    f'set_driving_cell -lib_cell "{cfg.libraries.driver_cell}" -pin Z '
                    f'[remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]'
                )

            lines.append("set_load 0.05 [all_outputs]")

        return lines

    def _gen_timing_derate(self) -> list[str]:
        """Timing derate (OCV)."""
        d = self.state.config.timing_derate
        if d.late_factor == 1.0 and d.early_factor == 1.0:
            return []
        lines = ["# ---- Timing Derate (OCV) ----"]
        if d.late_factor != 1.0:
            lines.append(f"set_timing_derate {d.late_factor} -late")
        if d.early_factor != 1.0:
            lines.append(f"set_timing_derate {d.early_factor} -early")
        return lines

    def _gen_physical_constraints(self) -> list[str]:
        """DC-T physical awareness: TLU+, floorplan, DEF."""
        syn = self.state.config.synthesis
        if not syn.topographical_mode:
            return []

        lines = ["# ---- Physical Constraints (DC-T) ----"]

        if syn.tlu_plus_file:
            lines.append(f'set_tlu_plus_files -max_tluplus "{syn.tlu_plus_file}"')
            if syn.tech2itf_map:
                lines[-1] += f' -tech2itf_map "{syn.tech2itf_map}"'

        if syn.floorplan_file:
            lines.append(f'read_floorplan "{syn.floorplan_file}"')
        elif syn.def_file:
            lines.append(f'extract_physical_constraints "{syn.def_file}"')

        if syn.physical_constraints_file:
            lines.append(f'source "{syn.physical_constraints_file}"')

        if syn.dc_obs_file:
            lines.append(f'source "{syn.dc_obs_file}"')

        return lines

    def _gen_mcmm(self) -> list[str]:
        """Multi-Corner Multi-Mode scenarios."""
        syn = self.state.config.synthesis
        if not syn.mcmm_enabled or not syn.mcmm_scenarios:
            return []

        lines = ["# ---- MCMM Scenarios ----"]
        for sc in syn.mcmm_scenarios:
            lines.append(f"# Scenario: {sc.name}")
            lines.append(f"create_scenario {sc.name}")
            if sc.operating_condition:
                lines.append(
                    f'set_operating_conditions {sc.operating_condition} '
                    f'-analysis_type {sc.analysis_type}'
                )
            if sc.tlu_plus_file:
                lines.append(f'set_tlu_plus_files -max_tluplus "{sc.tlu_plus_file}"')
            lines.append(
                f'set_scenario_options -scenarios {sc.name} '
                f'-setup {"true" if sc.setup else "false"} '
                f'-hold {"true" if sc.hold else "false"}'
            )
            if sc.sdc_file:
                lines.append(f'source "{sc.sdc_file}"')
            elif sc.clock_file:
                lines.append(f'source "{sc.clock_file}"')
            lines.append("")

        if syn.mcmm_default_scenario:
            lines.append(f"current_scenario {syn.mcmm_default_scenario}")
            active = " ".join(s.name for s in syn.mcmm_scenarios)
            lines.append(f"set_active_scenarios [list {active}]")

        return lines

    def _gen_power_optimization(self) -> list[str]:
        """Power optimization settings."""
        syn = self.state.config.synthesis
        if not syn.power_optimization:
            return []

        lines = ["# ---- Power Optimization ----"]
        if syn.leakage_optimization:
            lines.append("set_leakage_optimization true")
        if syn.dynamic_optimization:
            lines.append("set_dynamic_optimization true")
        if syn.power_prediction and syn.topographical_mode:
            lines.append("set_power_prediction true")

        return lines

    def _gen_clock_gating(self) -> list[str]:
        """Clock gating configuration."""
        syn = self.state.config.synthesis
        if not syn.clock_gating and not syn.self_gating:
            return []

        lines = ["# ---- Clock Gating ----"]
        if syn.clock_gating:
            edge = "positive_edge_logic" if syn.clock_gating_positive_edge else "negative_edge_logic"
            lines.append(
                f'set_clock_gating_style -{edge} {syn.clock_gating_style} '
                f'-control_point {syn.clock_gating_control_point}'
            )
        return lines

    def _gen_hierarchy_management(self) -> list[str]:
        """Hierarchy control: keep, flatten, size_only."""
        syn = self.state.config.synthesis
        if not syn.keep_hierarchies and not syn.size_only_patterns and not syn.flatten_all:
            return []

        lines = ["# ---- Hierarchy Management ----"]

        for hier in syn.keep_hierarchies:
            lines.append(f'set_boundary_optimization [get_cells {hier}] false')

        for pattern in syn.size_only_patterns:
            lines.append(f'# Preserve structure for: {pattern}')
            lines.append(f'foreach_in_collection c [get_cells -hier -filter {{ref_name=~*{pattern}*}}] {{')
            lines.append(f'    set_size_only [get_cells [get_attribute $c full_name]]')
            lines.append(f'}}')

        return lines

    def _gen_vt_control(self) -> list[str]:
        """VT library control: dont_use and release patterns."""
        syn = self.state.config.synthesis
        if not syn.vt_dont_use_patterns and not syn.vt_release_patterns:
            return []

        lines = ["# ---- VT Control ----"]

        # Build dont_use cell list
        lines.append("set dont_use_cell_list [list]")
        for vt_name, patterns in syn.vt_dont_use_patterns.items():
            for pattern in patterns:
                lines.append(
                    f'append_to_collection -unique dont_use_cell_list '
                    f'[get_lib_cells -regexp "{pattern}"]'
                )

        # Release patterns
        if syn.vt_release_patterns:
            for vt_name, patterns in syn.vt_release_patterns.items():
                for pattern in patterns:
                    lines.append(
                        f'set dont_use_cell_list '
                        f'[remove_from_collection $dont_use_cell_list '
                        f'[get_lib_cells -regexp "{pattern}"]]'
                    )

        lines.append("set_dont_use $dont_use_cell_list")
        return lines

    def _gen_congestion(self) -> list[str]:
        """Congestion optimization."""
        if not self.state.config.synthesis.congestion_optimization:
            return []
        return [
            "# ---- Congestion Optimization ----",
            "set_congestion_optimization [current_design] true",
        ]

    def _gen_dft_scan(self) -> list[str]:
        """DFT / Scan insertion."""
        syn = self.state.config.synthesis
        if not syn.scan_insertion:
            return []

        lines = ["# ---- DFT / Scan ----"]
        lines.append(f'set_scan_configuration -style {syn.scan_style}')
        return lines

    def _gen_design_rules(self) -> list[str]:
        """Design rule constraints."""
        syn = self.state.config.synthesis
        lines = ["# ---- Design Rules ----"]
        lines.append(f"set_max_fanout {syn.max_fanout_dc} [current_design]")
        lines.append(f"set_max_transition {syn.max_transition_dc} [current_design]")
        lines.append(f"set_max_capacitance {syn.max_capacitance_dc} [current_design]")
        return lines

    def _gen_compile_command(self) -> list[str]:
        """Build and emit the compile_ultra command with all flags."""
        syn = self.state.config.synthesis
        lines = ["# ---- Compile ----"]

        cmd = "compile_ultra"
        if syn.no_autoungroup:
            cmd += " -no_autoungroup"
        if syn.clock_gating:
            cmd += " -gate_clock"
        if syn.self_gating:
            cmd += " -self_gating"
        if syn.scan_insertion:
            cmd += " -scan"
        if syn.congestion_optimization:
            cmd += " -congestion"
        if syn.timing_high_effort:
            cmd += " -timing_high_effort_script"

        lines.append(cmd)

        # NDR constraints
        if syn.ndr_constraints_file:
            lines.append(f'source "{syn.ndr_constraints_file}"')
        if syn.compile_constraints_file:
            lines.append(f'source "{syn.compile_constraints_file}"')

        return lines

    def _gen_post_compile(self) -> list[str]:
        """Post-compile: hierarchy flattening, optimization, name rules."""
        syn = self.state.config.synthesis
        lines = []

        # Flatten if requested
        if syn.flatten_all:
            lines.append("# ---- Post-Compile: Flatten ----")
            for hier in syn.keep_hierarchies:
                lines.append(f'set_dont_touch [get_cells {hier}]')
            lines.append("ungroup -flatten -all")
            for hier in syn.keep_hierarchies:
                lines.append(f'remove_attribute [get_cells {hier}] dont_touch')
                lines.append(f'ungroup -flatten -start_level {syn.flatten_start_level} [get_cells {hier}]')

        # Name rules
        lines.append("define_name_rules verilog -target_bus_naming_style {%s[%d]} -case_insensitive")
        lines.append("change_names -rules verilog -hierarchy")

        # Additional constraints
        if syn.place_constraints_file:
            lines.append(f'source "{syn.place_constraints_file}"')

        # Port buffers
        if syn.insert_port_buffers:
            lines.append("# ---- Port Buffers ----")
            for buf in syn.insert_port_buffers:
                lines.append(f'insert_buffer [get_ports {buf}] {buf}_buf')

        return lines

    def _gen_reports(self) -> list[str]:
        """Generate all report commands."""
        return [
            "# ---- Reports ----",
            "report_qor -significant_digits 4 > ./DC/report/qor.rpt",
            "report_timing -max_paths 100 -significant_digits 4 -nworst 1 -delay max -sort_by slack > ./DC/report/timing_setup.rpt",
            "report_timing -max_paths 100 -significant_digits 4 -nworst 1 -delay min -sort_by slack > ./DC/report/timing_hold.rpt",
            "report_area -hierarchy -nosplit > ./DC/report/area.rpt",
            "report_power -nosplit -hierarchy -hier_level 1 > ./DC/report/power.rpt",
            "report_constraint -all_violators -significant_digits 4 > ./DC/report/constraint.rpt",
            "report_cell > ./DC/report/cell.rpt",
            "report_threshold_voltage_group > ./DC/report/vt_group.rpt",
            "report_clock > ./DC/report/clock.rpt",
            "report_timing_derate > ./DC/report/derate.rpt",
            "check_design > ./DC/report/check_design.rpt",
            "check_timing > ./DC/report/check_timing.rpt",
        ]

    def _gen_write_outputs(self) -> list[str]:
        """Write output files."""
        lines = [
            "# ---- Write Outputs ----",
            "write -format verilog -hierarchy -output ./DC/out/${DESIGN_NAME}.v",
            "write -format ddc -hierarchy -output ./DC/out/${DESIGN_NAME}.ddc",
            "write_sdc -nosplit ./DC/out/${DESIGN_NAME}.sdc",
        ]
        if self.state.config.synthesis.svf_enabled:
            lines.append("set_svf -off")
        return lines

    # =========================================================================
    # Result parsing
    # =========================================================================
    def parse_results(self) -> None:
        result = self.state.get_stage_result(FlowStage.SYNTHESIS)
        if self.work_dir is None:
            return

        rpt_dir = self.work_dir / "DC" / "report"
        if not rpt_dir.exists():
            rpt_dir = self.work_dir / "rpt"

        qor_file = rpt_dir / "qor.rpt"
        if qor_file.exists():
            self._parse_qor(qor_file.read_text(), result)

        tim_file = rpt_dir / "timing_setup.rpt"
        if tim_file.exists():
            self._parse_timing(tim_file.read_text(), result)

        area_file = rpt_dir / "area.rpt"
        if area_file.exists():
            self._parse_area(area_file.read_text(), result)

        power_file = rpt_dir / "power.rpt"
        if power_file.exists():
            self._parse_power(power_file.read_text(), result)

        out_dir = self.work_dir / "DC" / "out"
        if not out_dir.exists():
            out_dir = self.work_dir / "out"
        for suffix in ["v", "ddc", "sdc"]:
            fpath = out_dir / f"{self.state.config.design_name}.{suffix}"
            if fpath.exists():
                self.state.record_artifact(f"syn_{suffix}", str(fpath))
                result.output_files[suffix] = str(fpath)

    def _parse_qor(self, text: str, result: StageResult):
        m = re.search(r'timing\s+([-.\d]+)\s+([-.\d]+)', text)
        if m:
            result.timing.wns = float(m.group(1))
            result.timing.tns = float(m.group(2))
        m = re.search(r'area\s+([-.\d]+)', text)
        if m:
            result.area.cell_area = float(m.group(1))
        m = re.search(r'Number of cells:\s+(\d+)', text)
        if m:
            result.area.num_std_cells = int(m.group(1))

    def _parse_timing(self, text: str, result: StageResult):
        m = re.search(r'slack\s+\((\w+)\)\s+([-.\d]+)', text)
        if m:
            slack_val = float(m.group(2))
            if result.timing.wns is None or slack_val < (result.timing.wns or 0):
                result.timing.wns = slack_val
        violations = len(re.findall(r'slack\s+\(\w+\)\s+([-.\d]+)', text))
        if violations > 0:
            neg_paths = sum(1 for m2 in re.finditer(
                r'slack\s+\(\w+)\)\s+([-.\d]+)', text
            ) if float(m2.group(1)) < 0)
            result.timing.num_violating_paths = neg_paths

    def _parse_area(self, text: str, result: StageResult):
        m = re.search(r'Total cell area:\s+([-.\d]+)', text)
        if m:
            result.area.cell_area = float(m.group(1))
        m = re.search(r'Total area:\s+([-.\d]+)', text)
        if m:
            result.area.total_area = float(m.group(1))
        seq_count = 0
        comb_count = 0
        for line in text.splitlines():
            if re.match(r'\s*(Combinational|Sequential) cell count:', line):
                nums = re.findall(r'(\d+)', line)
                if 'Combinational' in line and nums:
                    comb_count = int(nums[0])
                elif 'Sequential' in line and nums:
                    seq_count = int(nums[0])
        if comb_count or seq_count:
            result.area.num_std_cells = comb_count + seq_count

    def _parse_power(self, text: str, result: StageResult):
        m = re.search(r'Total\s+([-.\d]+)\s+([-.\d]+)\s+([-.\d]+)\s+([-.\d]+)', text)
        if m:
            result.power.leakage_power_mw = float(m.group(1)) * 1000
            result.power.dynamic_power_mw = float(m.group(2)) * 1000
            result.power.short_circuit_power_mw = float(m.group(3)) * 1000
            result.power.total_power_mw = float(m.group(4)) * 1000
