"""
Design Compiler Adapter — logic synthesis stage.

Industrial features:
- Multi-VT library support with VT percentage constraints
- Timing derate (OCV)
- Path groups (C-O, D-L, D-O, reg2reg, reg2icg)
- Power optimization (physically-aware clock gating)
- Critical range
- Advanced delay calculation (AWE, Arnoldi)
"""
from __future__ import annotations

import logging
import re
import time
from pathlib import Path
from typing import Any

from ..db.design_state import (
    DesignState, FlowStage, StageResult, StageStatus,
    TimingMetrics, AreaMetrics, PowerMetrics,
)
from .base import ToolAdapter

logger = logging.getLogger("ic_backend")


class DCAdapter(ToolAdapter):
    tool_name = "DesignCompiler"
    stage = FlowStage.SYNTHESIS
    env_script = "/share/apps/EDAs/syn22.bash"

    def _get_shell_cmd(self) -> str:
        return "dc_shell -no_gui -no_log"

    def setup_work_dir(self, stage_name: str = "synthesis") -> Path:
        root = super().setup_work_dir(stage_name)
        (root / "DC" / "out").mkdir(parents=True, exist_ok=True)
        (root / "DC" / "report").mkdir(parents=True, exist_ok=True)
        return root

    def generate_script(self) -> str:
        cfg = self.state.config
        lines = []

        lines.append(f"# Auto-generated DC synthesis script")
        lines.append(f"# Design: {cfg.design_name}")
        lines.append(f"# Generated by IC Backend MVP")
        lines.append("")

        # ---- Settings ----
        lines.append(f'set DESIGN_NAME "{cfg.design_name}"')
        lines.append(f'set TOP_MODULE "{cfg.top_module}"')
        lines.append(f'set CLOCK_PERIOD {cfg.clock_period_ns}')
        lines.append(f'set CLOCK_NAME "{cfg.clock_name}"')
        lines.append("")

        # ---- Host options ----
        lines.append("# ---- Host Options ----")
        lines.append(f'set_host_options -max_cores {cfg.synthesis.num_cores}')
        lines.append("")

        # ---- Libraries ----
        lines.append("# ---- Libraries ----")
        std_libs = " ".join(cfg.libraries.std_cell_libs)
        lines.append(f'set search_path [concat $search_path [list {" ".join(str(Path(p).parent) for p in cfg.libraries.std_cell_libs)}]]')
        lib_names = " ".join(Path(p).name for p in cfg.libraries.std_cell_libs)
        lines.append(f'set target_library [list {lib_names}]')
        lines.append(f'set link_library   [concat * $target_library]')
        lines.append(f'set symbol_library [list]')
        lines.append("")

        # Multi-VT support
        if cfg.libraries.vt_libs:
            lines.append("# ---- Multi-VT Libraries ----")
            for vt_name, vt_libs in cfg.libraries.vt_libs.items():
                vt_lib_names = " ".join(Path(p).name for p in vt_libs)
                lines.append(f'set {vt_name}_libs [list {vt_lib_names}]')
                lines.append(f'set link_library [concat $link_library ${vt_name}_libs]')
            lines.append("")

        # ---- Read RTL ----
        lines.append("# ---- Read RTL ----")
        for rtl in cfg.rtl_files:
            if rtl.endswith(".v") or rtl.endswith(".sv"):
                lines.append(f'read_verilog "{rtl}"')
            elif rtl.endswith(".vhd") or rtl.endswith(".vhdl"):
                lines.append(f'read_vhdl "{rtl}"')
        lines.append(f'current_design $TOP_MODULE')
        lines.append("link")
        lines.append("uniquify")
        lines.append("")

        # ---- Timing app_var settings ----
        lines.append("# ---- Timing Settings ----")
        lines.append('set_app_var timing_enable_multiple_clocks_per_reg true')
        lines.append('set_app_var timing_separate_clock_gating_group true')
        lines.append('set_app_var timing_use_enhanced_capacitance_modeling true')
        lines.append('set_app_var timing_remove_clock_reconvergence_pessimism true')
        lines.append('set_app_var timing_crpr_threshold_ps 1.0')
        lines.append('set_app_var case_analysis_with_logic_constants true')
        lines.append("")

        # ---- Constraints ----
        lines.append("# ---- Constraints ----")
        if cfg.sdc_file and Path(cfg.sdc_file).exists():
            lines.append(f'source "{cfg.sdc_file}"')
        else:
            # Create clocks from config
            for clk in cfg.clocks:
                lines.append(f'# Clock: {clk.name}')
                if clk.pin_or_port:
                    lines.append(f'create_clock -name {clk.name} -period {clk.period_ns} [get_ports {clk.pin_or_port}]')
                else:
                    lines.append(f'create_clock -name {clk.name} -period {clk.period_ns} [get_ports $CLOCK_NAME]')
                lines.append(f'set_clock_uncertainty -setup {clk.setup_uncertainty_ns} [get_clocks {clk.name}]')
                lines.append(f'set_clock_uncertainty -hold {clk.hold_uncertainty_ns} [get_clocks {clk.name}]')
                lines.append(f'set_clock_transition {clk.transition_ns} [get_clocks {clk.name}]')
                lines.append(f'set_ideal_network [all_fanout -flat -from [get_attribute [get_clocks {clk.name}] sources]]')
                lines.append("")

            # Input/output delays
            lines.append('# Input/Output delays')
            lines.append(f'set_input_delay -clock $CLOCK_NAME -max [expr $CLOCK_PERIOD * 0.3] [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]')
            lines.append(f'set_input_delay -clock $CLOCK_NAME -min [expr $CLOCK_PERIOD * 0.1] [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]')
            lines.append(f'set_input_transition 0.1 [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]')
            lines.append(f'set_output_delay -clock $CLOCK_NAME -max [expr $CLOCK_PERIOD * 0.3] [all_outputs]')
            lines.append(f'set_output_delay -clock $CLOCK_NAME -min [expr $CLOCK_PERIOD * 0.1] [all_outputs]')
            lines.append("")

            # Driving cell and load
            if cfg.libraries.driver_cell:
                lines.append(f'# Driving cell')
                lines.append(f'set_driving_cell -no_design_rule -lib_cell {cfg.libraries.driver_cell} -pin Z [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]')
            else:
                lines.append(f'set_driving_cell -lib_cell BUFFD2BWP30P140 -pin Z [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]')
            lines.append(f'set_load 0.1 [all_outputs]')
            lines.append("")

            # Path groups
            lines.append('# Path groups')
            lines.append('group_path -name C-O -to [all_outputs]')
            lines.append('group_path -name D-L -from [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]]')
            lines.append('group_path -name D-O -from [remove_from_collection [all_inputs] [get_ports $CLOCK_NAME]] -to [all_outputs]')
            lines.append("")

        # ---- Design rules ----
        lines.append("# ---- Design Rules ----")
        lines.append(f'set_max_transition {cfg.synthesis.max_transition_dc} [current_design]')
        lines.append(f'set_max_fanout {cfg.synthesis.max_fanout_dc} [current_design]')
        if cfg.synthesis.critical_range_ns > 0:
            lines.append(f'set_critical_range {cfg.synthesis.critical_range_ns} [current_design]')
        lines.append("")

        # ---- Timing derate (OCV) ----
        if cfg.timing_derate.late_factor != 1.0 or cfg.timing_derate.early_factor != 1.0:
            lines.append("# ---- Timing Derate (OCV) ----")
            lines.append(f'set_timing_derate {cfg.timing_derate.late_factor} -late')
            lines.append(f'set_timing_derate {cfg.timing_derate.early_factor} -early')
            lines.append("")

        # ---- VT percentage constraints ----
        if cfg.libraries.vt_percentage_constraint:
            lines.append("# ---- VT Percentage Constraints ----")
            for vt_name, percentage in cfg.libraries.vt_percentage_constraint.items():
                lines.append(f'set_multi_vth_constraint -type hard -cost area -lvth_groups [get_lib_cells */*{vt_name}*] -lvth_percentage {percentage} -include_blackboxes')
            lines.append("")

        # ---- Dont-use cells ----
        if cfg.libraries.dont_use_cells:
            lines.append("# ---- Dont-use cells ----")
            for cell in cfg.libraries.dont_use_cells:
                lines.append(f'set_dont_use [get_lib_cells */{cell}]')
            lines.append("")

        # ---- Power optimization ----
        if cfg.synthesis.power_optimization:
            lines.append("# ---- Power Optimization ----")
            lines.append(f'set_total_power_strategy -effort {cfg.synthesis.power_effort}')
            lines.append(f'set_app_var power_cg_flatten {str(cfg.synthesis.flatten_cg).lower()}')
            lines.append(f'set_app_var power_cg_physically_aware_cg {str(cfg.synthesis.physically_aware_cg).lower()}')
            lines.append('set_app_var power_remove_redundant_clock_gates false')
            lines.append("")

        # ---- Compile options ----
        lines.append("# ---- Compile Options ----")
        lines.append('set_app_var compile_delete_unloaded_sequential_cells false')
        lines.append('set_app_var compile_seqmap_propagate_constants false')
        lines.append(f'set_app_var compile_enable_register_merging {str(cfg.synthesis.enable_register_merging).lower()}')
        lines.append('set_fix_multiple_port_nets -all -buffer_constants')
        lines.append('set_auto_disable_drc_nets -constant false -scan false')
        lines.append("")

        # ---- Delay calculation ----
        lines.append("# ---- Delay Calculation ----")
        lines.append(f'set_delay_calculation_options -preroute awe -awe_effort {cfg.synthesis.awe_effort} -postroute arnoldi -routed_clock arnoldi -arnoldi_effort {cfg.synthesis.arnoldi_effort}')
        lines.append("")

        # ---- Compile ----
        lines.append("# ---- Compile ----")
        compile_cmd = "compile_ultra"
        if cfg.synthesis.no_autoungroup:
            compile_cmd += " -no_autoungroup"
        if cfg.synthesis.timing_high_effort:
            compile_cmd += " -timing_high_effort_script"
        lines.append(compile_cmd)

        if cfg.synthesis.incremental_compile and cfg.synthesis.max_incremental_loops > 0:
            for i in range(cfg.synthesis.max_incremental_loops):
                lines.append(f'compile_ultra -incremental')
        lines.append("")

        # ---- Reports ----
        lines.append("# ---- Reports ----")
        lines.append('report_qor -significant_digits 4 > ./DC/report/qor.rpt')
        lines.append('report_timing -max_paths 100 -significant_digits 4 -nworst 1 -delay max -sort_by slack > ./DC/report/timing_setup.rpt')
        lines.append('report_timing -max_paths 100 -significant_digits 4 -nworst 1 -delay min -sort_by slack > ./DC/report/timing_hold.rpt')
        lines.append('report_area -hierarchy -nosplit > ./DC/report/area.rpt')
        lines.append('report_power -nosplit -hierarchy -hier_level 1 > ./DC/report/power.rpt')
        lines.append('report_constraint -all_violators -significant_digits 4 > ./DC/report/constraint.rpt')
        lines.append('report_cell > ./DC/report/cell.rpt')
        lines.append('report_threshold_voltage_group > ./DC/report/vt_group.rpt')
        lines.append('report_clock > ./DC/report/clock.rpt')
        lines.append('report_timing_derate > ./DC/report/derate.rpt')
        lines.append("")

        # ---- Write outputs ----
        lines.append("# ---- Write outputs ----")
        lines.append(f'change_names -rules verilog -hierarchy')
        lines.append(f'write -format verilog -hierarchy -output ./DC/out/${{DESIGN_NAME}}.v')
        lines.append(f'write -format ddc -hierarchy -output ./DC/out/${{DESIGN_NAME}}.ddc')
        lines.append(f'write_sdc -nosplit ./DC/out/${{DESIGN_NAME}}.sdc')
        lines.append("")
        lines.append("exit")

        return "\n".join(lines)

    def parse_results(self) -> None:
        result = self.state.get_stage_result(FlowStage.SYNTHESIS)
        if self.work_dir is None:
            return

        rpt_dir = self.work_dir / "DC" / "report"
        if not rpt_dir.exists():
            rpt_dir = self.work_dir / "rpt"

        qor_file = rpt_dir / "qor.rpt"
        if qor_file.exists():
            self._parse_qor(qor_file.read_text(), result)

        tim_file = rpt_dir / "timing_setup.rpt"
        if tim_file.exists():
            self._parse_timing(tim_file.read_text(), result)

        area_file = rpt_dir / "area.rpt"
        if area_file.exists():
            self._parse_area(area_file.read_text(), result)

        power_file = rpt_dir / "power.rpt"
        if power_file.exists():
            self._parse_power(power_file.read_text(), result)

        out_dir = self.work_dir / "DC" / "out"
        if not out_dir.exists():
            out_dir = self.work_dir / "out"
        for suffix in ["v", "ddc", "sdc"]:
            name = f"syn_{self.state.config.design_name}.{suffix}"
            fpath = out_dir / f"{self.state.config.design_name}.{suffix}"
            if fpath.exists():
                self.state.record_artifact(f"syn_{suffix}", str(fpath))
                result.output_files[suffix] = str(fpath)

    def _parse_qor(self, text: str, result: StageResult):
        m = re.search(r'timing\s+([-.\d]+)\s+([-.\d]+)', text)
        if m:
            result.timing.wns = float(m.group(1))
            result.timing.tns = float(m.group(2))

        m = re.search(r'area\s+([-.\d]+)', text)
        if m:
            result.area.cell_area = float(m.group(1))

        m = re.search(r'Number of cells:\s+(\d+)', text)
        if m:
            result.area.num_std_cells = int(m.group(1))

    def _parse_timing(self, text: str, result: StageResult):
        m = re.search(r'slack\s+\((\w+)\)\s+([-.\d]+)', text)
        if m:
            slack_val = float(m.group(2))
            if result.timing.wns is None or slack_val < (result.timing.wns or 0):
                result.timing.wns = slack_val

        violations = len(re.findall(r'slack\s+\(\w+\)\s+([-.\d]+)', text))
        if violations > 0:
            neg_paths = sum(1 for m2 in re.finditer(
                r'slack\s+\(\w+\)\s+([-.\d]+)', text
            ) if float(m2.group(1)) < 0)
            result.timing.num_violating_paths = neg_paths

    def _parse_area(self, text: str, result: StageResult):
        m = re.search(r'Total cell area:\s+([-.\d]+)', text)
        if m:
            result.area.cell_area = float(m.group(1))

        m = re.search(r'Total area:\s+([-.\d]+)', text)
        if m:
            result.area.total_area = float(m.group(1))

        seq_count = 0
        comb_count = 0
        for line in text.splitlines():
            if re.match(r'\s*(Combinational|Sequential) cell count:', line):
                nums = re.findall(r'(\d+)', line)
                if 'Combinational' in line and nums:
                    comb_count = int(nums[0])
                elif 'Sequential' in line and nums:
                    seq_count = int(nums[0])
        if comb_count or seq_count:
            result.area.num_std_cells = comb_count + seq_count

    def _parse_power(self, text: str, result: StageResult):
        m = re.search(r'Total\s+([-.\d]+)\s+([-.\d]+)\s+([-.\d]+)\s+([-.\d]+)', text)
        if m:
            result.power.leakage_power_mw = float(m.group(1)) * 1000
            result.power.dynamic_power_mw = float(m.group(2)) * 1000
            result.power.short_circuit_power_mw = float(m.group(3)) * 1000
            result.power.total_power_mw = float(m.group(4)) * 1000
