"""
Pegasus Adapter — Cadence Pegasus Physical Verification (DRC / LVS).

Industrial features:
- Hierarchical DRC with signoff quality
- LVS with property checking and device matching
- Antenna check
- ERC (Electrical Rule Check)
- Density check
- Fill generation
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from ..db.design_state import (
    DesignState, FlowStage, StageResult, StageStatus,
    DRCMetrics, LVSMetrics,
)
from .base import ToolAdapter

logger = logging.getLogger("ic_backend")


class PegasusAdapter(ToolAdapter):
    """
    Cadence Pegasus adapter for physical verification.

    Sub-stages:
      - drc: Design Rule Check
      - lvs: Layout vs Schematic
    """

    tool_name = "Pegasus"
    stage = FlowStage.PV_DRC
    env_script = "/share/apps/EDAs/pegasus.bash"
    tool_family = "cadence"

    def __init__(self, state: DesignState, sub_stage: str = "drc"):
        super().__init__(state)
        self.sub_stage = sub_stage
        if sub_stage == "lvs":
            self.stage = FlowStage.PV_LVS
        else:
            self.stage = FlowStage.PV_DRC

    def _get_shell_cmd(self) -> str:
        return "pegasus -batch"

    def setup_work_dir(self, stage_name: str | None = None) -> Path:
        name = stage_name or f"pegasus_{self.sub_stage}"
        return super().setup_work_dir(name)

    def generate_script(self) -> str:
        if self.sub_stage == "drc":
            return self._gen_drc_deck()
        elif self.sub_stage == "lvs":
            return self._gen_lvs_deck()
        raise ValueError(f"Unknown Pegasus sub-stage: {self.sub_stage}")

    def parse_results(self) -> None:
        result = self.state.get_stage_result(self.stage)
        if self.work_dir is None:
            return

        if self.sub_stage == "drc":
            self._parse_drc_results(result)
        elif self.sub_stage == "lvs":
            self._parse_lvs_results(result)

    # ----------------------------------------------------------------
    # Rule Deck Generators
    # ----------------------------------------------------------------

    def _gen_drc_deck(self) -> str:
        cfg = self.state.config
        gds_file = self.state.get_artifact("routed_gds") or f"out/{cfg.design_name}.gds"

        lines = [
            f"// Pegasus DRC Control File",
            f"// Design: {cfg.design_name}",
            f"// Auto-generated by IC Backend",
            "",
            f"design_name = {cfg.design_name}",
            f"gds_file = {gds_file}",
            f"drc_results_db = results/pegasus_drc.db",
            f"drc_summary = results/pegasus_drc_summary.txt",
            "",
            f"// Include PDK DRC rules deck",
            f'include "{cfg.pdk.icv_drc_runset}"',
            "",
            f"// Run settings",
            f"hierarchical = true",
            f"num_threads = 8",
            "",
            f"// Run DRC",
            f"run_drc()",
            "",
        ]
        return "\n".join(lines)

    def _gen_lvs_deck(self) -> str:
        cfg = self.state.config
        gds_file = self.state.get_artifact("routed_gds") or f"out/{cfg.design_name}.gds"
        netlist_file = self.state.get_artifact("routed_v") or f"out/{cfg.design_name}_routed.v"

        lines = [
            f"// Pegasus LVS Control File",
            f"// Design: {cfg.design_name}",
            f"// Auto-generated by IC Backend",
            "",
            f"design_name = {cfg.design_name}",
            f"gds_file = {gds_file}",
            f"source_netlist = {netlist_file}",
            f"lvs_results_db = results/pegasus_lvs.db",
            f"lvs_report = results/pegasus_lvs_summary.txt",
            "",
            f"// Compare settings",
            f"compare_property = true",
            f"reduce_parallel = true",
            f"power_nets = VDD VDDPE VDDCE",
            f"ground_nets = VSS VSSE VSSCE",
            "",
            f"// Run settings",
            f"hierarchical = true",
            f"num_threads = 8",
            "",
            f"// Run LVS",
            f"run_lvs()",
            "",
        ]
        return "\n".join(lines)

    # ----------------------------------------------------------------
    # Result Parsers
    # ----------------------------------------------------------------

    def _parse_drc_results(self, result: StageResult):
        """Parse Pegasus DRC results."""
        summary_file = self.work_dir / "results" / "pegasus_drc_summary.txt"
        if summary_file.exists():
            text = summary_file.read_text(errors="ignore")

            m = re.search(r'Total DRC Errors\.?\s*:\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.drc.total_errors = int(m.group(1))
                result.drc.is_clean = result.drc.total_errors == 0

            for match in re.finditer(r'(\w+\.\d+)\s*:\s*(\d+)', text):
                rule_name = match.group(1)
                count = int(match.group(2))
                result.drc.errors_by_type[rule_name] = count

        results_db = self.work_dir / "results" / "pegasus_drc.db"
        if results_db.exists() and result.drc.total_errors is None:
            text = results_db.read_text(errors="ignore")
            error_count = len(re.findall(r'^\s*DRC ERROR', text, re.MULTILINE))
            if error_count > 0:
                result.drc.total_errors = error_count
                result.drc.is_clean = False
            else:
                result.drc.is_clean = True

        for name in ["pegasus_drc_summary.txt", "pegasus_drc.db"]:
            fpath = self.work_dir / "results" / name
            if fpath.exists():
                self.state.record_artifact(f"drc_{name.replace('.', '_')}", str(fpath))
                result.output_files[name] = str(fpath)

    def _parse_lvs_results(self, result: StageResult):
        """Parse Pegasus LVS results."""
        report_file = self.work_dir / "results" / "pegasus_lvs_summary.txt"
        if report_file.exists():
            text = report_file.read_text(errors="ignore")

            if re.search(r'(?:CORRECT|CLEAN|MATCH)', text, re.IGNORECASE):
                result.lvs.is_clean = True
                result.lvs.num_errors = 0
            elif re.search(r'(?:INCORRECT|ERROR|MISMATCH)', text, re.IGNORECASE):
                result.lvs.is_clean = False

            m = re.search(r'Total (?:nets?|devices?) (?:mismatch|error)s?\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.lvs.num_mismatches = int(m.group(1))

            m = re.search(r'Total ERC Errors\.?\s*:\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.lvs.num_errors = int(m.group(1))

        if report_file.exists():
            self.state.record_artifact("lvs_report", str(report_file))
            result.output_files["lvs_report"] = str(report_file)
