"""
PrimeTime Adapter — sign-off static timing analysis.

Modular architecture: each feature section is a separate generator function,
controlled by config flags in PTConfig. The YAML config file drives which
sections are included in the generated TCL script.

Industrial features (from DCICC Flow 4.6):
- SPEF back-annotation with auto format detection
- Multi-VT with VT group marking and dont_use control
- CPPR (Common Path Pessimism Removal)
- SI analysis (crosstalk delay)
- Path group timing analysis (per clock group, setup/hold)
- Power analysis (VCD/SAIF annotation)
- ECO fixing (setup, hold, DRC, power, leakage)
- Model extraction for hierarchical sign-off
- Session save/restore
- Analysis coverage reporting
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from ..db.design_state import (
    DesignState, FlowStage, StageResult, StageStatus,
    TimingMetrics, PowerMetrics,
)
from .base import ToolAdapter

logger = logging.getLogger("ic_backend")


class PTAdapter(ToolAdapter):
    tool_name = "PrimeTime"
    stage = FlowStage.STA_SIGNOFF
    env_script = "/share/apps/EDAs/syn22.bash"
    tool_family = "pt"

    def _get_shell_cmd(self) -> str:
        return "pt_shell"

    def setup_work_dir(self, stage_name: str = "primetime") -> Path:
        root = super().setup_work_dir(stage_name)
        (root / "PT" / "out").mkdir(parents=True, exist_ok=True)
        (root / "PT" / "report").mkdir(parents=True, exist_ok=True)
        return root

    # =========================================================================
    # Script generation — orchestrates all modular sections
    # =========================================================================
    def generate_script(self) -> str:
        cfg = self.state.config
        pt = cfg.pt
        sections: list[list[str]] = []

        sections.append(self._gen_header())
        sections.append(self._gen_directories())
        sections.append(self._gen_common_settings())
        sections.append(self._gen_libraries())
        sections.append(self._gen_read_design())
        sections.append(self._gen_dont_use())
        sections.append(self._gen_sdc())
        sections.append(self._gen_timing_derate())
        sections.append(self._gen_spef())
        sections.append(self._gen_update_timing())
        sections.append(self._gen_analysis_coverage())
        sections.append(self._gen_path_group_analysis())
        sections.append(self._gen_power_analysis())
        sections.append(self._gen_constraint_reports())
        sections.append(self._gen_eco_fixing())
        sections.append(self._gen_model_extraction())
        sections.append(self._gen_session_save())
        sections.append(["exit"])

        all_lines: list[str] = []
        for sec in sections:
            if sec:
                all_lines.extend(sec)
                all_lines.append("")

        return "\n".join(all_lines)

    # =========================================================================
    # Modular generator functions
    # =========================================================================

    def _gen_header(self) -> list[str]:
        cfg = self.state.config
        return [
            "# PrimeTime STA Sign-off Script",
            f"# Design: {cfg.design_name}",
            "# Generated by IC Backend Framework",
            "",
        ]

    def _gen_directories(self) -> list[str]:
        pt = self.state.config.pt
        lines = []
        if pt.report_path:
            lines.append(f'if {{![file isdirectory "{pt.report_path}"]}} {{')
            lines.append(f'    file mkdir "{pt.report_path}"')
            lines.append("}")
        if pt.output_path:
            lines.append(f'if {{![file isdirectory "{pt.output_path}"]}} {{')
            lines.append(f'    file mkdir "{pt.output_path}"')
            lines.append("}")
        return lines

    def _gen_common_settings(self) -> list[str]:
        pt = self.state.config.pt
        lines = [
            "# ---- Common Settings ----",
            f"set_host_options -max_cores {pt.num_cores}",
            f'set hierarchy_separator "/"',
            "set sh_source_uses_search_path true",
            f"set report_default_significant_digits {pt.significant_digits}",
            "set link_create_black_boxes false",
        ]
        if pt.enable_cppr:
            lines.append("set timing_remove_clock_reconvergence_pessimism true")
            lines.append("set timing_clock_reconvergence_pessimism same_transition")
            lines.append(f"set timing_crpr_threshold_ps {pt.cppr_threshold_ps}")

        if pt.save_pin_arrival_and_slack:
            lines.append("set timing_save_pin_arrival_and_slack true")

        if pt.enable_si_analysis:
            lines.append("set si_enable_analysis true")

        if pt.enable_power_analysis:
            lines.append("set power_enable_analysis true")
            lines.append("set power_clock_network_include_register_clock_pin_power false")

        lines.append("set read_parasitics_load_locations true")
        if pt.delay_calc_mode:
            lines.append(f"set delay_calc_waveform_analysis_mode {pt.delay_calc_mode}")

        return lines

    def _gen_libraries(self) -> list[str]:
        pt = self.state.config.pt
        cfg = self.state.config
        lines = ["# ---- Libraries ----"]

        # Search path
        search_dirs = set()
        for p in cfg.libraries.std_cell_libs + cfg.libraries.io_libs + cfg.libraries.macro_libs:
            search_dirs.add(str(Path(p).parent))
        search_dirs.update(pt.search_path)
        if search_dirs:
            lines.append(f'set search_path [concat $search_path [list {" ".join(sorted(search_dirs))}]]')

        # Target library
        lib_names = [Path(p).name for p in cfg.libraries.std_cell_libs]
        lib_names.extend([Path(p).name for p in pt.target_library])
        if lib_names:
            lines.append(f'set target_library [list {" ".join(lib_names)}]')
        else:
            lines.append("set target_library [list]")

        # Link library
        link_parts = ["*"] + lib_names
        link_parts.extend([Path(p).name for p in pt.link_library])
        lines.append(f'set link_library [concat {" ".join(link_parts)}]')

        return lines

    def _gen_read_design(self) -> list[str]:
        cfg = self.state.config
        pt = cfg.pt
        lines = ["# ---- Read Design ----"]

        # Netlist
        netlist = pt.netlist_file
        if not netlist:
            netlist = self.state.get_artifact("syn_v")
        if not netlist:
            netlist = str(Path(self.state.work_root).resolve() / "synthesis" / "DC" / "out" / f"{cfg.design_name}.v")
        lines.append(f'read_verilog "{netlist}"')
        lines.append(f'link_design "{cfg.top_module}"')

        return lines

    def _gen_dont_use(self) -> list[str]:
        pt = self.state.config.pt
        lines = []

        # VT group marking
        if pt.vt_groups:
            lines.append("# ---- VT Group Marking ----")
            for lib_pattern, vt_name in pt.vt_groups.items():
                lines.append(
                    f'set_user_attribute [get_libs -regexp "{lib_pattern}"] '
                    f'default_threshold_voltage_group {vt_name}'
                )

        # Build dont_use list
        has_dont_use = (
            pt.dont_use_patterns
            or pt.custom_dont_use
            or pt.custom_remove_dontuse
        )
        if not has_dont_use:
            return lines

        lines.append("# ---- Dont-Use Cells ----")
        lines.append("set dont_use_cell_list [list]")

        for pattern in pt.dont_use_patterns:
            lines.append(
                f'append_to_collection -unique dont_use_cell_list '
                f'[get_lib_cells -regexp "{pattern}"]'
            )

        for cell in pt.custom_dont_use:
            lines.append(
                f'append_to_collection -unique dont_use_cell_list '
                f'[get_lib_cells */{cell}]'
            )

        if pt.custom_remove_dontuse:
            for cell in pt.custom_remove_dontuse:
                lines.append(
                    f'set dont_use_cell_list '
                    f'[remove_from_collection $dont_use_cell_list '
                    f'[get_lib_cells */{cell}]]'
                )

        lines.append("set_dont_use $dont_use_cell_list")
        return lines

    def _gen_sdc(self) -> list[str]:
        cfg = self.state.config
        pt = cfg.pt
        sdc = pt.sdc_file
        if not sdc:
            sdc = self.state.get_artifact("syn_sdc")
        if not sdc:
            sdc = str(Path(self.state.work_root).resolve() / "synthesis" / "DC" / "out" / f"{cfg.design_name}.sdc")
        lines = [
            "# ---- Read SDC ----",
            f'read_sdc "{sdc}"',
            "report_clock",
        ]
        # Clean parasitics before re-annotation
        lines.extend([
            "remove_capacitance [get_nets -hierarchical]",
            "remove_resistance [get_nets -hierarchical]",
        ])
        return lines

    def _gen_timing_derate(self) -> list[str]:
        pt = self.state.config.pt
        d = self.state.config.timing_derate
        late = pt.timing_derate_late if pt.timing_derate_late != 1.0 else d.late_factor
        early = pt.timing_derate_early if pt.timing_derate_early != 1.0 else d.early_factor
        if late == 1.0 and early == 1.0:
            return []
        lines = ["# ---- Timing Derate (OCV) ----"]
        if late != 1.0:
            lines.append(f"set_timing_derate {late} -late")
        if early != 1.0:
            lines.append(f"set_timing_derate {early} -early")
        lines.append("report_timing_derate")
        return lines

    def _gen_spef(self) -> list[str]:
        cfg = self.state.config
        pt = cfg.pt
        spef = pt.spef_file
        if not spef:
            spef = self.state.get_artifact("icc2_route_opt_spef") or ""
        if not spef:
            return []

        lines = ["# ---- Read SPEF (Parasitics) ----"]
        if pt.spef_format == "auto":
            lines.append(f'if {{[file isfile "{spef}"]}} {{')
            lines.append(f'    set cur_spf_type [get_spf_type "{spef}"]')
            lines.append(
                f'    read_parasitics -format $cur_spf_type '
                f'-complete_with zero -keep_capacitive_coupling "{spef}"'
            )
            lines.append("}")
        else:
            lines.append(
                f'read_parasitics -format {pt.spef_format} '
                f'-complete_with zero -keep_capacitive_coupling "{spef}"'
            )
        return lines

    def _gen_update_timing(self) -> list[str]:
        return [
            "# ---- Update Timing ----",
            "check_timing",
            "update_timing -full",
        ]

    def _gen_analysis_coverage(self) -> list[str]:
        pt = self.state.config.pt
        if not pt.enable_analysis_coverage:
            return []
        return [
            "# ---- Analysis Coverage ----",
            "report_analysis_coverage",
            f'report_analysis_coverage > {pt.report_path}/analysis_coverage.rpt',
        ]

    def _gen_path_group_analysis(self) -> list[str]:
        pt = self.state.config.pt
        lines = [
            "# ---- Path Group Timing Analysis ----",
            'foreach_in_collection one_group [get_path_groups] {',
            '    set group_name [regsub -all -- {\\*} [get_attribute $one_group full_name] ""]',
        ]

        # Setup (max) timing
        flags = "-transition_time" if pt.report_transition else ""
        if pt.report_net:
            flags += " -net"
        if pt.report_capacitance:
            flags += " -capacitance"

        lines.extend([
            f'    report_timing -delay_type max {flags} \\',
            f'        -max_paths {pt.max_paths} -nworst {pt.nworst} \\',
            f'        -slack_lesser_than {pt.slack_lesser_than} \\',
            f'        -significant_digits {pt.significant_digits} \\',
            f'        -path_group $one_group \\',
            f'        > {pt.report_path}/${{group_name}}_max.tim',
        ])

        # Hold (min) timing
        lines.extend([
            f'    report_timing -delay_type min {flags} \\',
            f'        -max_paths {pt.max_paths} -nworst {pt.nworst} \\',
            f'        -slack_lesser_than {pt.slack_lesser_than} \\',
            f'        -significant_digits {pt.significant_digits} \\',
            f'        -path_group $one_group \\',
            f'        > {pt.report_path}/${{group_name}}_min.tim',
        ])

        lines.append("}")
        return lines

    def _gen_power_analysis(self) -> list[str]:
        pt = self.state.config.pt
        if not pt.enable_power_analysis:
            return []

        lines = ["# ---- Power Analysis ----"]

        if pt.vcd_file:
            lines.append(f'set power_analysis_mode {pt.power_mode}')
            strip = f'-strip_path {pt.vcd_strip_path}' if pt.vcd_strip_path else ""
            time_arg = ""
            if pt.vcd_time_range and len(pt.vcd_time_range) >= 2:
                time_arg = f'-time {{{pt.vcd_time_range[0]} {pt.vcd_time_range[1]}}}'
            lines.append(f'read_vcd {strip} "{pt.vcd_file}" {time_arg}')
        elif pt.saif_file:
            strip = pt.saif_strip_path or self.state.config.design_name
            lines.append(f'read_saif -strip_path {strip} "{pt.saif_file}"')

        lines.extend([
            f'report_power -verbose > {pt.report_path}/power.rpt',
            f'report_switching_activity > {pt.report_path}/switching_activity.rpt',
            f'report_switching_activity -list_not_annotated > {pt.report_path}/switching_activity_not_annotated.rpt',
            f'report_annotated_parasitics -check -list_not_annotated -max_nets 1000 > {pt.report_path}/parasitics_not_annotated.rpt',
        ])

        return lines

    def _gen_constraint_reports(self) -> list[str]:
        pt = self.state.config.pt
        return [
            "# ---- Constraint Reports ----",
            f'report_constraint -all_violators > {pt.report_path}/vios.rpt',
            f'report_threshold_voltage_group > {pt.report_path}/threshold_voltage_group.rpt',
            f'report_clock_timing -type summary > {pt.report_path}/clock_timing_summary.rpt',
        ]

    def _gen_eco_fixing(self) -> list[str]:
        pt = self.state.config.pt
        if not pt.enable_eco:
            return []

        lines = [
            "# ---- ECO Fixing ----",
            "set eco_allow_filler_cells_as_open_sites true",
            "set eco_report_unfixed_reason_max_endpoints 50",
            f'if {{![file isdirectory "{pt.report_path}/eco"]}} {{',
            f'    file mkdir "{pt.report_path}/eco"',
            "}",
            "set_eco_options \\",
        ]

        if pt.lef_library:
            lines.append(f'    -physical_lib_path "{pt.lef_library}" \\')
        if pt.final_def:
            lines.append(f'    -physical_design_path "{pt.final_def}" \\')
        lines.append(f'    -log_file {pt.report_path}/eco/pt_eco_physical.log')
        lines.append("report_eco_options")

        # Fix power
        if pt.fix_power:
            lines.append("# Fix power")
            lines.append("fix_eco_power -verbose")

        # Fix DRC (transition)
        if pt.fix_drc:
            lines.append("# Fix DRC (max_transition)")
            buf_list = " ".join(pt.fix_drc_buffer_list) if pt.fix_drc_buffer_list else ""
            buf_arg = f'-buffer_list [get_lib_cells {buf_list}]' if buf_list else ""
            lines.append(
                f'fix_eco_drc -type max_transition -verbose '
                f'-methods {{size_cell insert_buffer}} '
                f'{buf_arg} '
                f'-physical_mode {pt.eco_physical_mode}'
            )

        # Fix setup
        if pt.fix_setup:
            lines.append("# Fix setup timing")
            group_arg = ""
            if pt.fix_setup_groups:
                group_arg = f'-group {{{" ".join(pt.fix_setup_groups)}}}'
            lines.append(
                f'fix_eco_timing -type setup -methods {{size_cell}} '
                f'{group_arg} -ignore_drc '
                f'-setup_margin {pt.setup_opt_margin} '
                f'-hold_margin {pt.hold_opt_margin} '
                f'-slack_lesser_than {pt.setup_opt_slack} '
                f'-physical_mode {pt.eco_physical_mode} -verbose'
            )

        # Fix hold
        if pt.fix_hold:
            lines.append("# Fix hold timing")
            group_arg = ""
            if pt.fix_hold_groups:
                group_arg = f'-group {{{" ".join(pt.fix_hold_groups)}}}'
            buf_list = " ".join(pt.fix_hold_buffer_list) if pt.fix_hold_buffer_list else ""
            buf_arg = f'-buffer_list [get_lib_cells {buf_list}]' if buf_list else ""
            lines.append(
                f'fix_eco_timing -type hold '
                f'-methods {{size_cell insert_buffer_at_load_pins}} '
                f'{group_arg} {buf_arg} '
                f'-setup_margin {pt.setup_opt_margin} '
                f'-hold_margin {pt.hold_opt_margin} '
                f'-slack_lesser_than {pt.hold_opt_slack} '
                f'-physical_mode {pt.eco_physical_mode} -verbose'
            )

        # Fix leakage
        if pt.fix_leakage:
            lines.append("# Fix leakage power")
            priority = " ".join(pt.eco_power_priority) if pt.eco_power_priority else ""
            pri_arg = f'-pattern_priority {{{priority}}}' if priority else ""
            lines.append(
                f'fix_eco_power -verbose {pri_arg} '
                f'-setup_margin {pt.power_opt_margin}'
            )

        # Post-ECO reports
        lines.extend([
            "# Post-ECO reports",
            f'report_analysis_coverage > {pt.report_path}/eco/analysis_coverage.rpt',
            f'report_constraint -all_violators > {pt.report_path}/eco/vios.rpt',
            f'report_threshold_voltage_group > {pt.report_path}/eco/threshold_voltage_group.rpt',
        ])

        # Write ECO script
        eco_out = pt.eco_scripts_output or f"{pt.output_path}/eco_script.tcl"
        lines.append(f'write_changes -format icctcl -output "{eco_out}"')

        # Save ECO session
        if pt.save_session:
            session_name = pt.session_name or self.state.config.design_name
            lines.append(f'save_session {pt.output_path}/{session_name}_eco.session')

        return lines

    def _gen_model_extraction(self) -> list[str]:
        pt = self.state.config.pt
        if not pt.enable_model_extraction:
            return []
        cfg = self.state.config
        return [
            "# ---- Model Extraction ----",
            f"set_input_transition {pt.input_transition} [all_inputs]",
            f'extract_model -output {pt.output_path}/{cfg.design_name} -library_cell',
            f'extract_model -output {pt.output_path}/{cfg.design_name} -library_cell -format lib',
        ]

    def _gen_session_save(self) -> list[str]:
        pt = self.state.config.pt
        if not pt.save_session:
            return []
        session_name = pt.session_name or self.state.config.design_name
        return [
            "# ---- Save Session ----",
            f"save_session {pt.output_path}/{session_name}.session",
        ]

    # =========================================================================
    # Result parsing
    # =========================================================================
    def parse_results(self) -> None:
        result = self.state.get_stage_result(FlowStage.STA_SIGNOFF)
        if self.work_dir is None:
            return

        pt = self.state.config.pt
        rpt_dir = self.work_dir / "PT" / "report"
        if not rpt_dir.exists():
            return

        # Parse QoR
        qor_file = rpt_dir / "qor.rpt"
        if qor_file.exists():
            self._parse_qor(qor_file.read_text(), result)

        # Parse timing reports (path group files)
        for f in rpt_dir.glob("*_max.tim"):
            self._parse_timing(f.read_text(), result, is_setup=True)
        for f in rpt_dir.glob("*_min.tim"):
            self._parse_timing(f.read_text(), result, is_setup=False)

        # Also check legacy filenames
        for fname in ["timing_setup.rpt", "critical_paths_setup.rpt"]:
            fpath = rpt_dir / fname
            if fpath.exists():
                self._parse_timing(fpath.read_text(), result, is_setup=True)

        for fname in ["timing_hold.rpt", "critical_paths_hold.rpt"]:
            fpath = rpt_dir / fname
            if fpath.exists():
                self._parse_timing(fpath.read_text(), result, is_setup=False)

        # Parse constraints
        for fname in ["constraint.rpt", "vios.rpt"]:
            constraint_file = rpt_dir / fname
            if constraint_file.exists():
                self._parse_constraints(constraint_file.read_text(), result)

        # Parse power
        power_file = rpt_dir / "power.rpt"
        if power_file.exists():
            self._parse_power(power_file.read_text(), result)

        # Record outputs
        out_dir = self.work_dir / "PT" / "out"
        if out_dir.exists():
            for f in out_dir.iterdir():
                if f.is_file():
                    self.state.record_artifact(f"pt_{f.stem}", str(f))

    def _parse_qor(self, text: str, result: StageResult):
        m = re.search(r'timing\s+([-.\d]+)\s+([-.\d]+)', text)
        if m:
            result.timing.wns = float(m.group(1))
            result.timing.tns = float(m.group(2))

    def _parse_timing(self, text: str, result: StageResult, is_setup: bool):
        slacks = re.findall(r'slack\s+\(\w+\)\s+([-.\d]+)', text)
        if slacks:
            worst = min(float(s) for s in slacks)
            neg_slacks = [float(s) for s in slacks if float(s) < 0]
            if is_setup:
                if result.timing.wns is None or worst < result.timing.wns:
                    result.timing.wns = worst
                if neg_slacks:
                    result.timing.tns = sum(neg_slacks)
                result.timing.num_violating_paths = len(neg_slacks)
            else:
                result.timing.num_violating_paths = (result.timing.num_violating_paths or 0) + len(neg_slacks)

    def _parse_constraints(self, text: str, result: StageResult):
        tran_violations = len(re.findall(r'max_transition', text, re.IGNORECASE))
        cap_violations = len(re.findall(r'max_capacitance', text, re.IGNORECASE))
        fanout_violations = len(re.findall(r'max_fanout', text, re.IGNORECASE))
        result.timing.max_transition_violations = tran_violations
        result.timing.max_capacitance_violations = cap_violations
        result.timing.max_fanout_violations = fanout_violations

    def _parse_power(self, text: str, result: StageResult):
        # Try multi-column power report format
        m = re.search(r'Total\s+([-.\d]+)\s+([-.\d]+)\s+([-.\d]+)\s+([-.\d]+)', text)
        if m:
            result.power.leakage_power_mw = float(m.group(1)) * 1000
            result.power.dynamic_power_mw = float(m.group(2)) * 1000
            result.power.short_circuit_power_mw = float(m.group(3)) * 1000
            result.power.total_power_mw = float(m.group(4)) * 1000
            return

        # Try PT power report format (Internal Power, Switching Power, Leakage)
        internal = re.search(r'Internal\s+Power:\s+([-.\d]+)', text)
        switching = re.search(r'Switching\s+Power:\s+([-.\d]+)', text)
        leakage = re.search(r'Leakage\s+Power:\s+([-.\d]+)', text)
        total = re.search(r'Total\s+Power:\s+([-.\d]+)', text)

        if internal:
            result.power.dynamic_power_mw = float(internal.group(1)) * 1000
        if switching and result.power.dynamic_power_mw:
            result.power.dynamic_power_mw += float(switching.group(1)) * 1000
        elif switching:
            result.power.dynamic_power_mw = float(switching.group(1)) * 1000
        if leakage:
            result.power.leakage_power_mw = float(leakage.group(1)) * 1000
        if total:
            result.power.total_power_mw = float(total.group(1)) * 1000
