"""
StarRC Adapter — parasitic extraction (RC extraction).

Generates StarRC command files and parses extraction results.
Supports:
  - SPEF generation for timing analysis
  - Full-chip and block-level extraction
  - Coupled and decoupled modes
  - Multi-corner extraction (ss/tt/ff)
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from ..db.design_state import (
    DesignState, FlowStage, StageResult, StageStatus,
)
from .base import ToolAdapter

logger = logging.getLogger("ic_backend")


class StarRCAdapter(ToolAdapter):
    """
    StarRC adapter for parasitic extraction.

    Sub-stages:
      - spef: Generate SPEF for timing signoff
      - coupled: Coupled extraction with crosstalk
      - decoupled: Decoupled extraction (faster)
    """
    tool_name = "StarRC"
    stage = FlowStage.ROUTE_OPT  # extraction is part of route_opt
    env_script = "/share/apps/EDAs/mg.bash"
    tool_family = "starrc"

    def __init__(self, state: DesignState, sub_stage: str = "spef"):
        super().__init__(state)
        self.sub_stage = sub_stage

    def _get_shell_cmd(self) -> str:
        return "StarXtract"

    def setup_work_dir(self, stage_name: str | None = None) -> Path:
        name = stage_name or f"starrc_{self.sub_stage}"
        return super().setup_work_dir(name)

    def generate_script(self) -> str:
        """Generate StarRC command file."""
        return self._gen_cmd_file()

    def parse_results(self) -> None:
        """Parse StarRC extraction results."""
        result = self.state.get_stage_result(self.stage)
        if self.work_dir is None:
            return
        self._parse_extraction_results(result)

    # ----------------------------------------------------------------
    # Command File Generator
    # ----------------------------------------------------------------

    def _gen_cmd_file(self) -> str:
        cfg = self.state.config
        pdk = cfg.pdk

        gds_file = self.state.get_artifact("routed_gds") or f"out/{cfg.design_name}.gds"
        def_file = self.state.get_artifact("routed_def") or f"out/{cfg.design_name}.def"
        spef_file = f"out/{cfg.design_name}_{self.sub_stage}.spef"
        mapping_file = f"out/{cfg.design_name}.map"

        # Determine extraction corners
        corners = getattr(self.state.config, "starrc_corners", ["tt"])
        if isinstance(corners, str):
            corners = [corners]

        # Extraction mode
        coupling = self.sub_stage in ("coupled", "spef")
        extraction_mode = "COUPLED" if coupling else "DECOUPLED"

        lines = [
            f"/* StarRC Command File */",
            f"/* Design: {cfg.design_name} */",
            f"/* Sub-stage: {self.sub_stage} */",
            f"/* Auto-generated by ImplCraft */",
            "",
            f"BLOCK: {cfg.design_name}",
            f"GDS_FILE: {gds_file}",
            f"DEF_FILE: {def_file}",
            f"MAPPING_FILE: {mapping_file}",
            f"OPERATING_TEMPERATURE: 25",
            "",
            f"/* Technology */",
            f"TCAD_GRD_FILE: {pdk.tech_file}",
            f"LAYER_MAP_FILE: {mapping_file}",
            "",
            f"/* Extraction Control */",
            f"EXTRACTION: {extraction_mode}",
            f"COUPLING: {'YES' if coupling else 'NO'}",
            f"NETLIST_FILE: {spef_file}",
            f"OPERATING_FREQUENCY: {int(1000.0 / cfg.clock_period_ns)}MHz" if cfg.clock_period_ns else "",
            "",
            f"/* Netlist Format */",
            f"NETLIST_FORMAT: SPEF",
            f"SPEF_HIER_DELIMITER: /",
            f"SPEF_KEYWORDS: IEEE_1481",
            "",
            f"/* Extraction Options */",
            f"EXTRACT_VIA: YES",
            f"EXTRACT_MOS_DIFFUSION: YES",
            f"EXTRACT_CONTACT: YES",
            f"SELECT_NET: ALL",
            f"SELECT_CELL: ALL",
            "",
            f"/* Reduction */",
            f"REDUCTION: YES",
            f"REDUCTION_RELATIVE_ERROR: 0.01",
            f"REDUCTION_ABSOLUTE_ERROR: 0.001",
            "",
            f"/* Reports */",
            f"REPORT_FILE: starrc_{self.sub_stage}.rpt",
            f"STATISTICS_FILE: starrc_{self.sub_stage}.stat",
            f"ERRORS_FILE: starrc_{self.sub_stage}.errs",
            "",
        ]

        # Multi-corner extraction blocks
        for corner in corners:
            lines.extend([
                f"/* Corner: {corner} */",
                f"BLOCK_{corner.upper()}: {cfg.design_name}",
                f"TCAD_GRD_FILE_{corner.upper()}: {pdk.tech_file}",
                f"OPERATING_TEMPERATURE_{corner.upper()}: 25",
                "",
            ])

        return "\n".join(lines)

    # ----------------------------------------------------------------
    # Result Parsers
    # ----------------------------------------------------------------

    def _parse_extraction_results(self, result: StageResult):
        """Parse StarRC extraction report."""
        if self.work_dir is None:
            return

        # Parse report file
        report_file = self.work_dir / f"starrc_{self.sub_stage}.rpt"
        if report_file.exists():
            text = report_file.read_text(errors="ignore")

            # Extract net count
            m = re.search(r'Total\s+nets\s+extracted\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.metrics["nets_extracted"] = int(m.group(1))

            # Extract coupling count
            m = re.search(r'Total\s+coupling\s+capacitors\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.metrics["coupling_caps"] = int(m.group(1))

            # Check for errors
            m = re.search(r'Total\s+errors?\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                error_count = int(m.group(1))
                result.metrics["extraction_errors"] = error_count
                if error_count > 0:
                    result.messages.append(f"StarRC reported {error_count} extraction errors")

        # Parse statistics file
        stat_file = self.work_dir / f"starrc_{self.sub_stage}.stat"
        if stat_file.exists():
            text = stat_file.read_text(errors="ignore")

            m = re.search(r'Total\s+R\s+elements\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.metrics["r_elements"] = int(m.group(1))

            m = re.search(r'Total\s+C\s+elements\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.metrics["c_elements"] = int(m.group(1))

            m = re.search(r'Total\s+CC\s+elements\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.metrics["cc_elements"] = int(m.group(1))

        # Check errors file
        errs_file = self.work_dir / f"starrc_{self.sub_stage}.errs"
        if errs_file.exists():
            text = errs_file.read_text(errors="ignore")
            error_lines = [l.strip() for l in text.splitlines() if l.strip()]
            if error_lines:
                result.messages.extend(error_lines[:10])  # First 10 errors

        # Record output artifacts
        spef_file = self.work_dir / f"out/{self.state.config.design_name}_{self.sub_stage}.spef"
        if spef_file.exists():
            self.state.record_artifact(f"spef_{self.sub_stage}", str(spef_file))
            result.output_files[f"spef_{self.sub_stage}"] = str(spef_file)

        for name in [f"starrc_{self.sub_stage}.rpt", f"starrc_{self.sub_stage}.stat"]:
            fpath = self.work_dir / name
            if fpath.exists():
                result.output_files[name] = str(fpath)

        # Mark status based on error count
        errors = result.metrics.get("extraction_errors", 0)
        if errors == 0:
            result.status = StageStatus.PASSED
        else:
            result.status = StageStatus.WARNING
