"""
Calibre Adapter — physical verification (DRC / LVS).

Generates Calibre rule decks and parses results back into DRCMetrics / LVSMetrics.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from ..db.design_state import (
    DesignState, FlowStage, StageResult, StageStatus,
    DRCMetrics, LVSMetrics,
)
from .base import ToolAdapter

logger = logging.getLogger("ic_backend")


class CalibreAdapter(ToolAdapter):
    """
    Calibre adapter for DRC and LVS physical verification.

    Sub-stages:
      - drc: Design Rule Check
      - lvs: Layout vs Schematic
    """
    tool_name = "Calibre"
    stage = FlowStage.PV_DRC  # default
    env_script = "/share/apps/EDAs/mg.bash"

    def __init__(self, state: DesignState, sub_stage: str = "drc"):
        super().__init__(state)
        self.sub_stage = sub_stage
        if sub_stage == "lvs":
            self.stage = FlowStage.PV_LVS
        else:
            self.stage = FlowStage.PV_DRC

    def _get_shell_cmd(self) -> str:
        return "calibre -batch"

    def setup_work_dir(self, stage_name: str | None = None) -> Path:
        name = stage_name or f"calibre_{self.sub_stage}"
        return super().setup_work_dir(name)

    def generate_script(self) -> str:
        if self.sub_stage == "drc":
            return self._gen_drc_deck()
        elif self.sub_stage == "lvs":
            return self._gen_lvs_deck()
        raise ValueError(f"Unknown Calibre sub-stage: {self.sub_stage}")

    def parse_results(self) -> None:
        result = self.state.get_stage_result(self.stage)
        if self.work_dir is None:
            return

        if self.sub_stage == "drc":
            self._parse_drc_results(result)
        elif self.sub_stage == "lvs":
            self._parse_lvs_results(result)

    # ----------------------------------------------------------------
    # Rule Deck Generators
    # ----------------------------------------------------------------

    def _gen_drc_deck(self) -> str:
        cfg = self.state.config
        gds_file = self.state.get_artifact("routed_gds") or f"out/{cfg.design_name}.gds"

        lines = [
            f"// Calibre DRC Rule Deck",
            f"// Design: {cfg.design_name}",
            f"// Auto-generated by IC Backend MVP",
            "",
            f"PRECISION 1000",
            f"LAYOUT PATH \"{gds_file}\"",
            f"LAYOUT PRIMARY {cfg.design_name}",
            f"DRC RESULTS DATABASE drc_results.db",
            f"DRC MAXIMUM RESULTS ALL",
            f"DRC MAXIMUM VERTEX 4096",
            f"DRC CELL NAME YES",
            f"DRC SUMMARY REPORT drc_summary.rpt",
            "",
            f"// Include PDK DRC rules",
            f'INCLUDE "{cfg.pdk.tech_file}"',
            "",
        ]
        return "\n".join(lines)

    def _gen_lvs_deck(self) -> str:
        cfg = self.state.config
        gds_file = self.state.get_artifact("routed_gds") or f"out/{cfg.design_name}.gds"
        netlist_file = self.state.get_artifact("routed_v") or f"out/{cfg.design_name}_routed.v"

        lines = [
            f"// Calibre LVS Rule Deck",
            f"// Design: {cfg.design_name}",
            f"// Auto-generated by IC Backend MVP",
            "",
            f"PRECISION 1000",
            f"",
            f"LAYOUT PATH \"{gds_file}\"",
            f"LAYOUT PRIMARY {cfg.design_name}",
            f"LAYOUT SYSTEM GDSII",
            "",
            f"SOURCE PATH \"{netlist_file}\"",
            f"SOURCE PRIMARY {cfg.design_name}",
            f"SOURCE SYSTEM VERILOG",
            "",
            f"LVS REPORT lvs_report.rpt",
            f"LVS POWER NAME VDD VDDPE VDDCE",
            f"LVS GROUND NAME VSS VSSE VSSCE",
            f"LVS COMPARE PROPERTY",
            f"LVS DEVICE PROPERTY",
            f"LVS ABUTMENT BOX YES",
            f"LVS EXECUTE ERC",
            f"LVS REPORT MAXIMUM 1000",
            f"LVS ABORT ON SUPPLY ERROR YES",
            f"LVS FILTER UNUSED OPTION YES",
            f"LVS FILTER UNUSED DEVICE NO",
            "",
            f"// Include PDK LVS rules",
            f'INCLUDE "{cfg.pdk.tech_file}"',
            "",
        ]
        return "\n".join(lines)

    # ----------------------------------------------------------------
    # Result Parsers
    # ----------------------------------------------------------------

    def _parse_drc_results(self, result: StageResult):
        """Parse Calibre DRC results."""
        # Try summary report
        summary_file = self.work_dir / "drc_summary.rpt"
        if summary_file.exists():
            text = summary_file.read_text(errors="ignore")

            # Count total errors
            m = re.search(r'Total DRC Errors\.?\s*:\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.drc.total_errors = int(m.group(1))
                result.drc.is_clean = result.drc.total_errors == 0

            # Parse error types
            for match in re.finditer(r'(\w+\.\d+)\s+:\s*(\d+)', text):
                rule_name = match.group(1)
                count = int(match.group(2))
                result.drc.errors_by_type[rule_name] = count

        # Also check results database
        results_db = self.work_dir / "drc_results.db"
        if results_db.exists() and result.drc.total_errors is None:
            text = results_db.read_text(errors="ignore")
            error_count = len(re.findall(r'^\s*DRC ERROR', text, re.MULTILINE))
            if error_count > 0:
                result.drc.total_errors = error_count
                result.drc.is_clean = False
            else:
                result.drc.is_clean = True

        # Record artifacts
        for name in ["drc_summary.rpt", "drc_results.db"]:
            fpath = self.work_dir / name
            if fpath.exists():
                self.state.record_artifact(f"drc_{name.replace('.', '_')}", str(fpath))
                result.output_files[name] = str(fpath)

    def _parse_lvs_results(self, result: StageResult):
        """Parse Calibre LVS results."""
        report_file = self.work_dir / "lvs_report.rpt"
        if report_file.exists():
            text = report_file.read_text(errors="ignore")

            # Check for correct comparison
            if re.search(r'CORRECT', text, re.IGNORECASE):
                result.lvs.is_clean = True
                result.lvs.num_errors = 0
            elif re.search(r'INCORRECT', text, re.IGNORECASE):
                result.lvs.is_clean = False

            # Count mismatches
            m = re.search(r'Total (?:nets?|devices?) (?:mismatch|error)s?\s*[:=]\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.lvs.num_mismatches = int(m.group(1))

            # ERC errors
            m = re.search(r'Total ERC Errors\.?\s*:\s*(\d+)', text, re.IGNORECASE)
            if m:
                result.lvs.num_errors = int(m.group(1))

        # Record artifacts
        if report_file.exists():
            self.state.record_artifact("lvs_report", str(report_file))
            result.output_files["lvs_report"] = str(report_file)
